### ISSUE TITLE
jQuery form events in IE

### ISSUE THREAD

**Issue by brian-lc** [NUARIG/surveyor#1]
Checkbox and radio button events do not fire properly in IE. This causes a problem with dependency triggering.

**Comment by mgurley** [comment]
A link to a discussion of the nature of the problem:
http://stackoverflow.com/questions/208471/getting-jquery-to-recognise-change-in-ie

**Comment by yoon** [comment]
properly include jquery form plugin, fix ie change/click issue. closed by 0984c0bb65b3659ae23bf886b8ca2d1172b48129
