### ISSUE TITLE
Rails3 Branch - Dependent questions show by default instead of hide by default

### ISSUE THREAD

**Issue by jwoodlee** [NUARIG/surveyor#106]
Guys -

Just pulled down rails3 branch and im totally pumped to start working with it looks like a cool gem

A few questions or issue?

Dependent questions seem to show by default - which i personally think is wrong... They should show till condition is met.. Say I have a multi check box question with a dependent question and the rule of the dependent looks to see if an item is checked. The question shows until you click and unclick the answer referenced in the rule.. Just doesnt seem logical.. Is there a n appropriate work around

script/generate extend_surveyor  or more appropriately 
rails generate extend_surveyor doesnt seem to work in the Rails3 branch... Really looking to change understand the view logic..

Thanks guys - awesome work

**Comment by yoon** [comment]
fieldset.q_hidden should be hidden, but isn't.

the appropriate generator is rails generate surveyor:custom

Will make these updates to the rails3 branch
