### ISSUE TITLE
Rails 3 Branch, Answer :Text Combo for :pick =>:any

### ISSUE THREAD

**Issue by jwoodlee** [NUARIG/surveyor#107]
If a question is marked as a :pick =>:any answer does support a ,:string but not :text...
If question is marked without a pick indicator it supports :text properly..

**Comment by yoon** [comment]
That's correct. When we originally created question types, we allowed you to have checkboxes with strings, but didn't have any surveys with checkboxes and text boxes.

If you don't have a pick indicator, that means the pick is :none by default (no check box or radio buttons).

Do you have a need for checkboxes with text boxes next to them.?

**Comment by jwoodlee** [comment]
Yes. I was thinking of checkboxes and texboxes.. something like

have you ever used any of the following services
<checkbox> Yellow pages.com  ,Describe your Experience <textarea>
<checkbox> Google.com  ,Describe your Experience <textarea>

I guess you could do it in a dependent question but I found them hard
to understand in the dsl..

On Fri, Mar 18, 2011 at 11:51 AM, yoon
reply@reply.github.com
wrote:
