### ISSUE TITLE
Rails 3 Branch - Cant Run Generator to Create custom look and feel

### ISSUE THREAD

**Issue by jwoodlee** [NUARIG/surveyor#109]
woodlejb$ rails generate surveyor:custom
   identical  surveys/EXTENDING_SURVEYOR.md
   identical  app/controllers/surveyor_controller.rb
Could not find "app/views/layout/surveyor_custom.html.erb" in any of your source paths. Your current source paths are: 
/Users/woodlejb/railstation/myapp/lib/templates/surveyor/custom
/Library/Ruby/Gems/1.8/bundler/gems/surveyor-60aa59db3037/lib/generators/surveyor/templates

**Comment by yoon** [comment]
Closed by: b79b8ed60f6d8e38a483f7731ccc601de9a61654
