### ISSUE TITLE
Answer custom class styles appear on hidden field instead of the text field 

### ISSUE THREAD

**Issue by jdzak** [NUARIG/surveyor#113]
When using the custom_class attribute on an answer (type string), the custom class will not be added to the displayed input field.  Instead the CSS class will appear on the hidden field.

**Comment by yoon** [comment]
Merge branch &#39;113&#39; of https://github.com/jdzak/surveyor into jdzak-113
- &#39;113&#39; of https://github.com/jdzak/surveyor:
  Adding the custom_class attribute to text answer fields. Closed by eb0969347b068acf0cb3f3c5e0caf1244e5cf2d7.
