### ISSUE TITLE
display_response with Datetime-, Float- and Integer-values

### ISSUE THREAD

**Issue by glynx** [NUARIG/surveyor#115]
The display_response method does not include any code for displaying Datetime, Float and Integer values, because of this the type-name is used which sucks and needs to be improved.

**Comment by yoon** [comment]
We haven't invested much of our time into the results controller, which was contributed by the community. If you'd like to improve it, please feel free.

We're not usually motivated by "sucks and needs to be improved", though.

**Comment by glynx** [comment]
Currently we are busy with other aspects of our project, but we use the results-views and when there is free time, I will take a look at the helpers and include some improvements in there. There also seem to be some problems with nested responses, but I'll have a look at this later.

**Comment by yoon** [comment]
Consolidated into #414
