### ISSUE TITLE
COuld not find generator surveyor!

### ISSUE THREAD

**Issue by murgancovka** [NUARIG/surveyor#116]
Hey!
When i trying to write rails generate surveyor
i receive this: COuld not find generator surveyor!

could you help me?

using rails 3, ruby 1.8.7

**Comment by yoon** [comment]
The syntax is rails generate surveyor:install

Make sure you are using the rails 3 branch of surveyor.

**Comment by murgancovka** [comment]
This suits only for rails 3, yes?

**Comment by yoon** [comment]
http://groups.google.com/group/surveyor-dev
