### ISSUE TITLE
RESULTS OF SURVEYS

### ISSUE THREAD

**Issue by murgancovka** [NUARIG/surveyor#117]
I dont udnerstand, where i cansee my results of passed surveys?

**Comment by glynx** [comment]
The SurveyResultsController offers 2 actions to show the result of a table:
index: shows a table of all surveys and links to the results of each survey
show: shows a simple results table for a selected survey

The results view seems to be still work in progress. There seem to be some bugs as mentioned in other tickets. But this allows you to take a look how the data is extracted and build a views that match your needs on top of this.

**Comment by yoon** [comment]
Thanks glynx. You're right, the results view was added by another contributor, and we haven't had a chance to get to it yet.

**Comment by bnadav** [comment]
If a csv file containing the results for a a given survey is what you need - there is a rake task that does just that: 
  rake surveyor:dump SURVEY_ACCESS_CODE=<access_code> [OUTPUT_DIR=<dir>]

**Comment by murgancovka** [comment]
I''m Sorry for being newbie, firstly thanks for responses.
Questions , where csv file is? in what folder or its exists when surveys is completed? In web i can find result page for this surveyor , yaeah?

and .. I'm trying to edit survey.. ok i'm edited.. so i refresh my browser (server too), and after i see the same survey that was ... wtf? ow i can create my own surveys/own questions?

**Comment by yoon** [comment]
The csv file will be in the OUTPUT_DIR.

To create your own survey, make a file like the kitchen_sink_survey.rb with your own questions and import that.

If you want a response, please don't isolate yourself by saying "wtf" to the people that are helping you. As I mentioned in another ticket, this is not the place for support requests. Please direct your requests to the survyeor google group. http://groups.google.com/group/surveyor-dev
