### ISSUE TITLE
Required Answers

### ISSUE THREAD

**Issue by wawimundo** [NUARIG/surveyor#122]
Hi,

First of all, I would like to thank you for a very good survey system. I'm glad development is doing great.

Anyway, I think I'm missing something obvious, but is there a way to specify if a question is "required"? I'm thinking of something like this:

question_194 "I read a huge variety of books.", :pick => :one, :required => true
    answer "Very Much Like Me"
    answer "Like Me"
    answer "Neutral"
    answer "Unlike Me"
    answer "Very Much Unlike Me"

I'm setting up a 250 question survey and the client requested that all questions need to be answered.

Dave

**Comment by yoon** [comment]
You're looking for question.is_mandatory, which is set to true by default. How you enforce it, though, is up to you. We also have some methods on the ResponseSet model: mandatory_questions_complete?, progress_hash, is_answered?(question), and is_unanswered?(question). See lib/surveyor/models/response_set_methods.rb and question_methods.rb

**Comment by wawimundo** [comment]
Ok, sounds good. I'm gonna check out that module. Thanks Yoon.

Dave

**Comment by linojon** [comment]
hi, is there an example you could gist how to handle these?

**Comment by yoon** [comment]
linoj, not sure what you mean by "handle". question.is_mandatory = true by default, but the current surveyor controller doesn't do anything with it. You'd have to create a custom surveyor_controller (see the README about that) and use one of the ResponseSet methods mentioned above https://github.com/NUBIC/surveyor/issues/122#issuecomment-903221

**Comment by linojon** [comment]
this is what we tried but obviously the response set isnt updated before we check mandatory_questions_complete?

```
  def update
    @response_set = ResponseSet.find_by_access_code(params[:response_set_code])
    if @response_set.mandatory_questions_complete?
      super
    else
      path = edit_my_survey_path(:survey_code => @response_set.survey.access_code, :response_set_code => @response_set.access_code)
      redirect_to path, :flash => {:warning => "All Required Fields Need to be filled in" }
    end
  end
```

**Comment by yoon** [comment]
I would not use `super`, but instead overwrite the update code from lib/surveyor/surveyor_controller_methods and insert your modifications where they are needed.
