### ISSUE TITLE
Error on Section 2 of Kitchen Survey

### ISSUE THREAD

**Issue by kobaltz** [NUARIG/surveyor#130]
The first section seem to work properly, but the second section gives me this error:

NoMethodError in Surveyor#edit

Showing /home/initiald/.bundler/ruby/1.9.1/surveyor-a95169e36afc/app/views/partials/_question.html.haml where line #4 raised:

undefined method `id' for 0:Fixnum

Extracted source (around line #4):

1: -# TODO: js for slider
2: - rg ||= nil
3: - renderer = q.renderer(g ||= nil)
4: = f.inputs q_text(q), :id => rg ? "q_#{q.id}_#{rg.id}" : "q_#{q.id}", :class => "q_#{renderer} #{q.css_class(@response_set)}" do
5:   %span.help= q.help_text
6:   - case renderer
7:   - when :image, :label

Trace of template inclusion: /home/initiald/.bundler/ruby/1.9.1/surveyor-a95169e36afc/app/views/partials/_question_group.html.haml, /home/initiald/.bundler/ruby/1.9.1/surveyor-a95169e36afc/app/views/partials/_section.html.haml, /home/initiald/.bundler/ruby/1.9.1/surveyor-a95169e36afc/app/views/surveyor/edit.html.haml

**Comment by kobaltz** [comment]
It didn't make sense to me that this would be throwing an error. I found that it was the :repeater function on the second page.

**Comment by yoon** [comment]
Fixed by: aeefd33
