### ISSUE TITLE
rails3 branch, double call SurveyorController#update 

### ISSUE THREAD

**Issue by mprokopov** [NUARIG/surveyor#131]
There is some strange behaviour in sample app with surveyor gem at rails 3 branch.

After survey completion it calls SurveyorController#update as JSON and SurveyorController#update as HTML, 
so responses table has two or more doubled records.

**Comment by kobaltz** [comment]
I've had a similar issue with injecting a new survey into my database. It creates two surveys for each one injected.

**Comment by dwickwire** [comment]
I've also got this issue with Rails 3.0.7 and Ruby 1.9.2.  

I've drilled it down to the surveyor_controller_methods at this line
saved = @response_set.update_attributes(:responses_attributes => ResponseSet.reject_or_destroy_blanks(params[:r]))

For me grid questions do not get saved.

**Comment by jeperkins4** [comment]
Grid question responses are not getting saved.  We've tried to hack at it a bit.  Here is what we currently have, but it's causing numerous issues; such as duplicate response records and the multiple redirect issue.  Dependency Conditions go haywire as well.

class SurveyorController < ApplicationController
  include Surveyor::SurveyorControllerMethods

  def update
    #debugger
    super
    @response_set = ResponseSet.find_by_access_code(params[:response_set_code])
    unless @response_set.mandatory_questions_complete?
      path = edit_my_survey_path(:survey_code => @response_set.survey.access_code, :response_set_code => @response_set.access_code)
      #redirect_to path, :warning => "All Required Fields Need to be filled in"
      flash[:warning] = "All Required Fields Need to be filled in"
      redirect_to path
    end
  end

  def surveyor_finish
    #@response_set is set by gem's surveyor_controller action
    user_path @response_set.user_id
  end
end

**Comment by dwickwire** [comment]
This may have been resolved in the latest version (rails-3) branch.  Is this what you are using - v.0.20.0 ?

**Comment by yoon** [comment]
#272
