### ISSUE TITLE
:date doesn't save

### ISSUE THREAD

**Issue by kobaltz** [NUARIG/surveyor#133]
Anyone experience issues with the :date not saving? It populates whenever you select the date, but it looks like it is not saving the value when entered. Going back to the survey after taking it, it appears blank.

```
q "When would you like to meet for dinner?"
a :date
```

**Comment by gorenje** [comment]
i got it save if the date is in the future

**Comment by kobaltz** [comment]
Ah. That would make sense. I have been trying dates in the past (of the current year). Any idea how to have it store historical dates (from at least within the same year).

**Comment by gorenje** [comment]
Ok, sorry the real reason is that a date field sends the last value to the server, i.e. if you select a date, then first an empty string is sent to the server. Upon selecting a second date, the first date you set will be sent and stored on the server.

**Comment by gorenje** [comment]
Dunno, but maybe this commit might help you: https://github.com/gorenje/surveyor/commit/02e985e9e0f4cef7ca57dae2f6be04234f528cf5

**Comment by yoon** [comment]
Sorry, that last comment didn't make sense... looking into it.
