### ISSUE TITLE
Partials don't render when action controller caching is enabled

### ISSUE THREAD

**Issue by jdzak** [NUARIG/surveyor#134]
With this configuration the pages render correctly:

<pre>
# config/environments/staging.rb
config.action_controller.perform_caching = false
</pre>

With this configuration the pages don't render correctly:

<pre>
# config/environments/staging.rb
config.action_controller.perform_caching = true
</pre>

**Comment by yoon** [comment]
This seems to be a problem with the "cache" statement on line 12 of edit.html.haml

**Comment by yoon** [comment]
no longer caching
