### ISSUE TITLE
Firefox 4 & Chrome => Dependency not being removed

### ISSUE THREAD

**Issue by kobaltz** [NUARIG/surveyor#135]
Whenever testing the site from Firefox 4 or Google Chrome I usually try to test the different options on the survey I'm creating. I've noticed that Internet Explorer v7+ will remove the dependency questions if I change my previous answer to something else that no longer validates the dependency question. Any ideas? I'm targeting this survey to be used a broad spectrum. Most will be using IE, but the few that won't could be an issue.

Also, I've noticed within IE, if you have nested dependencies, If you go back and change the first question which triggers the initial dependency then it will not remove the nested one.

**Comment by kobaltz** [comment]
I was able to narrow down the issue to the jquery.surveyor.js file and to this line. Doing a bit of research, it sounds like JQuery and Firefox4 do not play well together.

 $.ajax({ type: "PUT", url: $(this).parents('form#survey_form').attr("action"), data: question_data, dataType: 'json', success: successfulSave })

**Comment by yoon** [comment]
This may (or may not) have been fixed with: https://github.com/NUBIC/surveyor/commit/8e5cf88db0be476bb064ddd036f40860753aa298

**Comment by yoon** [comment]
Could you let us know if you're still experiencing this issue with the latest surveyor?

**Comment by kobaltz** [comment]
The issues that I experienced are gone! Crazy how one little > can change the way the entire thing works.
