### ISSUE TITLE
Make question numbering configurable

### ISSUE THREAD

**Issue by jdzak** [NUARIG/surveyor#136]
In surveyor there is no easy way to exclude the question numbering.  In my application I copied all the partials that use q_text and modified the partials to use a custom q_text method which does not add numbers.  Is it possible to provide the ability to turn question numbering on/off?

**Comment by jefflunt** [comment]
Just to confirm, this adds a `next_question_number` helper that can be overridden, which makes custom/on/off numbering a per-app (not per survey) choice, is that correct?

**Comment by yoon** [comment]
Yes, that's correct. The helper also has access to the question object, which should make some fairly complex numbering schemes possible.
