### ISSUE TITLE
:pick => :any appends check boxes

### ISSUE THREAD

**Issue by kobaltz** [NUARIG/surveyor#138]
It looks like whenever you check a check box, it will create a record for that ID in the database. However, if you uncheck it, the record remains in the database. When you navigate back to the section that has the question, the checkbox remains checked. If you manually delete the record from the database then it becomes unchecked.

**Comment by yoon** [comment]
What version of surveyor are you using? I tried this with the latest, with the kitchen sink survey. I checked "Blue", unchecked it, went to section 2 and back, and there was no checkbox. Also, no response in the db.

**Comment by kobaltz** [comment]
I was using the RAILS3 latest version. I've switched over to 

gem 'surveyor', :git =>'git://github.com/gorenje/surveyor.git', :branch => 'rails3'

which one of their recent fixes solved my issue. I'm running Rails 3.0.8, Ruby 1.9.2p180, and Gems 1.7.2

https://github.com/gorenje/surveyor/commit/1947036ed1b2d19d3241acb7cd507b6035bd08cc
