### ISSUE TITLE
The dependency doesn't work with the radio buttons on version 0.19.4

### ISSUE THREAD

**Issue by Nataliya** [NUARIG/surveyor#143]
If one radio button is selected, the dependent section shows up, but if the other button is clicked - it's not disappearing. Here is a snipped code:

<pre>
survey "Test" do
  section "Test" do
    q_question_1 "Question1", :pick => :one
    a_yes "Yes"
    a_no "No"
    
    q_question_2 "Question2", :pick => :one
    a_yes "Yes"
    a_no "No"
    
    label "This is the dependency label"
    dependency :rule => "A or B"
    condition_A :q_question_1, "==", :a_yes
    condition_B :q_question_2, "==", :a_yes
  end
end
</pre>

**Comment by jdzak** [comment]
Fixed by #147.
