### ISSUE TITLE
uninitialized constant Surveyor::Models::SurveyMethods::UUID

### ISSUE THREAD

**Issue by dwickwire** [NUARIG/surveyor#144]
Using RVM
Rails 3.0.7
Ruby 1.9.2

First of all rake db:migrate won't work unless I follow this http://stackoverflow.com/questions/5287121/undefined-method-task-using-rake-0-9-0-beta-4

So the error in the title occurs when I run rake surveyor FILE=surveys/kitchen_sink_survey.rb

Here's my trace

*\* Invoke surveyor (first_time)
*\* Invoke surveyor:parse (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute surveyor:parse
--- Parsing /Users/dwickwire/Projects/quest/quest/surveys/kitchen_sink_survey.rb ---

survey rake aborted!
uninitialized constant Surveyor::Models::SurveyMethods::UUID
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/bundler/gems/surveyor-1f0c476f951d/lib/surveyor/parser.rb:19:in `instance_eval'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/bundler/gems/surveyor-1f0c476f951d/lib/surveyor/models/survey_methods.rb:34:in`initialize'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/bundler/gems/surveyor-1f0c476f951d/lib/surveyor/parser.rb:83:in `new'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/bundler/gems/surveyor-1f0c476f951d/lib/surveyor/parser.rb:83:in`parse_and_build'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/bundler/gems/surveyor-1f0c476f951d/lib/surveyor/parser.rb:34:in `method_missing'
(eval):1:in`parse'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/bundler/gems/surveyor-1f0c476f951d/lib/surveyor/parser.rb:19:in `instance_eval'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/bundler/gems/surveyor-1f0c476f951d/lib/surveyor/parser.rb:19:in`parse'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/bundler/gems/surveyor-1f0c476f951d/lib/surveyor/parser.rb:10:in `parse'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/bundler/gems/surveyor-1f0c476f951d/lib/tasks/surveyor_tasks.rake:10:in`block (2 levels) in <top (required)>'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/task.rb:205:in `call'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/task.rb:205:in`block in execute'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/task.rb:200:in `each'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/task.rb:200:in`execute'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/dwickwire/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/1.9.1/monitor.rb:201:in`mon_synchronize'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/task.rb:176:in`block in invoke_prerequisites'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/task.rb:174:in `each'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/task.rb:174:in`invoke_prerequisites'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/Users/dwickwire/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/1.9.1/monitor.rb:201:in`mon_synchronize'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/task.rb:144:in`invoke'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/application.rb:112:in `invoke_task'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/application.rb:90:in`block (2 levels) in top_level'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/application.rb:90:in `each'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/application.rb:90:in`block in top_level'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/application.rb:129:in `standard_exception_handling'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/application.rb:84:in`top_level'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/application.rb:62:in `block in run'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/application.rb:129:in`standard_exception_handling'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/lib/rake/application.rb:59:in `run'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/gems/rake-0.9.0/bin/rake:31:in`<top (required)>'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/bin/rake:19:in `load'
/Users/dwickwire/.rvm/gems/ruby-1.9.2-p136@rails3/bin/rake:19:in`<main>'
Tasks: TOP => surveyor => surveyor:parse

**Comment by dwickwire** [comment]
If I add  require 'uuid' at the head of survey_methods.rb the kitchen sink rake will run but then I get the folowing error when going to the localhost:3000/surveys

so now naturally the survey url looks like this because I've disabled UUID support.

http://localhost:3000/surveys/kitchen-sink-survey/%5B%22%20%22,%20%22%5C%22%22,%20%22%5C%22%22,%20%22%20%22,%20%22%5C%22%22,%20%22%5C%22%22,%20%22O%22,%20%22%20%22,%20%22z%22,%20%22%5C%22%22%5D/take

Somehow UUID was not available to the Survey::Parser object through add_dependency which led me to require it there, although its not a real fix, just a temporary hack.

**Comment by dwickwire** [comment]
I've tested and confirmed this with ruby 1.8.7 and Rails 3.0.7 on a new machine with a fresh install.    Also I've noticed that UUID is not in the gemspec.

**Comment by jdzak** [comment]
Associated pull request is #148.

**Comment by dwickwire** [comment]
I've tried exactly what you've got in your pull request, somehow the UUID's are different and then the browser URL doens't get a real UUID.  I think there's more to it, but I haven't been able to figure out what else is wrong yet. 

Also note that I've been getting "Unable to Update" through that solution.  Again not sure if its connected yet.

**Comment by yoon** [comment]
We may need to change our "development dependencies" to http://guides.rubygems.org/specification-reference/#add_runtime_dependency

**Comment by jdzak** [comment]
I tested my fix on the rails 2.3 branch, with ruby 1.8.7.  I'll test on rails3 with ruby 1.9.2.

**Comment by jdzak** [comment]
Ya, it looks like my fix only works on the master (rails 2.3) surveyor branch.  You're right, it looks like the rails 3 branch is missing a dependency in the gemspec, I'll fix this.  Thanks for finding that.

**Comment by jdzak** [comment]
Regenerated the gemspec on the rails 3 branch.  Tested and everything looks like it's working now.  Thanks everyone.

**Comment by dwickwire** [comment]
Excellent.  Thank you.
