### ISSUE TITLE
Warn a user when surveyor assets need to be updated

### ISSUE THREAD

**Issue by jdzak** [NUARIG/surveyor#151]
For surveyor applications upgrading to a new version of surveyor, the following scenario is a pain point because it can cause errors after an upgrade.
1. Surveyor assets (stylesheet, javascript, rails migrations, etc.) are updated
2. A new version of surveyor is released
3. A user points their surveyor application's Gemfile to the new version of surveyor
4. That user forgets to run 'script/generate surveyor' and 'rake db:migrate'

It would be helpful if we warn the user when the surveyor assets need to be updated.  Also, since a lot of users put their stylesheet changes right in the base surveyor.sass and we don't want the user to overwrite their changes, maybe we can talk about a standard way for users to add custom styles to their surveyor application.

**Comment by yoon** [comment]
Perhaps via: http://guides.rubygems.org/specification-reference/#post_install_message
