### ISSUE TITLE
Create an automated way to test the kitchen sink survey

### ISSUE THREAD

**Issue by jdzak** [NUARIG/surveyor#152]
Since a lot of users experience a problem with the kitchen sink survey, it would be nice to have an automated way to test the kitchen sink survey so we can add this to our CI testing and run it against different ruby versions.

**Comment by yoon** [comment]
what would you like to test about the kitchen sink survey? just that it renders, or specific features?

**Comment by jdzak** [comment]
I just liked how the kitchen sink survey covers most of the functionality in surveyor.  It may be though that we just need to addon to our existing cucumber tests.
