### ISSUE TITLE
Couldn't find Answer with ID=

### ISSUE THREAD

**Issue by dwickwire** [NUARIG/surveyor#155]
RVM with Ruby 1.9.2 and Rails 3.0.7

After successfully generating the schema and kitchen sink:

Click complicated questions, click "Previous Section" renders the error.

The POST returns a 404.

**Comment by dwickwire** [comment]
I've tried mysql2 gem with rails 3.0.7 and Ruby 1.9.2 and also the same issue.

**Comment by dwickwire** [comment]
On response_methods.rb line 22 adding a check for an array with an empty string resolves the bug.

exists? returns true rendering an error for the find on the next line.

**Comment by yoon** [comment]
We're not quite up to speed yet on Ruby 1.9.

Mark A. Wimbiscus Yoon
Systems Analyst/Programmer
Northwestern University Clinical and Translational Sciences Institute (NUCATS)
312-503-2343
yoon@northwestern.edu
http://www.nucats.northwestern.edu

On Fri, Jun 3, 2011 at 8:35 PM, dwickwire
reply@reply.github.com
wrote:

**Comment by jdzak** [comment]
dwickwire: Are you getting the same error as the one reported for #154?

**Comment by dwickwire** [comment]
The errors are the same, just apparently labeled differently for Ruby 1.9.x 

#154 resolves this issue.
