### ISSUE TITLE
Dependency evaluation fails for conditions having similar letters

### ISSUE THREAD

**Issue by Nataliya** [NUARIG/surveyor#159]
Dependency evaluation fails for conditions having similar letters

Combinations like "condition_AA" or "condition_A1" or "condition_a" are not properly evaluated

<pre>
survey "TEMP" do
  section "Phone Screen" do
    q_diabetes "Diabetes", :pick => :one
    a_yes "Yes", :string
    a_no "No"
    
    q_high_blood_preassure "High blood pressure?", :pick => :one
    a_yes "Yes", :string
    a_no "No"
    
    q "It looks like you are not eligible for this specific study at the time", :pick => :one
    a_yes "Yes"
    a_no "No"
    dependency :rule => "A or AA"
    condition_A :q_diabetes, "==", :a_yes
    condition_AA :q_high_blood_preassure, "==", :a_yes
  end
end
</pre>

**Comment by yoon** [comment]
I would strongly discourage the use of so many dependencies that you need this feature. Nevertheless, I'll be fixing this soon.
