### ISSUE TITLE
Conditional label on hide/show doesn't properly work. 

### ISSUE THREAD

**Issue by Nataliya** [NUARIG/surveyor#163]
Select 3 answers for the first question, the label will show up. Deselect one of the answers - the label is permanently displayed. 

<pre> 
survey "Survey" do
  section "Section" do   
     q_13_most_used_drug "Considering your use of the most used drug, in the past 12 months:", :pick => :any
     a_1 "A1"
     a_2 "B1"
     a_3 "C1"
     a_4 "D1"
     a_5 :omit
     
     q_13_second_most_used_drug "Considering your use of the 2nd most used drug, in the past 12 months:", :pick => :any
     a_1 "A1"
     a_2 "B1"
     a_3 "C1"
     a_4 "D1"
     a_5 :omit
     
     label "<b>CURRENT DRUG DEPENDENCE</b>"
     dependency :rule => "A or B"
     condition_A :q_13_most_used_drug, "count>=3"
     condition_B :q_13_most_second_used_drug, "count>=3"
  end
end
</pre>

**Comment by yoon** [comment]
condition_b refers to: q_13_most_second_used_drug, but should refer to: q_13_second_most_used_drug

I'm also not seeing this behavior on surveyor 0.19.6
