### ISSUE TITLE
Unable to remove a Survey

### ISSUE THREAD

**Issue by jeperkins4** [NUARIG/surveyor#165]
Using the rake surveyor:remove task (under the rails3 branch), the survey does not remove.

**Comment by yoon** [comment]
Does the survey appear as an option for removal, and then fail to be removed? Or does it just not appear as an option?

**Comment by jeperkins4** [comment]
No surveys appear as options, but the user is still prompted for a survey ID.  I was able to fix in my fork by changing line #45

<code>if surveys</code>

to 

<code>if surveys.size > 0</code>

**Comment by yoon** [comment]
If the survey doesn't appear as an option, it is likely that you have have associated response sets. For data integrity reasons, we don't allow you to remove surveys with associated response sets via the rake task (thus the prompt: "The following surveys do not have any response sets"). You have to manually remove the response sets via the console (so you are aware you are removing data), then the rake task will work.
