### ISSUE TITLE
Memory leak in the surveyor:dump rake task

### ISSUE THREAD

**Issue by bnadav** [NUARIG/surveyor#166]
It seems that running surveyor:dump rake task for a survey with a lot of associated response-sets (in the thousands),
causes the ruby process to grow beyond reasonable size.
I guess there must be a memory leak in converting data to csv, or writing to the output file.

I used ruby 1.8.7

Cheers

Nadav

**Comment by yoon** [comment]
Does the ruby process eat the memory and not return it? What is a reasonable size in this case?

**Comment by bnadav** [comment]
Yes it's the ruby process. It caused my pc to stop responding after running for a while. I had to kill the process.
This happens when trying to dump thousands of response sets.

**Comment by yoon** [comment]
What I meant to say is that memory consumption and a memory leak (where memory is consumed, and not released) are different issues. I tried this with the kitchen sink survey, one response per question, 100,000 response sets, benchmarking 20 times, and had no problems with ree on OSX. It's not clear to me that this is a surveyor issue. I would suggest trying to modify the surveyor dump rake task from:

File.open(full_path, 'w') do |f|
  survey.response_sets.each_with_index{|r,i| f.write(r.to_csv(true, i == 0)) } # print access code every time, print_header first time
end

to:

survey.response_sets.each_with_index do |r,i|
    File.open(full_path, 'w'){|f| f.write(r.to_csv(true, i == 0))}
end

and see if trading off File open/close cycles for memory helps.
