### ISSUE TITLE
Setting display_type on the repeater removes "add row" 

### ISSUE THREAD

**Issue by Nataliya** [NUARIG/surveyor#167]
For surveyor 0.19.6

<pre>
survey "Test" do
  section "Test" do
    repeater "repeater", :display_type => :block do
       q "<b>Question 1</b>", :help_text => "Refer to the table above"
       a :string

       q "<b>Question 2</b>", :help_text => "1-n To be filled in by Web application"
       a :string
    end
  end
end
</pre>

**Comment by yoon** [comment]
There is no :display_type => :block defined for groups. Repeater is just a shortcut for making a QuestionGroup with :display_type => :repeater.
