### ISSUE TITLE
undefined method `api_id'

### ISSUE THREAD

**Issue by markcap** [NUARIG/surveyor#168]
When I try making a survey I'm getting this error: 

rake surveyor FILE=surveys/kitchen_sink_survey.rb
--- Parsing /Users/CRL00265/Documents/systemsinsync/surveys/kitchen_sink_survey.rb ---

survey rake aborted!
undefined method `api_id' for #Survey:0x00000104175480

Tasks: TOP => surveyor => surveyor:parse

I created a couple surveys before but for some reason I get this error on all of them now. I'm using ruby 1.9.2 rails 3.0.9

**Comment by jdzak** [comment]
There is a new migration in version 0.9.5 of surveyor that adds this column
to the surveys table.  You need to re-run 'script/generate surveyor' to copy
over the new migration into your project and then run 'rake db:migrate'.

There's an open feature request to make the upgrade process smoother for users.  #151.

**Comment by markcap** [comment]
thank you :)
