### ISSUE TITLE
some question types aren't saving

### ISSUE THREAD

**Issue by markcap** [NUARIG/surveyor#169]
Hi, I've noticed that some question types just don't save in surveys. It gives an "Unable to update survey" flash message and doesn't get saved to the database. The following are taken from the kitchen sink survey:

Section 1: Questions 2, 9, 15
Section 2: Questions 1, 2, 3

From what I gather so far, it doesn't save anything with :pick => any, anything with a grid, or anything with the JS calendar selector. Maybe I'm just missing something, but so far no luck in figuring it out.  Ruby 1.9.2 and Rails 3.0.9

**Comment by jdzak** [comment]
Are there any errors being thrown by the server?  If so, a stack trace would
be very helpful.

Thanks,
John

**Comment by markcap** [comment]
I don't see any errors, but here's the action in my log file:

Started POST "/surveys/kitchen-sink-survey/otcHZki2Rv" for 127.0.0.1 at 2011-06-23 13:15:20 -0500
  Processing by SurveyorController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"Pas5Tk+7UtGzXUEnyM8iCGiq/gTxEcca21RBwiL6aEo=", "section"=>{"3"=>"Complicated questions"}, "r"=>{"1"=>{"question_id"=>"3"}, "2"=>{"question_id"=>"4", "answer_id"=>["", "9"]}, "3"=>{"question_id"=>"4", "answer_id"=>["", "10"]}, "4"=>{"question_id"=>"4", "answer_id"=>["", "11"]}, "5"=>{"question_id"=>"4", "answer_id"=>[""]}, "6"=>{"question_id"=>"4", "answer_id"=>[""]}, "7"=>{"question_id"=>"5", "answer_id"=>"14", "text_value"=>""}, "8"=>{"question_id"=>"6", "answer_id"=>"15", "text_value"=>""}, "9"=>{"question_id"=>"7", "answer_id"=>"16", "string_value"=>""}, "10"=>{"question_id"=>"8", "answer_id"=>"17", "string_value"=>""}, "11"=>{"question_id"=>"9", "answer_id"=>"18", "string_value"=>""}, "12"=>{"question_id"=>"11", "answer_id"=>"19", "string_value"=>""}, "13"=>{"question_id"=>"11", "answer_id"=>"20", "string_value"=>""}, "14"=>{"question_id"=>"11", "answer_id"=>"21", "string_value"=>""}, "15"=>{"question_id"=>"12", "answer_id"=>"22", "integer_value"=>""}, "16"=>{"question_id"=>"13", "answer_id"=>"23", "text_value"=>""}, "17"=>{"question_id"=>"14", "answer_id"=>"24", "datetime_value(1i)"=>"", "datetime_value(2i)"=>"", "datetime_value(3i)"=>"", "datetime_value(4i)"=>"", "datetime_value(5i)"=>""}, "18"=>{"question_id"=>"15", "answer_id"=>"25", "datetime_value(1i)"=>"1", "datetime_value(2i)"=>"1", "datetime_value(3i)"=>"1", "datetime_value(4i)"=>"", "datetime_value(5i)"=>""}, "19"=>{"question_id"=>"16", "answer_id"=>"26", "datetime_value"=>""}, "20"=>{"question_id"=>"17", "answer_id"=>""}, "21"=>{"question_id"=>"18", "answer_id"=>""}, "22"=>{"question_id"=>"19", "answer_id"=>"42", "float_value"=>""}, "23"=>{"question_id"=>"20", "answer_id"=>"43", "float_value"=>""}, "24"=>{"question_id"=>"21", "answer_id"=>""}, "25"=>{"question_id"=>"22", "answer_id"=>""}, "26"=>{"question_id"=>"23", "answer_id"=>[""]}, "27"=>{"question_id"=>"23", "answer_id"=>[""]}, "28"=>{"question_id"=>"23", "answer_id"=>[""]}, "29"=>{"question_id"=>"23", "answer_id"=>[""]}, "30"=>{"question_id"=>"23", "answer_id"=>[""]}, "31"=>{"question_id"=>"23", "answer_id"=>[""]}, "32"=>{"question_id"=>"24"}}, "survey_code"=>"kitchen-sink-survey", "response_set_code"=>"otcHZki2Rv"}
  ResponseSet Load (0.2ms)  SELECT `response_sets`.\* FROM `response_sets` WHERE `response_sets`.`access_code` = 'otcHZki2Rv' LIMIT 1 FOR UPDATE
  Response Load (0.4ms)  SELECT `responses`.\* FROM `responses` WHERE (`responses`.response_set_id = 42)
  SQL (0.1ms)  BEGIN
  Question Load (0.3ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 4 ORDER BY display_order ASC LIMIT 1
  CACHE (0.0ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 4 ORDER BY display_order ASC LIMIT 1
  CACHE (0.0ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 4 ORDER BY display_order ASC LIMIT 1
  CACHE (0.0ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 4 ORDER BY display_order ASC LIMIT 1
  CACHE (0.0ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 4 ORDER BY display_order ASC LIMIT 1
  Question Load (0.3ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 5 ORDER BY display_order ASC LIMIT 1
  Question Load (0.2ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 6 ORDER BY display_order ASC LIMIT 1
  SQL (0.2ms)  SELECT 1 FROM `answers` WHERE `answers`.`id` = 16 ORDER BY display_order ASC LIMIT 1
  Answer Load (0.2ms)  SELECT `answers`.\* FROM `answers` WHERE `answers`.`id` = 16 ORDER BY display_order ASC LIMIT 1
  Question Load (0.3ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 7 ORDER BY display_order ASC LIMIT 1
  SQL (0.1ms)  SELECT 1 FROM `answers` WHERE `answers`.`id` = 17 ORDER BY display_order ASC LIMIT 1
  Answer Load (0.2ms)  SELECT `answers`.\* FROM `answers` WHERE `answers`.`id` = 17 ORDER BY display_order ASC LIMIT 1
  Question Load (0.2ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 8 ORDER BY display_order ASC LIMIT 1
  SQL (0.1ms)  SELECT 1 FROM `answers` WHERE `answers`.`id` = 18 ORDER BY display_order ASC LIMIT 1
  Answer Load (0.2ms)  SELECT `answers`.\* FROM `answers` WHERE `answers`.`id` = 18 ORDER BY display_order ASC LIMIT 1
  Question Load (0.2ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 9 ORDER BY display_order ASC LIMIT 1
  SQL (0.1ms)  SELECT 1 FROM `answers` WHERE `answers`.`id` = 19 ORDER BY display_order ASC LIMIT 1
  Answer Load (0.2ms)  SELECT `answers`.\* FROM `answers` WHERE `answers`.`id` = 19 ORDER BY display_order ASC LIMIT 1
  Question Load (0.2ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 11 ORDER BY display_order ASC LIMIT 1
  SQL (0.1ms)  SELECT 1 FROM `answers` WHERE `answers`.`id` = 20 ORDER BY display_order ASC LIMIT 1
  Answer Load (0.2ms)  SELECT `answers`.\* FROM `answers` WHERE `answers`.`id` = 20 ORDER BY display_order ASC LIMIT 1
  CACHE (0.0ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 11 ORDER BY display_order ASC LIMIT 1
  SQL (0.1ms)  SELECT 1 FROM `answers` WHERE `answers`.`id` = 21 ORDER BY display_order ASC LIMIT 1
  Answer Load (0.2ms)  SELECT `answers`.\* FROM `answers` WHERE `answers`.`id` = 21 ORDER BY display_order ASC LIMIT 1
  CACHE (0.0ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 11 ORDER BY display_order ASC LIMIT 1
  Question Load (0.2ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 12 ORDER BY display_order ASC LIMIT 1
  Question Load (0.2ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 13 ORDER BY display_order ASC LIMIT 1
  Question Load (0.2ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 14 ORDER BY display_order ASC LIMIT 1
  Question Load (0.2ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 15 ORDER BY display_order ASC LIMIT 1
  Question Load (0.2ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 16 ORDER BY display_order ASC LIMIT 1
  Question Load (0.2ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 19 ORDER BY display_order ASC LIMIT 1
  Question Load (0.2ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 20 ORDER BY display_order ASC LIMIT 1
  Question Load (0.2ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 23 ORDER BY display_order ASC LIMIT 1
  CACHE (0.0ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 23 ORDER BY display_order ASC LIMIT 1
  CACHE (0.0ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 23 ORDER BY display_order ASC LIMIT 1
  CACHE (0.0ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 23 ORDER BY display_order ASC LIMIT 1
  CACHE (0.0ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 23 ORDER BY display_order ASC LIMIT 1
  CACHE (0.0ms)  SELECT `questions`.\* FROM `questions` WHERE `questions`.`id` = 23 ORDER BY display_order ASC LIMIT 1
  SQL (0.4ms)  SELECT 1 FROM `response_sets` WHERE (`response_sets`.`access_code` = BINARY 'otcHZki2Rv') AND (`response_sets`.id <> 42) LIMIT 1
  CACHE (0.0ms)  SELECT 1 FROM `response_sets` WHERE (`response_sets`.`access_code` = BINARY 'otcHZki2Rv') AND (`response_sets`.id <> 42) LIMIT 1
  SQL (0.1ms)  COMMIT
Redirected to http://localhost:3000/surveys/kitchen-sink-survey/otcHZki2Rv/take?section=3
Completed 302 Found in 436ms

I saw a couple other people having problems with grids and calendar select.

**Comment by markcap** [comment]
I've determined this is a problem with maybe cancan or devise so I'm closing it for now. I'll post the answer when i figure out whats preventing it from being saved

**Comment by markcap** [comment]
Looks like an update of the gem was needed to fix this issue.
