### ISSUE TITLE
Using the :symbol option for config['default.finish'] does not work

### ISSUE THREAD

**Issue by mgurley** [NUARIG/surveyor#17]
Using the :symbol option for config['default.finish'] is supposed to delegate the generation of the url path upon the finish of a survey to a method in the host application's  ApplicationController.  This feature is not working.  It is always redirecting to /surveys

**Comment by yoon** [comment]
fixing case statement for config default.finish. closed by f97c0267c4f00b634d65015ef647c9e1b7760e02. thanks mike
