### ISSUE TITLE
Conditional questions don't appear when answer's name contains 'a_' in it

### ISSUE THREAD

**Issue by Nataliya** [NUARIG/surveyor#170]
<pre>
    q_data_collection "Comorbid disease data collection", :pick => :one
    a_via_chart_review_charlson "Via chart review (Charlson)"
    a_via_patient_interview "Via patient interview/questionnaire"
    
    q_myocardial_infaction "Myocardinal Infarction", :pick => :one
    a_yes "Yes"
    a_no "No"
    dependency :rule => "A"
    condition_A :q_data_collection, "==", :a_via_chart_review_charlson
</pre>

By removing 'via_' in the answer's name, the dependent question shows up.

**Comment by yoon** [comment]
this is also an issue with question references with q_ in them.
