### ISSUE TITLE
Differentiate between singular and plural versions of the noun

### ISSUE THREAD

**Issue by Nataliya** [NUARIG/surveyor#182]
Need a way to differentiate between singular and plural versions of the noun: 

Ex Question: IF MULTIPLE_GESTATION =2 OR 3, DISPLAY “BABIES” AS APPROPRIATE THROUGHOUT INSTRUMENT. OTHERWISE, DISPLAY “BABY.”

Possible solution would be to introduce the variable and then append it to the question/answer/label text.

**Comment by yoon** [comment]
An intermediate workaround could be to specify "child(ren)" or "baby(ies)".

**Comment by Nataliya** [comment]
Another example:

PROGRAMMER INSTRUCTIONS: 
• IF CHILD_SEX = 1, DISPLAY “his” AND “he” IN APPROPRIATE FIELDS THROUGHOUT INSTRUMENT.
• IF CHILD_SEX = 2, DISPLAY “her” AND “she” IN APPROPRIATE FIELDS THROUGHOUT INSTRUMENT.
• IF CHILD_SEX = 3, DISPLAY “him/her” AND “he/she” IN APPROPRIATE FIELDS THROUGHOUT INSTRUMENT.

**Comment by jdzak** [comment]
This is covered by #198.
