### ISSUE TITLE
Get the blank value from the field to use for comparisons

### ISSUE THREAD

**Issue by Nataliya** [NUARIG/surveyor#183]
Have to have a way to get the blank value from the field to use for comparisons. nil or empty string doesn't work. Thrown exception is:
ArgumentError (comparison of Fixnum with nil failed):
  /Users/nshurupova/work/surveyor/lib/surveyor/models/dependency_condition_methods.rb:54:in `send'
  /Users/nshurupova/work/surveyor/lib/surveyor/models/dependency_condition_methods.rb:54:in`is_met?'
  /Users/nshurupova/work/surveyor/lib/surveyor/models/dependency_condition_methods.rb:39:in `to_hash'
  /Users/nshurupova/work/surveyor/lib/surveyor/models/dependency_methods.rb:52:in`conditions_hash'

My code snippet:

<pre>
survey "temp" do
  section "Prepregnancy visit v10", :reference_identifier=>"prepregnancy_visit_v10" do

    q_hipv1_enter_height "How tall are you without shoes? ", :pick=>"one"
     a_1 "ENTER RESPONSE"
     a_neg1 "REFUSED"
     a_neg2 "DON'T KNOW"

     q_hipv1_height_ft "PORTION OF HEIGHT IN WHOLE FEET (e.g., 5)", :data_export_identifier=>"PREG_VISIT_1.HEIGHT_FT"
     a "FEET", :integer
     dependency :rule=>"A"
     condition_A :q_hipv1_enter_height, "==", :a_1

     label "The value you provided is outside the suggested range.<br>
      Appropriate range is:<br> 
       4 to 7 feet. <br> 
       This value is admissible, but you may wish to verify."
     dependency :rule=>"A or B"
     condition_A :q_hipv1_height_ft, "<", {:integer_value => "4"}
     condition_B :q_hipv1_height_ft, ">", {:integer_value => "7"}

     q_hipv1_ht_inch "ADDITIONAL PORTION OF HEIGHT IN INCHES (e.g., 7)", :display_type=>"string", :data_export_identifier=>"PREG_VISIT_1.HT_INCH"
     a "INCHES", :string
     dependency :rule=>"A"
     condition_A :q_hipv1_enter_height, "==", :a_1
     
     label "The value you provided is outside the suggested range.<br> 
       Appropriate ranges are:<br>
        0 to 11 inches when FEET value is specified.
        48 to 84 inches, when FEET value is blank.<br>
       This value is admissible, but you may wish to verify."
     dependency :rule=>"A or B or (E and C or D)"
     condition_A :q_hipv1_ht_inch, "<", {:integer_value => "0"}
     condition_B :q_hipv1_ht_inch, ">", {:integer_value => "11"}
     condition_C :q_hipv1_ht_inch, ">", {:integer_value => "84"}
     condition_D :q_hipv1_ht_inch, "<", {:integer_value => "48"}
     condition_E :q_hipv1_height_ft, "==", ""

  end
end
</pre>

**Comment by yoon** [comment]
Another example

<pre>
survey "Simple survey" do
  section "Basic questions" do
    q_hipv1_height_ft "PORTION OF HEIGHT IN WHOLE FEET (e.g., 5)", :data_export_identifier=>"PREG_VISIT_1.HEIGHT_FT"
    a "FEET", :integer

    q_hipv1_ht_inch "ADDITIONAL PORTION OF HEIGHT IN INCHES (e.g., 7)", :display_type=>"string", :data_export_identifier=>"PREG_VISIT_1.HT_INCH"
    a "INCHES", :integer

    label "The value you provided is outside the suggested range. Appropriate ranges are:<br>
      0 to 11 inches when FEET value is specified.<br>
      48 to 84 inches, when FEET value is blank.<br>
     This value is admissible, but you may wish to verify."
    dependency :rule => "E and G"
    condition_E :q_hipv1_height_ft, "count=0"
    condition_G :q_hipv1_ht_inch, "count>0"
  end
end
</pre>

**Comment by jdzak** [comment]
This is covered by #198.
