### ISSUE TITLE
RSpec test fails for ResponseSet when deleting previously checked checkbox response values

### ISSUE THREAD

**Issue by jeperkins4** [NUARIG/surveyor#184]
spec/models/response_set_spec.rb

Failures:

  1) ResponseSet should preserve response ids in checkboxes when removing another checkbox
     Failure/Error: @response_set.update_attributes!(:responses_attributes => ResponseSet.reject_or_destroy_blanks({"1"=>{"question_id"=>"9", "answer_id"=>"", "id" => initial_response_ids.first}}))
     ActiveRecord::RecordInvalid:
       Validation failed: Responses is invalid
     # ./spec/models/response_set_spec.rb:63:in `block (2 levels) in <top (required)>'

  2) ResponseSet should remove responses
     Failure/Error: @response_set.update_attributes!(:responses_attributes => {"2"=>{:question_id => 1, :id => r.id, :_destroy => true, :answer_id =>[""]}}).should be_true
     ActiveRecord::RecordInvalid:
       Validation failed: Responses is invalid
     # ./spec/models/response_set_spec.rb:125:in `block (2 levels) in <top (required)>'

I've narrowed this down to the validation inside of the lib/surveyor/models/response_methods.rb   It appears that the validation on the presence of the answer_id is causing the _destroy call to fail.   I have been able to get it to work in the console if I set the ResponseSet with the responses_attributes, reload the ResponseSet and then save...

@response_set.response_attributes = {...}
@response_set.reload
@response_set.save!

But this does not work as a hack in passing the RSpec.

**Comment by jeperkins4** [comment]
1.9.2 and Rails 3.0.9

**Comment by jeperkins4** [comment]
This seems to work when answer_id => "" is deleted from the responses_attributes once the :_destroy => true has been merged into the hash.  But I am not certain yet of other unintended consequences.

**Comment by yoon** [comment]
This should be working on master.
