### ISSUE TITLE
Compare answers from different questions. 

### ISSUE THREAD

**Issue by Nataliya** [NUARIG/surveyor#185]
Need a way to compare answers from different questions. Example: 

question 1 =  "How many household members are supported by your total combined family income?"
question 2 = "How many of those people are children? Please include anyone under 18 years or anyone older than 18 years and in high school"

Display the label with warning if the answer to question 2 > answer to question 1

More examples:
1) question 1: "HOW MANY CHILDREN IN THIS HOUSEHOLD ARE ELIGIBLE FOR THE 3-MONTH CALL TODAY?"
question 2: "WHICH NUMBER CHILD IS THIS QUESTIONNAIRE FOR?"
PROGRAMMER INSTRUCTION: 
• question2 CANNOT BE GREATER THAN question1

2)
• INCLUDE A SOFT EDIT/WARNING IF CALCULATED AGE IS LESS THAN 2 MONTHS OR GREATER THAN 5 MONTHS.

**Comment by jdzak** [comment]
This is covered by #198.
