### ISSUE TITLE
Add an indicator to know If some questions were answered before

### ISSUE THREAD

**Issue by Nataliya** [NUARIG/surveyor#186]
If some questions were answered before and are pre-populated, need to have some kind of indication of that and be able to use it in the dependencies. 

Here are the example: 

PROGRAMMER INSTRUCTIONS:
• IF OWN_HOME WAS ASKED DURING PREGNANCY SCREENER OR PRE-PREGANCY VISIT, THEN ASK RECENT_MOVE; ELSE SKIP TO OWN_HOME.

PROGRAMMER INSTRUCTION:
• IF A PRE-PREGNANCY QUESTIONNAIRE WAS COMPLETED DISPLAY BRACKETEDTEXT: “The next questions may be similar to those asked the last time we spoke, but we are asking them again because sometimes the answers change.”

PROGRAMMER INSTRUCTIONS:
• ASK COMM_EMAIL ONLY IF A PRE-PREGNANCY INTERVIEW WAS COMPLETED;
• ELSE SKIP TO HAVE_EMAIL

PROGRAMMER INSTRUCTIONS: 
• ASK COMM_CELL ONLY IF A PRE-PREGNANCY INTERVIEW WAS COMPLETED
• ELSE SKIP TO CELL_PHONE_1

PROGRAMMER INSTRUCTIONS: 
• ASK COMM_CONTACT ONLY IF A PRE-PREGNANCY INTERVIEW WAS COMPLETED
•  ELSE SKIP TO CONTACT_1

Example from the other questionare:
    PROGRAMMER INSTRUCTIONS:
    • IF CHILD_NUM = 1 AND  NO PRIOR MATERNAL QUESTIONNAIRES WERE COMPLETED OR THE MOTHER WAS FIRST IDENTIFIED AT 
    THE BIRTH VISIT, GO TO MARISTAT.
    • IF CHILD_NUM > 1 AND NO PRIOR MATERNAL QUESTIONNAIRES WERE COMPLETED, OR THE MOTHER WAS FIRST IDENTIFIED AT 
    THE BIRTH VISIT, GO TO MARISTAT AND COMPLETE QUESTIONNAIRE FOR FIRST CHILD.  THEN BEGINNING AT CHILD_QNUM, 
    LOOP THROUGH INTERVIEWER-COMPLETED SECTIONS: SLEEP, CRYING PATTERNS, CHILD DEVELOPMENT AND PARENTING, CHILDCARE 
    ARRANGEMENTS HEALTHCARE, FOR EACH SUBSEQUENT CHILD.
    • IF CHILD_NUM =1 AND MOTHER WAS ENROLLED PRIOR TO OR DURING PREGNANCY AND HAS COMPLETED AT LEAST ONE QUESTIONNAIRE 
    BEFORE BIRTH, GO TO TIME_STAMP_3 AND COMPLETE QUESTIONNAIRE FOR FIRST CHILD.  THEN BEGINNING AT CHILD_QNUM, 
    LOOP THROUGH INTERVIEWER-COMPLETED SECTIONS: SLEEP, CRYING PATTERNS, CHILD DEVELOPMENT AND PARENTING, CHILDCARE 
    ARRANGEMENTS HEALTHCARE, FOR EACH SUBSEQUENT CHILD.

PROGRAMMER INSTRUCTION: 
• USING CHILD_DOB CALCULATE CHILD’S AGE TO THE NEAREST MONTH AND PRELOAD.

VISIT EVALUATION QUESTIONS MAY BE COMPLETED IN EITHER PAPI OR CASI MODE.
INTERVIEWER INSTRUCTIONS: 
• IF SAQ IS COMPLETED AS A PAPI, RECORD THE PARTICIPANT’S ID ON TOP OF INSTRUMENT

**Comment by jdzak** [comment]
This is covered by #198 and #196.
