### ISSUE TITLE
Substitute text from a response into a question or label text

### ISSUE THREAD

**Issue by Nataliya** [NUARIG/surveyor#187]
Here are the examples:

Is your name [INSERT PARTICIPANT NAME]?

Is your birth date [SHOW PARTICIPANT’S DATE OF BIRTH AS MM/DD/YYYY]?

PROGRAMMER INSTRUCTIONS: 
• PRELOAD CHILD’S NAME IF BABY_NAME COLLECTED AT BIRTH INTERVIEW.
• IF CNAME_CONFIRM = 1, SET C_FNAME C_LNAME TO KNOWN VALUE.

PROGRAMMER INSTRUCTION:
• IF C_FNAME AND C_LNAME = -1 or -2, SUBSTITUTE “YOUR CHILD” FOR C_FNAME IN REMAINER OF QUESTIONNAIRE.

 PROGRAMMER INSTRUCTIONS:
 •      PRELOAD CHILD_DOB COLLECTED AT BIRTH INTERVIEWAS MM/DD/YYYY
 •    IF CDOB_CONFIRM =1, SET CHILD_DOB TO KNOWN VALUE.

PROGRAMMER INSTRUCTIONS: 
• IF PARTICIPANT HAS REPORTED BEING PREGNANT WITH MULTIPLES FILL IN “BABIES’ AS APPROPRIATE THROUGHOUT INSTRUMENT

**Comment by jdzak** [comment]
We need to build a way to substitute text from previous answers into a question or label.  This method should also be compatible with iOS surveyor (mustache or javascript possibly).

**Comment by Nataliya** [comment]
• DISPLAY CORRECT SAMPLE_NUMBER AND DESCRIPTION FOR EACH LOOP IN SAMPLE_NUMBER AND SAMPLE_ID AND IN REPLACE TEXT IN BRACKETS WITH {SAMPLE_ID}, {SAMPLE_NUMBER} FOR EACH LOOP. 

(INS_ENV_TapWaterPestTech_DCI)

**Comment by Nataliya** [comment]
Here is the example:

<pre>
q_FATHER  "What is the first and last name of your baby’s father?", 
    :pick => :one,
    :data_export_identifier=>"PREG_VISIT_1_SAQ_2.FATHER_NAME"
    a_F_F_NAME_and_F_L_NAME "First and last name:", :string
    a_neg_1 "Refused"
    a_neg_2 "Don't know"

q_FATHER_SAME_HH "Is the father of your baby/[FIRST NAME OF FATHER] living in the same household as you?",

</pre>

**Comment by Nataliya** [comment]
opened ticket to prepopulate global values #259

**Comment by yoon** [comment]
Closed by 0b54243

**Comment by sridharraman** [comment]
I am unable to find the documentation on how to do this. I am trying to use the value of an answer in the text of a subsequent question. How do I do it?

Thanks.
