### ISSUE TITLE
Grid Questions still not saving

### ISSUE THREAD

**Issue by markcap** [NUARIG/surveyor#188]
grid questions in my own survey and kitchen sink survey aren't saving. Using the rails 3 branch and up to date surveyor.

**Comment by yoon** [comment]
Did you re-run script/generate surveyor, and is your jquery.surveyor.js up to date?

**Comment by markcap** [comment]
I did re-run the script/generate, and my jquery.surveyor.js is up to date, unless there's a more updated version somewhere that doesn't get installed through the generator.

**Comment by yoon** [comment]
Ok, I'm able to re-create the error now. Taking a look at the causes

**Comment by dwickwire** [comment]
I'm having this issue again on rails 3.0.9 with patch 0.20 on rails3 branch  - I'm getting a 500

**Comment by dwickwire** [comment]
Is this a bug in action dispatch?  The 500 trace gives

RuntimeError (Called id for nil, which would mistakenly be 4 -- if you really wanted the id of nil, use object_id):

but the trace only hits middleware code.

**Comment by markcap** [comment]
Not sure, I couldn't find much information based on the traces I was getting. I reverted my grid questions to :pick => :one types for now because I have a project due today that uses it. Hopefully I'll be able to move them back soon.

**Comment by dwickwire** [comment]
Its probably a jQuery selector issue but I can't confirm because I don't know what the update_attributes in SurveyorUpdate responses_attributes is expecting.

**Comment by dwickwire** [comment]
OK.  I've got a hack

Uncomment the "unless q.pick == "one" from line 6 on _answer.html.haml will allow surveys to update.

**Comment by markcap** [comment]
Will that mess with normal radio button questions? with :pick => :one

**Comment by dwickwire** [comment]
Bump.  If this could get resolved that would be great!  It is too deep into business logic for me to address a wholesome solution.

**Comment by rsutphin** [comment]
> Bump.

Bumping issues does not increase their priority. If it has any affect it will be to annoy the maintainers, which (all else being equal) will have the opposite effect.

That said, it turns out we do have a [failing feature](https://github.com/NUBIC/surveyor/blob/86720e6541/features/surveyor.feature#L237-263) for this issue. Apparently it did work in Rails 2.3.

**Comment by dwickwire** [comment]
Fair enough.

**Comment by rsutphin** [comment]
Some time [since 88ee9d5](https://github.com/NUBIC/surveyor/compare/88ee9d5...15d87c), the feature for grids began passing. It passes on all platforms and with both Rails 3.0 and 3.1.
