### ISSUE TITLE
to_a with mysql putting numbers in wrong place

### ISSUE THREAD

**Issue by pcasa** [NUARIG/surveyor#189]
from kitchen_sink demo I added (1..30).to_a.each{|num| a num.to_s} to some of my questions

but on some questions, it changes the answer to start at another number not "0"

with sqlite it works, but with mySql number are changed.

**Comment by pcasa** [comment]
can confirm that this only happens with mysql.  same machine with sqlite3 works fine.  looks like its actually in the view that selects it.

**Comment by yoon** [comment]
I don't see any 0's in your answers, so I'm a little confused.

I would try:

(1..30).to_a.each{|num| a num.to_s, :display_order => num }

Mark A. Wimbiscus Yoon
Systems Analyst/Programmer
Northwestern University Clinical and Translational Sciences Institute (NUCATS)
312-503-2343
yoon@northwestern.edu
http://www.nucats.northwestern.edu

On Tue, Jul 26, 2011 at 10:19 AM, pcasa
reply@reply.github.com
wrote:

**Comment by pcasa** [comment]
Can confirm that adding :display_order => num fixed issue.

thanks
