### ISSUE TITLE
Check the value in the multi-answers questions

### ISSUE THREAD

**Issue by Nataliya** [NUARIG/surveyor#193]
Need to have a way to check the entered value for the questions with couple of possible answers

<pre>
survey "temp" do
  section "INTRO", :reference_identifier=>"HOUSEHOLD_INVENTORY" do
    q_CIG_NOW_NUM "On days that you smoke, how many cigarettes do you smoke per day? If you smoke 1 cigarette or 
    less each day, please enter \"1.\"",
    :pick => :one
    a_number "NUMBER PER DAY", :integer
    a_neg_1 "REFUSED"
    a_neg_2 "DON’T KNOW"

# TODO: 
# PROGRAMMER INSTRUCTIONS: 
# • DISPLAY SOFT EDIT IF RESPONSE > 60
# • IF RESPONSE IS IN PACKS, CALCULATE 20 CIGARETTES PER PACK     
    label "The provided value is outside the suggested range. (Range < 60) This value is admissible, but you may wish to verify."
    dependency :rule=>"A"
    condition_A :q_CIG_NOW_NUM, ">", {:integer_value => "60"}     
  end
end
</pre>

**Comment by jdzak** [comment]
This is covered by #198.
