### ISSUE TITLE
Allow responses to be pre-populated when survey is started

### ISSUE THREAD

**Issue by jdzak** [NUARIG/surveyor#196]
When a survey is started we need a way to pre-populate survey responses using data passed in through the request.

**Comment by Nataliya** [comment]
Here is another example:
VISIT EVALUATION QUESTIONS MAY BE COMPLETED IN EITHER PAPI OR CASI MODE.

INTERVIEWER INSTRUCTIONS: 
• IF SAQ IS COMPLETED AS A PAPI, RECORD THE PARTICIPANT’S ID ON TOP OF INSTRUMENT

**Comment by seanvolution** [comment]
This is no longer necessary because NCS Navigator Core creates a response set prior to presenting the survey to the user.  Other applications could use the same approach.
