### ISSUE TITLE
Add a hidden field type

### ISSUE THREAD

**Issue by jdzak** [NUARIG/surveyor#197]
We need a way to create hidden fields in surveyor so we can store responses without them appearing to the person administering the survey.

This functionality can be used in conjunction with #196 and #187 to pass data into a survey, store it as a response, and then use that to substitute into another question's text.

**Comment by yoon** [comment]
Should they be in the DOM and hidden via css, or simply excluded from the DOM?

**Comment by seanvolution** [comment]
While #264 provides a way to do content substitution, there are situations in which we need to trigger dependent questions based on information that is pre-initialized in the response set. Hidden fields seem like the only way to handle this.

> Should they be in the DOM and hidden via css, or simply excluded from the DOM?

They would never need to be visible to the user, but they would need to be able to trigger dependencies. According to @kumbafu, this does not require that they be present in the DOM.
