### ISSUE TITLE
Rails_Root issue

### ISSUE THREAD

**Issue by jdkealy** [NUARIG/surveyor#199]
What should i do about this? 
I am running rails 3.1, just ran the installer and getting an issue running the rake task

/surverytest$ rake surveyor FILE=surveys/kitchen_sink_survey.rb
rake aborted!
uninitialized constant RAILS_ROOT

**Comment by yoon** [comment]
Temporarily, you could add RAILS_ROOT=/path/to/your/app to the rake command. In the long term, we'll need to change over to the Rails.root syntax.

**Comment by jparekh** [comment]
Or put RAILS_ROOT = Rails.root in your environment.rb file.

**Comment by yoon** [comment]
Closed by: 0ce52685339527c5e7e7d1ddcc3a66fa8211a915
