### ISSUE TITLE
Provide a way to add styles to a single word in a question

### ISSUE THREAD

**Issue by jdzak** [NUARIG/surveyor#201]
Currently we have the custom_css attribute to style text whole questions, but not a way to add styles to individual words in a question. Some ways people have worked around this is to embed html in the survey, but this doesn't work with surveor iOS.

We need a way to provide styling for single words in a question that will work with surveyor iOS. We need to be able to bold, underline, and italicize text.

**Comment by yoon** [comment]
Consolidated into #413
