### ISSUE TITLE
Need some flag to know if other survey was answered before

### ISSUE THREAD

**Issue by Nataliya** [NUARIG/surveyor#202]
PROGRAMMER INSTRUCTION: 
• IF A PRE-PREGNANCY QUESTIONNAIRE WAS COMPLETED DISPLAY BRACKETEDTEXT: 
{The next questions may be similar to those asked the last time we spoke, but we are asking them again because 
sometimes the answers change.}Now, I'd like to ask some questions about your schooling and employment.

**Comment by jdzak** [comment]
I'm closing this ticket because this functionality will be available once the prepopulation (#196) and hidden field(#197) functionality is added to surveyor.
