### ISSUE TITLE
Need information from a different questionnaire 

### ISSUE THREAD

**Issue by Nataliya** [NUARIG/surveyor#203]
INS_QUE_PrePreg_SAQ_EHPBHI_P2_V1.1 asks to skip the question if the maristat was answered a certain way. The maristat comes from the separate questionnaire. It also depends on they type of questionnaire - if it's CASI.

PROGRAMMER INSTRUCTION:  
• IF ADMINISTERED AS A CASI, SKIP OPIN_SPOUSE IF MARISTAT = 3, 4, 5, 6, -1 or -2

_PrePreg_SAQ_

**Comment by jdzak** [comment]
I'm closing this ticket because this functionality will be available once the prepopulation (#196) and hidden field(#197) functionality is added to surveyor.
