### ISSUE TITLE
Error while running "rake -f init_testbed.rakefile" in rails3 branch

### ISSUE THREAD

**Issue by bnadav** [NUARIG/surveyor#205]
While running the migrations:

==  AddDisplayTypeToAnswers: migrating ========================================
-- add_column(:answers, :display_type, :string)
   -> 0.0013s
rake aborted!
no such file to load -- systemu

Turns out that "systemu" is required by "macaddr"  which is required by  "uuid"  which is required
in the first line of surveyor/lib/surveyor/models/answer_methods.rb.

The macaddr.gemspec file does not specify 'systemu' as a dependency and so it does not get installed. 
There is an open issue about this (https://github.com/ahoward/macaddr/pull/5).

Until this is fixed, I guess the simplest way to avoid the error message would be to add to testbed/Gemfile, the line:
gem 'systemu'

**Comment by yoon** [comment]
should be fixed with the new `rake testbed`

b19ed3bc4e0faa3a67d1049046b69fd2f3d35189
6f43b4bf7f3720a4b3b666f137e60b6883fd4680
