### ISSUE TITLE
cucmber scenarios fail on rails3 branch

### ISSUE THREAD

**Issue by bnadav** [NUARIG/surveyor#206]
Hi all,
Am I doing something wrong, or is there some work to be done... 

After initiating the testbed - all specs run ok. 
However rake:cucumber results in 8 failures.

Also I couldn't run cucumber at all before altering lines 8 and 12 in features/support/env.rb to:
    require 'cucumber/rails/application'
    require 'cucumber/rails/action_controller'

Should I work on it, or am I missing something ?

Cheers

Nadav

**Comment by yoon** [comment]
Should be fixed in surveyor 0.21.0:

3eecd13d84c671f97a3de60441893ebb9af30ad6
f89a9f97090452ddef832bc5df2344eb3f4fd2bf
