### ISSUE TITLE
Support the data format along with description.

### ISSUE THREAD

**Issue by Nataliya** [NUARIG/surveyor#210]
Would be helpful, if surveyor has an ability to support data format, along with description, like it does for the string-type. 

Example :

 a "Date", :date
 a "Number", :integer

<pre>
    q_HOSP_NIGHTS "How many nights did you stay in the hospital during this hospital stay?",
     :help_text => "Confirm response",
     :pick=>:one, 
     :data_export_identifier=>"PREG_VISIT_2_2.HOSP_NIGHTS"
     a "Number", :integer
     a_neg_1 "Refused"
     a_neg_2 "Don't know"
</pre>

**Comment by yoon** [comment]
This is currently supported by surveyor for types :string, :text, :float, :integer, :date, :datetime, and :time
