### ISSUE TITLE
Dependencies inside of the "inline" question group are not hidden 

### ISSUE THREAD

**Issue by ybushmanova** [NUARIG/surveyor#216]
Dependencies inside of the question group are not hidden on page load when  :display_type => :inline  is set for the group

<pre>
survey "Test survey" do
  section "People" do
    group "Someone", :display_type => :inline do
      q_someone_deseased "Deseased", :pick => :one, :data_export_identifier => "someone_deseased"
      a_1 "Yes"
      a_2 "No"
      
      q_someone_age_at_death "Age at Death", :data_export_identifier => "someone_age_at_death"
      dependency :rule => "A"
      condition_A :q_someone_deseased, "==", :a_1
      a :integer, :custom_class => "short"
      
      q "Cause of Death", :data_export_identifier => "death_cause"
      dependency :rule => "A"
      condition_A :q_someone_deseased, "==", :a_1
      a :string
      
      q_someone_age "Age", :data_export_identifier => "someone_age"
      dependency :rule => "A"
      condition_A :q_someone_deseased, "==", :a_2
      a :integer, :custom_class => "short"
      
      q_someone_health_status "Health Status", :data_export_identifier => "someone_health_status"
      dependency :rule => "A"
      condition_A :q_someone_deseased, "==", :a_2
      a :string      
    end    
  end
end
</pre>

**Comment by yoon** [comment]
Closed by 30b9fcc2497df7e08968a015ea2d693da6bc3233
