### ISSUE TITLE
Inline display for radio buttond does not work for question group

### ISSUE THREAD

**Issue by ybushmanova** [NUARIG/surveyor#217]
<pre>
survey "Test survey" do
  section "People" do
    group "Someone", :display_type => :inline do
      q_someone_deseased "Deseased", :pick => :one, :display_type => :inline, :data_export_identifier => "someone_deseased"
      a_1 "Yes"
      a_2 "No"

      q_someone_alive "Alive", :pick => :one, :data_export_identifier => "someone_alive"
      a_1 "Yes"
      a_2 "No"
    end    
  end
end
</pre>

**Comment by yoon** [comment]
Closed by 8e173d0dce3af174c8e5d2e1156eae48fbf13d05
