### ISSUE TITLE
Impatient users can cause havoc in Surveyor.

### ISSUE THREAD

**Issue by mgurley** [NUARIG/surveyor#218]
Using Rails 0.20.0, Rails 3 branch.

The model of saving of responses as they are answered is really cool but if a user is inpatient and does not wait for the ajax request to finish, allowing the calllback to update the id of a newly created response, then:
- if the user clicks the next section button, then a duplicate response can be created on the server
- if the user unchecks a checkbox, then the response is not removed on the server

The UI needs to be blocked while the ajax request is submitted, so the user cannot reak havoc.  Possible solution:  http://jquery.malsup.com/block/

**Comment by jovhenni19** [comment]
Try adding this code in `app\models\response_set.rb` and then replace `update_attributes` with `update_response_attributes` in `lib\surveyor\surveyor_controller_methods.rb` the update part

<pre>
def update_responses_attributes(params_attrs)
   # format attributes as array of hashes, for ActiveRecord
   responses_attrs = params_attrs.collect do |k, response_attrs|
     response = responses.detect {|r| r.answer_id.to_s == response_attrs['answer_id'] }
     if response
       response_attrs.merge(:id => response.id) if Response.find(response.id).present?
     else
       response_attrs
     end
   end
   update_attributes :responses_attributes => responses_attrs
 end
</pre>


source: Jonathan Linowes and David Were [surveyor-dev] Google Groups

**Comment by mgurley** [comment]
Closed by 673da85f658309aac3bb84e1486f76d440d54c06

And then further refined by c543ebf26831c13ae3ad22fd815c973107ef49b1
