### ISSUE TITLE
The textarea on dependency saves twice on the DB

### ISSUE THREAD

**Issue by jovhenni19** [NUARIG/surveyor#221]
There is a dual entry for the answer to my dependency question. It is a text type and I think it occurred when I entered a text in the textarea and then I quickly press the complete button. My guess the culprit would be the saving when the element is
blurred and then the saving on the complete button. Hehe

But then..
"The ajax call for the textarea isn't triggered until it loses focus,
so that would happen at the same time as the submit button. Could you
submit a github issue, and take a stab at a solution if you'd like to?"  -Mark A. Wimbiscus Yoon

**Comment by mgurley** [comment]
Are you using the latest Rails 3 branch?  I added some JavaScript  recently that should block the UI during the Ajax request that should prevent your issue from occurring.  Here is the commit: 673da85f658309aac3bb84e1486f76d440d54c06.

**Comment by jovhenni19** [comment]
I'm using Rails 2.3.8 and thanks for the commit. I've already seen before that "BlockUI" plugin, but I don't know how to use it with surveyor. Your work will serve as a jump start for me. I'm gonna study it later. Thank you very much!

**Comment by mgurley** [comment]
Duplicates #218.  Which has been closed.
