### ISSUE TITLE
Template is missing

### ISSUE THREAD

**Issue by ghost** [NUARIG/surveyor#222]
I'm using mac osx and ruby 1.8
Using rake (0.9.2) 
Using multi_json (1.0.3) 
Using activesupport (3.1.0) 
Using bcrypt-ruby (3.0.1) 
Using builder (3.0.0) 
Using i18n (0.6.0) 
Using activemodel (3.1.0) 
Using erubis (2.7.0) 
Using rack (1.3.4) 
Using rack-cache (1.0.3) 
Using rack-mount (0.8.3) 
Using rack-test (0.6.1) 
Using hike (1.2.1) 
Using tilt (1.3.3) 
Using sprockets (2.0.2) 
Using actionpack (3.1.0) 
Using mime-types (1.16) 
Using polyglot (0.3.2) 
Using treetop (1.4.10) 
Using mail (2.3.0) 
Using actionmailer (3.1.0) 
Using arel (2.2.1) 
Using tzinfo (0.3.30) 
Using activerecord (3.1.0) 
Using activeresource (3.1.0) 
Using bundler (1.0.18) 
Using coffee-script-source (1.1.2) 
Using execjs (1.2.9) 
Using coffee-script (2.2.0) 
Using rack-ssl (1.3.2) 
Using json (1.6.1) 
Using rdoc (3.10) 
Using thor (0.14.6) 
Using railties (3.1.0) 
Using coffee-rails (3.1.1) 
Using fastercsv (1.5.4) 
Using formtastic (1.2.4) 
Using haml (3.1.3) 
Using jquery-rails (1.0.14) 
Using systemu (2.2.0) 
Using macaddr (1.4.0) 
Using mysql2 (0.3.7) 
Using rails (3.1.0) 
Using sass (3.1.10) 
Using sass-rails (3.1.4) 
Using uuid (2.3.4) 
Using surveyor (0.20.0) from https://github.com/NUBIC/surveyor.git (at rails3) 
Using uglifier (1.0.3) 

I've just try to see if kitchen survey works after 
rails g surveyor:install 
rake surveyor FILE=surveys/kitchen_sink_survey.rb

when I try to look at http://localhost:3000/surveys/ 
I have this issue:
Template is missing
Missing template surveyor/new, application/new with {:formats=>[:html], :handlers=>[:erb, :builder, :coffee], :locale=>[:en, :en]}.

edit: I have update some gems but now I have just a page with:

"You may take these surveys"

with a point with no editing or selecting possibility

**Comment by mgurley** [comment]
This can be resolved by explicitly adding 'haml' to your Gemfile.  I also needed to lock my version of the formtastic gem to something less than version 2.0. Like so:

gem 'formtastic', '1.2.4'
gem 'haml'

**Comment by ghost** [comment]
As you could see :
source 'http://rubygems.org'

gem 'rails'

gem 'mysql2'

gem 'rspec'
gem 'rspec-rails'

gem 'cucumber'
gem 'cucumber-rails'
gem 'database_cleaner'
gem 'factory_girl'
gem 'launchy'

gem 'capybara'

gem 'formtastic', '1.2.4'
gem 'surveyor', :git => 'git://github.com/NUBIC/surveyor.git', :branch => 'rails3'

gem 'haml'
gem 'fastercsv'

my version of formtatisc is 1.2.4

**Comment by mgurley** [comment]
Ok, I don't know what is different for you but I just had a colleague here do the following:
- Create a Rails 3.1.1 app
- Set the Gemfile to the following

```
source 'http://rubygems.org'

gem 'rails', '3.1.1'
gem 'surveyor', :git => 'git://github.com/mgurley/surveyor.git', :branch => 'rails3'

gem 'sqlite3'
gem 'formtastic', '1.2.4'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
```
- Ran bundle install
- Ran rails g surveyor:install
- Ran rake db:migrate
- Ran rake surveyor FILE=surveys/kitchen_sink_survey.rb
- Ran rails s
- Navigated to http://localhose:3000/surveys

He got  the 'Template is missing' error

Then he added 'haml' to his Gemfile:

```
source 'http://rubygems.org'

gem 'rails', '3.1.1'
gem 'surveyor', :git => 'git://github.com/mgurley/surveyor.git', :branch => 'rails3'

gem 'sqlite3'
gem 'formtastic', '1.2.4'
gem 'haml'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
```
- Ran bundle update
- Ran rails s
- Navigated to http://localhose:3000/surveys

No more  'Template is missing' error.  He had other problems but those will be addressed as separate issues.
Could you try to reproduce the above?

**Comment by ghost** [comment]
I have no more 'Template is missing error'.
Thank you
