### ISSUE TITLE
Implement a more elegant UI blocking solution to prevent duplicate responses.

### ISSUE THREAD

**Issue by mgurley** [NUARIG/surveyor#225]
For issue #218, a strategy of blocking the entire UI during each AJAX request was implemented with commit 673da85f658309aac3bb84e1486f76d440d54c06.   While this change helps improve data integrity, it is rather annoying and heavy-handed.  Implement a more elegant UI blocking solution that during each AJAX request:
- blocks the UI of only the question being answered
- prevents the entire survey form being submitted via a traditional HTTP post.

**Comment by yoon** [comment]
See #272
