### ISSUE TITLE
Make the Rails 3 branch master and make master a rails 2.3 branch.

### ISSUE THREAD

**Issue by mgurley** [NUARIG/surveyor#226]
Rails 3 is the future of Rails development.  Make the Rails 3 branch the master branch.  Make the master branch a Rails 2.3 branch.  Drop support for Rails 2.3 and tell people to fork the Rails 2.3 branch if they want to make changes.  Concomitantly, get the CI build to work on the new master (Rails 3 branch) and  update the Readme file with Rails 3 syntax.

**Comment by yoon** [comment]
closed by b5499addcd083e4e88bc1049f96fe5fe5954f24b
