### ISSUE TITLE
Add support for formtastic 2.0.

### ISSUE THREAD

**Issue by mgurley** [NUARIG/surveyor#227]
A new version of the formtastic gem was released--version 2.0.  Surveyor does not work with formtastc 2.0.  Sorry for the lack of detail but whoever works on this issue will quickly see what's wrong by trying to use surveyor with formtastic 2.0.  Currently, you need to lock your application  to version of formtastic < 2.0 like so:

gem 'formtastic', '1.2.4'

**Comment by rsutphin** [comment]
For a short-term solution, it would probably be a good idea to release a version of the gem with a tighter formtastic dependency; e.g., '~> 1.0'.

**Comment by mgurley** [comment]
A little more detail:

When you run the generator to install surveyor

```
rails g surveyor:install

```

you will get the following error:

```
uninitialized constant Formtastic::SemanticFormHelper (NameError)
```

**Comment by rsutphin** [comment]
Commit 8dd011e4 tightens the formtastic dependency in the gemspec.

**Comment by AlexHamilton** [comment]
I asked for help on the formtastic google group for help with migrating to formtastic 2 and was asked for pointers on what the modifications to the formtastic inputs in Surveyor were intended to do.  I don't have the background in Surveyor to answer, but if someone could add some pointers there, that would be helpful.  Thanks.
https://groups.google.com/forum/?fromgroups#!topic/formtastic/a7tpKvKXjAs)

**Comment by aaronmase** [comment]
+1
