### ISSUE TITLE
Ensure Rails 3.1.1 compatibility

### ISSUE THREAD

**Issue by pfriedman** [NUARIG/surveyor#228]
surveyor/new.html.haml line 13 is this:
- form_tag(take_survey_path(:survey_code => survey.access_code)) do 

it needs to be changed to the following for Rails3.1 +

= form_tag(take_survey_path(:survey_code => survey.access_code)) do 

Note the equals operator instead of the dash.

The dash format is deprecated in 3.1.0 and removed in 3.1.1 (which has just been released)

**Comment by yoon** [comment]
https://github.com/johnson-secondbureau/surveyor/commits/rails3.1

**Comment by rsutphin** [comment]
> https://github.com/johnson-secondbureau/surveyor/commits/rails3.1

This fork makes some pretty radical changes (e.g., it changes the routes) and some changes that are not compatible with Rails 3.0, so I'm not going to merge it as is. Instead, I'm going to go through the specs and features and fix the ones that fail with Rails 3.1.1, hopefully in a way that they will continue to work on Rails 3.0.
