### ISSUE TITLE
Slider not showing in Rails 3 branch

### ISSUE THREAD

**Issue by cheeyeo** [NUARIG/surveyor#230]
Hi

I installed and integrated the Rails 3 branch into a Rails 3 app

And the sliders do not show up both for text and numeric range values.

The browser tested is FireFox 

Can anyone please advise whether this issue is still open ?

thanks

**Comment by diasks2** [comment]
I am also experiencing this issue.  A select box is shown instead of a slider on questions #10 and #11 of the kitchen sink survey.  However, in questions #7, #8 and #9 the jquery-ui elements seem to be working fine (datepicker / slider).

**Comment by yoon** [comment]
This issue is still open. We once had a javascript slider that was based on dropdowns, but this hasn't been replaced since we moved to formtastic.
