### ISSUE TITLE
Do not create dependencies on edit if javascript is enabled

### ISSUE THREAD

**Issue by pfriedman** [NUARIG/surveyor#232]
Partially closes https://github.com/NUBIC/surveyor/issues/223

In jquery.surveyor.js, it says the following:

  // If javascript works, we don't need to show dependents from previous sections at the top of the page.
  jQuery("#dependents").remove();

The suggested change is to not create the dependents section at all if it is determined that javascript is enabled.

**Comment by yoon** [comment]
see 124c7432a6e128e05ef61a90210b2347384f3f09
