### ISSUE TITLE
It's possible to enter the value without selecting a radiobutton

### ISSUE THREAD

**Issue by Nataliya** [NUARIG/surveyor#234]
It's possible to enter the value without selecting a radiobutton. I think the correct functionality would be to trigger the radio button be selected if the value is entered in the text field. 

See the code below: In this example, if radio button not selected, dependent repeater never shows up. 

<pre>
    q_CIG_NOW_NUM "On days that you smoke, how many cigarettes do you smoke per day? If you smoke 1 cigarette or 
    less each day, please enter \"1.\"",
    :pick => :one
    a_number "NUMBER PER DAY", :integer
    a_neg_1 "REFUSED"
    a_neg_2 "DON’T KNOW"
    
    repeater "Tell us about the cars you own" do
      dependency :rule => "A"
      condition_A :q_CIG_NOW_NUM, ">", {:integer_value => "60"}
      
      q "Make", :pick => :one, :display_type => :dropdown
      a "Toyota"
      a "Ford"
      a "GMChevy"
      a "Ferrari"
      a "Tesla"
      a "Honda"
      a "Other weak brand"
    end
</pre>

**Comment by yoon** [comment]
Closed by 6bc503e
