### ISSUE TITLE
Dependencies withing the dependent repeater/group don't work

### ISSUE THREAD

**Issue by Nataliya** [NUARIG/surveyor#235]
Dependencies withing the dependent repeater/group don't work. The hidden tag is on the fieldset element, but the css doesn't display the element accordingly. 

See the code below: "Year"- question shows up regardless, once the repeater is visible. 

<pre>
    q_CIG_NOW_NUM "On days that you smoke, how many cigarettes do you smoke per day? If you smoke 1 cigarette or 
    less each day, please enter \"1.\"",
    :pick => :one
    a_number "NUMBER PER DAY", :integer
    a_neg_1 "REFUSED"
    a_neg_2 "DON’T KNOW"
    
    repeater "Tell us about the cars you own" do
      dependency :rule => "A"
      condition_A :q_CIG_NOW_NUM, ">", {:integer_value => "60"}
      
      q "Make", :pick => :one, :display_type => :dropdown
      a "Toyota"
      a "Ford"
      a "GMChevy"
      a "Ferrari"
      a "Tesla"
      a "Honda"
      a "Other weak brand"
      
      q_model "Model", 
      :pick => :one
      a_1 "Small"
      a_2 "Medium"
      a_3 "Large"
      
      q "Year"
      dependency :rule => "A"
      condition_A :q_model, "==", :a_2
      a :string
    end

</pre>

**Comment by yoon** [comment]
Duplicated by #366. Closing this one because the comments on the other are useful.
