### ISSUE TITLE
Content of surveys is not displaying

### ISSUE THREAD

**Issue by monfresh** [NUARIG/surveyor#244]
Hi. I created a new rails 3.1.1 app and added all the required gems to the Gemfile (see my Gemfile below), then did:
bundle install
rails g surveyor:install
rake db:migrate
rake surveyor FILE=surveys/quiz.rb
rails s

When I first went to http://localhost:3000/surveys,  I got an unstyled white page with "You may take these surveys" and a period below it. Looking at the server log, I saw several 404s, so I moved all the javascripts, stylesheets and images to the assets folder. I then stopped and restarted the server and refreshed the surveys page, but I'm still not getting any content. I just see "You may take these surveys" inside a yellow box.

What am I doing wrong?

Gemfile:
source 'http://rubygems.org'

gem 'rails', '3.1.1'
# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

gem 'surveyor', :git => 'git://github.com/NUBIC/surveyor.git', :branch => 'rails3'
gem 'haml'
gem 'formtastic', '1.2.4'
gem 'fastercsv'
# Gems used only for assets and not required
# in production environments by default.

group :assets do
  gem 'sass-rails', "  ~> 3.1.4"
  gem 'coffee-rails', "~> 3.1.1"
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
# Use unicorn as the web server
# gem 'unicorn'
# Deploy with Capistrano
# gem 'capistrano'
# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end

**Comment by rsutphin** [comment]
Did you do this recently? I ask because there is no longer a rails3 branch in surveyor — master now supports Rails 3. There were also problems with Rails 3.1.1 along the lines that you describe, but we thought they were all fixed under the auspices of issue #228. Can you do a `bundle update` and verify that you still have these problems?

**Comment by monfresh** [comment]
I just realized that I should probably be using the master branch, and when I updated the Gemfile to point to the master branch, it fixed my issue. While doing some google searches earlier for some formtastic issues I was having initially, I came across the instructions to point to the rails3 branch and didn't think twice about it. Sorry for the confusion.
