### ISSUE TITLE
Caching causes blank fields displayed 

### ISSUE THREAD

**Issue by ybushmanova** [NUARIG/surveyor#250]
config.action_controller.perform_caching = true makes form being displayed as empty even after it was filled an submitted. Survey data is being successfully stored but not retrieved.
Also getting the error: ActiveRecord::RecordNotFound (Couldn't find Response with ID=<id> for ResponseSet with ID=<id>) when trying to get to a different section.

**Comment by yoon** [comment]
see 6b439e63fc21a1f2501134036c2d97868aeb6fc4
