### ISSUE TITLE
Missing correct edit/show actions

### ISSUE THREAD

**Issue by bodonius** [NUARIG/surveyor#254]
Is there a best of practice for a CRU(D) roundtrip? 

If I wanted to show or edit a survey I get in trouble to gain access or got some error regarding undefined local variables (see below for showing a survey with access_code GD6CZbHMwX inside the generated show method). (I do not mean here the results controller but only methods in surveyor controller.)

http://localhost:3000/surveys/show/GD6CZbHMwX results in

undefined local variable or method `g' for #<#Class:0x007fed22ad9f78: 0x007fed22ad7bb0>

**Comment by yoon** [comment]
surveys/show/xyz... routes to surveyor#show with access_code "show" for response code "xyz", probably not what you were intending. see config/routes.rb or rake routes

**Comment by archonic** [comment]
Accessing `/surveys/name-of-survey/Mm9_lm4m3A/take` says `Processing by SurveyorController#edit as HTML`. That should be using the show action, shouldn't it?
