### ISSUE TITLE
Duplicate responses

### ISSUE THREAD

**Issue by bodonius** [NUARIG/surveyor#255]
For large surveys with hundreds of lines sometimes especially inside repeater groups form element responses are stored twice in the database. I'm aware of that this isn't an infamous bug https://github.com/NUBIC/surveyor/issues/225 but anyway... hopefully there is a solution somehow.

I really need duplication removing for an own export routine.

**Comment by yoon** [comment]
See #272. Also, repeaters will create responses with the same question_id, and answer_id, but a different response_group_id.
