### ISSUE TITLE
Survey#active_at and Survey#inactive_at incorrectly defaulted

### ISSUE THREAD

**Issue by rsutphin** [NUARIG/surveyor#258]
The attributes `active_at` and `inactive_at` on `Survey` are not initialized correctly. `active_at` should default to the creation time and `inactive_at` should start out null. Currently they do the reverse.

**Comment by yoon** [comment]
This behavior is correct according to the spec. See https://github.com/NUBIC/surveyor/blob/master/spec/models/survey_spec.rb#L72

This default prevents surveys from appearing automatically to users of your app before a developer has a chance to check them. If a different use case turns out to be the consensus, we should change the spec.

**Comment by rsutphin** [comment]
I see. I was confused because the names imply a range of time over which the survey may be taken. I.e., that a survey is active starting at some time and later becomes inactive. Under this interpretation, the defaults suggest that the survey was active from the indefinite past up to the instant at which it was created.

(The implementation of `#active_as_of?`, `#activate!`, and `#deactivate!` reflect this interpretation of the attributes, though now that I look at it closer, the way the setters are overridden does not.)

I agree that having a mechanism to allow surveys to be staged into a deployed application and then activated later makes sense. Since applications have to deliberately respect the active/inactive flags (i.e., it's an optional feature), perhaps a scheme like this would be less likely to cause confusion:
- Default both `active_at` and `inactive_at` to `nil`.
- Change the implementation of `#active_as_of`:

``` ruby
def active_as_of?(date)
  active_at && active_at < date && (!inactive_at || inactive_at > date)
end
```

This has the following benefits:
- Applications which don't use active/inactive have only null values in those columns in their survey table, so there's nothing to cause confusion. (This is what originally triggered me filing this issue.)
- Surveys start out inactive, then can be made active, then can be made inactive again, changing one value each time.
- No magic necessary in the `#active_at=` and `#inactive_at=` setters.

**Comment by yoon** [comment]
How would you interpret it if active_at > inactive_at?

**Comment by rsutphin** [comment]
Inactive. If an application wanted to reactivate something it had explicitly marked as inactive, it would need to set the inactive date to the future, or to nil. (It would be reasonable for `#activate!` to handle this situation, probably by setting inactive_at to nil if it is in the past.)
