### ISSUE TITLE
Continuing surveys

### ISSUE THREAD

**Issue by ericmeier** [NUARIG/surveyor#265]
Is there a way to continue a survey? It seems that it is only possible to create them from scratch. But for multipage surveys one needs more time to fill in and it should later be continued.

**Comment by rsutphin** [comment]
Please direct questions to the [mailing list](http://groups.google.com/group/surveyor-dev). 

The short answer to this question is "yes; use the edit action." If you need more detail, please ask on the list.

**Comment by jefflunt** [comment]
You can do this, but that function doesn't come out-of-the-box.

Surveys have ResponseSets, which is the collection of all responses by a
particular user to a Survey. That ReponseSet includes two fields:
`started_at` and `completed_at`. Essentially, if you manually clear out the
`completed_at` field for ResponseSets that are "started but not finished"
you should be able to pull this off. I think that in most cases the
`completed_at` field is used to know when a Survey was finished, the
intention being that after that date is set in the ResponseSet record, then
your application should no longer allow it to be edited.

On Mon, Dec 12, 2011 at 3:55 AM, ericmeier <
reply@reply.github.com
