### ISSUE TITLE
When javascript is enabled, don't submit the whole form

### ISSUE THREAD

**Issue by yoon** [NUARIG/surveyor#272]
Page loads submit buttons and (buttons that aren't submit buttons or links), with links hidden by default.  If javascript is enabled, then the submit buttons are removed from the DOM, and the links are shown.  For the last page, the finish button is its own form.  It is only shown when javascript is enabled.

**Comment by rsutphin** [comment]
I believe that #328 / #351 may obviate this. Can we close it?

**Comment by yoon** [comment]
I believe so.
