### ISSUE TITLE
Hide question from results if display order is 1. Why?

### ISSUE THREAD

**Issue by adonaldson** [NUARIG/surveyor#273]
Hi there,

I spotted this line in the results/show template:

https://github.com/NUBIC/surveyor/blob/master/app/views/results/show.html.erb#L6

Does a question with display_order 1 have some significance?

Thanks,

**Comment by yoon** [comment]
This whole controller is a bit out of date, and should probably be
removed. See #20

Mark A. Wimbiscus Yoon
Northwestern University Clinical and Translational Sciences Institute (NUCATS)
yoon@northwestern.edu
http://www.nucats.northwestern.edu

On Tue, Jan 31, 2012 at 12:54 PM, Andrew Donaldson
reply@reply.github.com
wrote:
