### ISSUE TITLE
Eliminate Response#response_set_id presence validation

### ISSUE THREAD

**Issue by hannahwhy** [NUARIG/surveyor#275]
The presence validation on `Response#response_set_id` introduced in 05034182be24f01b9960ecc19cbf9e452bc65e43 makes it impossible to write code like this under ActiveRecord 3.1:

``` ruby
rs = ResponseSet.new(:survey_id => survey_id)
rs.responses.build(...)
rs.save
```

because the ResponseSet will not have been saved at the time when Response's validations run.  (This pattern appears in some code being written for the National Children's Study.)

However, building a ResponseSet and its responses in this fashion can be done without violating referential integrity, which can be demonstrated by eliminating the validation under discussion, adding appropriate not-null and foreign key constraints on `Response#response_set_id` in a database that supports them (e.g. PostgreSQL), and executing the above code.  Therefore, I think that the presence validation is an unnecessary inhibition, and ask that it be eliminated or made optional.

**Comment by hannahwhy** [comment]
I have code in a personal fork that does this (see https://github.com/yipdw/surveyor/compare/master...relax-response-paranoia), and can convert this issue into a pull request if desired.

**Comment by yoon** [comment]
Sure, a pull request would be great. Could you include some tests that demonstrate the use case as documented above?

**Comment by hannahwhy** [comment]
> Sure, a pull request would be great. Could you include some tests that demonstrate the use case as documented above?

Sure thing; are you looking for additional tests beyond https://github.com/yipdw/surveyor/compare/master...relax-response-paranoia#L1R72 ?

**Comment by yoon** [comment]
That's enough to demonstrate the use case to me. I think it would be clearer if you didn't use a factory, though.

**Comment by hannahwhy** [comment]
Continuing this issue here:

https://github.com/NUBIC/surveyor/pull/276
