### ISSUE TITLE
make parser trace more readable to humans

### ISSUE THREAD

**Issue by yoon** [NUARIG/surveyor#278]
Make this output more useful:

<pre>
--- Parsing  /surveys/kitchen_sink_survey.rb  ---

survey survey_section question question_1 answer answer answer answer answer question_2 answer_1 answer_2 answer_3 answer_4 answer question_2a answer_1 dependency dependency_condition_A dependency_condition_B dependency_condition_C dependency_condition_D question_2b answer_1 dependency dependency_condition_Z question_montypython3 answer_1 question_montypython4 answer_1 dependency dependency_condition_A question_montypython5 answer_1 dependency dependency_condition_A question dependency dependency_condition_A question answer answer answer question answer validation validation_condition_A question answer validation validation_condition_A question answer question_time_lunch answer_1 question answer question answer answer answer answer answer answer answer answer answer answer question answer answer answer answer answer question answer question_group question answer question answer answer answer question answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer answer question answer answer answer answer answer answer question answer answer answer answer survey_section question_group answer answer answer question question question question_group answer answer answer answer answer question question question question_group answer answer answer answer answer question question question question question question question question question answer answer answer answer answer question answer answer answer answer question_car answer_y answer_n question_group dependency dependency_condition_A question answer answer answer answer answer answer answer question answer question answer question_group question answer answer 
found question:2 found answer:1 found question:2 found answer:2 found question:2 found answer:3 found question:2 found answer:4 found question:2 lost! answer: found question:montypython3 found answer:1 found question:montypython4 found answer:1 found question:montypython5 found answer:1 found question:car found answer:y saved. 
--- Done /surveys/kitchen_sink_survey.rb ---
</pre>

**Comment by jefflunt** [comment]
How about something like:

```
--- Parsing  /surveys/kitchen_sink_survey.rb  ---
Survey (name)
  section (name)
    question
      answer
    question
      answer
      answer
      answer
   section
     question
     answer
Parser has died...
--- Error ---
```

etc...

**Comment by rsutphin** [comment]
I agree with @normalocity's indentation suggestion for overall structure. I'd also dump name or abbreviated text for each node (not just for survey and section), reference identifier (where available), and line number. See [aker's deprecation module](https://github.com/NUBIC/aker/blob/master/lib/aker/deprecation.rb#L35-36) for an example of how to extract the line number from which a method was called.

I'd also suggest providing all that information (current node type, name if applicable, line number) when there's an unexpected exception in the parser, even if trace is off.
