### ISSUE TITLE
Running Specs on Ruby 1.8.7 with Rails 3.2

### ISSUE THREAD

**Issue by pfriedman** [NUARIG/surveyor#281]
There are two problems when running the testbed specs with Ruby 1.8.7 and Rails 3.2:

1) When creating the testbed application (bundle exec rake testbed) the rake task fails when attempting to run the 'bundle exec rake db:migrate db:test:prepare' line in he Rakefile (l. 64)
   The error is: uninitialized constant Rake::DSL

```
    stacktrace: 
Command failed with status (1): [bundle exec rake db:migrate db:test:prepar...]
.../gems/rake-0.8.7/lib/rake.rb:995:in `block in sh'
.../gems/rake-0.8.7/lib/rake.rb:1010:in `call'
.../gems/rake-0.8.7/lib/rake.rb:1010:in `sh'
.../gems/rake-0.8.7/lib/rake.rb:1094:in `sh'
./surveyor/Rakefile:64:in `block (4 levels) in <top (required)>'
```

The fix for this step (for now) is to cd into the testbed dir and manually call 'bundle exec rake db:migrate db:test:prepare'

2) Running the specs also fail. When running 'bundle exec rake spec', we get the following error:
  ./surveyor/testbed/config/initializers/session_store.rb:3: syntax error, unexpected ':', expecting $end (SyntaxError)
...sion_store :cookie_store, key: '_testbed_session' 

When correcting this by changing key: '_testbed_session'  to :key => '_testbed_session', you'll get:
  ./surveyor/testbed/config/initializers/wrap_parameters.rb:8: syntax error, unexpected ':', expecting kEND (SyntaxError)
  wrap_parameters format: [:json]

Then update this file by changing wrap_parameters format: [:json] to wrap_parameters :format => [:json]

Your specs will then pass.

**Comment by pfriedman** [comment]
Note that this is not a problem experienced when running the ./ci-exec.sh script. Setting CI_RUBY to ree-1.8.7 or ruby-1.9.2 and also setting RAILS_VERSION to 3.0 or 3.1 (or not setting it which then uses 3.2 by default) the tests all pass.

**Comment by rsutphin** [comment]
FWIW, I cannot reproduce this on REE-1.8.7-2011.03 or MRI 1.8.7-p358. Here's what I did:

```
[arranged for surveyor to use Rails 3.2.2 only to avoid #302]
$ bundle update
[...]
$ bundle show rails
/Users/rsutphin/.rvm/gems/ree-1.8.7-2011.03@surveyor/gems/rails-3.2.2
$ bundle exec rake testbed
[completes normally]
$ bundle exec rake spec
[no failures]
```

@pfriedman, can you verify that you see this problem with Rails 3.2.2?

**Comment by pfriedman** [comment]
The step that was failing for me when I created this issue was here during rake testbed

<pre>
cd -
cd testbed
</pre>


This seems to be working for me now (as it does for @rsutphin) so I am closing this issue.
