### ISSUE TITLE
Support images in questions and answers

### ISSUE THREAD

**Issue by jrhorn424** [NUARIG/surveyor#282]
Feature request. Related to #245.

I'm using "should" in the "wish-for" sense in what follows.

Subjects should be able to complete a question with images as "questions" and answers. Imagine a puzzle with a piece missing, and we want to test subject's cognitive abilities. Supporting images in both questions and answers allows us to show a puzzle with a piece missing, for example, and the subject  chooses the correct piece from a radio list. Ideally, the answers would still support text labels in addition to the images.

Less importantly, the images should be renderable in an arbitrary location with regard to their radio button and label: top, bottom, left, right.

**Comment by jrhorn424** [comment]
It just occurred to me to try passing a raw HTML image tag, but I haven't looked into the DSL to figure out if this is possible. Tips or hints are welcome...

**Comment by hoffmanc** [comment]
Is there no support for multimedia in surveys (e.g., images, video, etc.)?

**Comment by nicolamadio** [comment]
Is there a way to use images as answers on the radio list?

**Comment by nicolamadio** [comment]
answer "rails.png", :display_type =>"image" 
Works for me

**Comment by yoon** [comment]
Consolidated into #413
