### ISSUE TITLE
:help_text should recognize html tags

### ISSUE THREAD

**Issue by Nataliya** [NUARIG/surveyor#284]
:help_text used to recognize html tags but not any more

Example below:

```
:help_text => "<i>If yes, ask for an example and if this is typical behavior.</i>"
```

will be displayed on the page as;

```
<i>If yes, ask for an example and if this is typical behavior.</i>
```

Same with `<b>`,`<u>` and I assume others that were supported.

**Comment by rsutphin** [comment]
Do you know around when this behavior changed? It may be the result of using a more recent Rails version. In Rails 3 (I think) Rails started escaping all strings unless they are explicitly safed. This is a security measure, but it is probably reasonable for Surveyor to assume that DSL-provided strings are already safe.

**Comment by Nataliya** [comment]
The latest it used to work for is under rails 2.3.11

**Comment by yoon** [comment]
I don't think that HTML is the best choice for formatting in Surveyor, since we expect the same survey definition to work for surveyor and nu_surveyor. #285

**Comment by yoon** [comment]
Consolidated into #413
