### ISSUE TITLE
Default scope for Response is too broad

### ISSUE THREAD

**Issue by hannahwhy** [NUARIG/surveyor#290]
Commit 9b402ea4 introduced a `default_scope` on `Response`:

``` ruby
base.send :default_scope, :order => "created_at ASC"
```

(see https://github.com/NUBIC/surveyor/blob/9b402ea499edff2a73e8f6167671d2a3466aa948/lib/surveyor/models/response_methods.rb#L11)

This scope assumes that there will not be any other column named `created_at` in the result set; however, that is not true when eager-loading associated entities and predicating the query on attributes of those entities:

``` ruby
Response.includes(:response_set).where(:response_sets => { :user_id => an_id })
```

as ActiveRecord generates an outer join in that case.

I haven't been able to find a justification for this change in 9b402ea4; was this change made for testing reasons?  If so, can this default scope be removed and the affected tests modified to explicitly sort output?

**Comment by hannahwhy** [comment]
As a temporary workaround for NCS Core, I've eliminated the default:

``` ruby
class Response < ActiveRecord::Base
  include Surveyor::Models::ResponseMethods

  def self.default_scope; end
end
```

**Comment by yoon** [comment]
Partly for testing reasons, but mostly to have some reasonable default for the JSON representation of a response set. We have similar default scopes on other models. We should do something consistently across all of the models that have a sense of ordering.

**Comment by hannahwhy** [comment]
Why is a default necessary?

**Comment by yoon** [comment]
Is there a more narrow default scope that would make sense?

Ordering isn't strictly necessary, and it can be removed if it causes more problems that it fixes. It is good, though, to have some consistency in the array ordering of responses within the JSON representation. One possible order is by question.display_order, but that's a little more tedious in practice. The created date loosely reflects the order that the respondent responded to the survey.

**Comment by hannahwhy** [comment]
I think that the default ordering that makes the most sense is none at all; there doesn't seem to be any method on `Response` that assumes a particular order.  Users that require an order can impose their own.

**Comment by hannahwhy** [comment]
As another objection, Surveyor's current migrations do not index the timestamp columns.  Under PostgreSQL, this requires a separate sorting stage, which isn't a cost that applications should have to pay if they don't care about order:

https://gist.github.com/f3037a93013336b6fd17

Sorting on an indexed column permits the query analyzer to use a faster index scan, but then you pay a cost on record insert.
