### ISSUE TITLE
Implement ActiveSupport's #as_json/#to_json protocol

### ISSUE THREAD

**Issue by hannahwhy** [NUARIG/surveyor#291]
ActiveSupport 2.3.3 introduced the `#as_json`/`#to_json` protocol, which split the responsibility of generating a JSON representation from serializing that representation.  All versions of ActiveSupport since then have maintained that protocol.

I would like Surveyor's models to abide by this protocol, as it makes it easier to wrap existing JSON structures.  For example, to embed a `ResponseSet`'s JSON in a larger structure, I currently have to do something like this:

``` ruby
{ "response_set" => JSON.parse(response_set.to_json) }
```

because it is not currently the case that `response_set.as_json.to_json` and `response_set.to_json` generate equivalent objects.

**Comment by yoon** [comment]
See: https://github.com/nesquena/rabl/blob/master/lib/rabl/engine.rb#L32 and https://github.com/nesquena/rabl/blob/master/lib/rabl/engine.rb#L51

**Comment by hannahwhy** [comment]
I guess it's good to know that Rabl can technically satisfy this protocol, but there's still currently no way for users of Surveyor to access that intermediate representation save from writing Rabl dependencies into their own code.

Is it possible to eliminate `ResponseSet#to_json` and `Survey#to_json` and replace both with an `#as_json` that just invokes `Rabl::Engine#to_hash`?

**Comment by hannahwhy** [comment]
More here:

https://github.com/NUBIC/surveyor/pull/293
