### ISSUE TITLE
Work with, not against, eager loading

### ISSUE THREAD

**Issue by hannahwhy** [NUARIG/surveyor#292]
The 0.22.0 release of Surveyor spawns a _massive_ number of queries when serializing surveys and response sets to JSON.  Here's an ActiveRecord log, from NCS Core, of serializing eight surveys and eight response sets:

https://raw.github.com/gist/4a3567d61e0c68df8327/753310bc10341bfb6eddf812591503f2c0088ad9/gistfile1.txt

The error raised at the end of that log looks like a different Surveyor error; I'll investigate and report an issue on it if it turns out to be that.

Anyway, eager loading all entities for all surveys and response sets makes no difference in the number of issued queries when `ResponseSet#to_json` or `Survey#to_json` are called.  This shouldn't be the case: if the data needed to serialize Surveyor data to JSON is already in memory, there is no need to fetch it from the database again.

Unfortunately, I can't post the code samples that demonstrate this, because both belong to a still-private codebase.  I can, however, produce reduced test cases, if you'd like to see them.

**Comment by yoon** [comment]
May have to do with the object that is being handed to the rabl view:

<pre>
@survey = Survey.find_by_access_code(params[:survey_code])
</pre>


and 

<pre>
@response_set = ResponseSet.find_by_access_code(params[:response_set_code], :include => {:responses => [:question, :answer]})
</pre>


You are correct in noting that these actions haven't been optimized with eager loading yet.

**Comment by hannahwhy** [comment]
I'd prefer that eager loading be controlled by the user, not by Surveyor; Surveyor's JSON generation methods, IMO, should not invoke anything that will unconditionally result in a database access.  (That is: instead of using `where`, I'd prefer `#select`, and so forth.)

This can make code that interacts with Surveyor's JSON serialization a bit more verbose, but I think that's an acceptable cost for being able to keep database I/O under control.

All of this assumes that ActiveRecord has no way of knowing whether `#where` etc should hit the database, which I think is true.

**Comment by hannahwhy** [comment]
I'm bumping this issue because it will become a greater problem for NCS Navigator Cases, which will soon be serializing 4-5 additional surveys for each PBS fieldwork set.

**Comment by yoon** [comment]
Try:

```
h = {:sections => 
  {:questions => 
    [:answers, 
      {:question_group => [
        {:questions => [:answers, :dependency]}, 
        {:dependency => [:question, {:dependency_conditions => [:question, :answer]}]}
      ]},
      {:dependency => [:question, {:dependency_conditions => [:question, :answer]}]}
    ]
  }
}

Survey.includes(h).last.to_json
```
