### ISSUE TITLE
Distinguish deletions when updating responses in the controller

### ISSUE THREAD

**Issue by j-chen** [NUARIG/surveyor#30]
In response_set.rb: lines 57 and 109, in the "response_attributes=" and "response_group_attributes=" functions, updating the responses requires calling delete on all of the Response objects in a particular section, but it would be good to delete only responses that have been cleared by the user of the survey instead of deleting everything - this probably would require the program to know the response values beforehand.

**Comment by brian-lc** [comment]
I think at this point we're pretty set on the response clear and save pattern we have in the ResponseSet model. The decision to do it this way was based on how Rails forms work. While this may change in the future, for now we are going to hold off on implementing this change.
