### ISSUE TITLE
survey rake aborted! Can't mass-assign protected attributes: title, reference_identifier

### ISSUE THREAD

**Issue by diasks2** [NUARIG/surveyor#308]
I am trying to install the NUBIC surveyor gem in a Rails 3.2.3 app. I did the following steps:

1) Created a new Rails 3.2.3 project

```
 $ rails new surveyor
```

2) Added the surveyor gem

```
  gem "surveyor"
```

3) Ran

```
 bundle install
```

4) Generated the assets

```
 script/rails generate surveyor:install
```

5) Ran migrations

```
  bundle exec rake db:migrate
```

6) Then when I tried the "kitchen sink" survey

```
  rake surveyor FILE=surveys/kitchen_sink_survey.rb
```

I encountered the following error:

_survey rake aborted! Can't mass-assign protected attributes: title, reference_identifier_

**Comment by yoon** [comment]
See #302. This is also fixed in master
