### ISSUE TITLE
Missing asset

### ISSUE THREAD

**Issue by kbighorse** [NUARIG/surveyor#317]
Everything seems to be working fine, but getting this:

``` shell
ActionController::RoutingError (No route matches [GET] "/stylesheets/surveyor/ui-bg_highlight-soft_100_eeeeee_1x100.png"):
```

**Comment by kbighorse** [comment]
As I mentioned, most of the survey is working, which of course implies that I read the README and went through all the installation and setup steps and this is at least a possible bug.

`rake routes` won't show anything for a static asset like this stylesheet, if you'd glanced at the asset route I included. I am seeing this on my laptop running OS X Snow Leopard, but if I thought that could a factor, I'd have mentioned it.

What would be helpful is showing that that particular asset didn't get generated somehow:

``` shell
$ ls -lh public/stylesheets/surveyor
total 184
-rw-r--r--  1 kimball  staff   2.3K May  8 17:49 dateinput.css
-rw-r--r--  1 kimball  staff   331B May  8 17:49 jquery-ui-timepicker-addon.css
-rw-r--r--  1 kimball  staff    33K May  8 17:49 jquery-ui.custom.css
-rw-r--r--  1 kimball  staff   980B May  8 17:49 reset.css
-rw-r--r--  1 kimball  staff   4.8K May  8 17:49 results.css
-rw-r--r--  1 kimball  staff   104B May  8 17:49 ui-bg_glass_100_f6f6f6_1x400.png
-rw-r--r--  1 kimball  staff   125B May  8 17:49 ui-bg_glass_100_fdf5ce_1x400.png
-rw-r--r--  1 kimball  staff   105B May  8 17:49 ui-bg_glass_65_ffffff_1x400.png
-rw-r--r--  1 kimball  staff   3.7K May  8 17:49 ui-bg_gloss-wave_35_f6a828_500x100.png
-rw-r--r--  1 kimball  staff   129B May  8 17:49 ui-bg_highlight-soft_75_ffe45c_1x100.png
-rw-r--r--  1 kimball  staff   4.3K May  8 17:49 ui-icons_ef8c08_256x240.png
-rw-r--r--  1 kimball  staff   4.3K May  8 17:49 ui-icons_ffffff_256x240.png
```

I'm actually happy to contribute to this project, I think it's awesome.

**Comment by yoon** [comment]
yup, i believe that one's missing.

**Comment by gaurish** [comment]
i have sent pr #319 that adds that asset

**Comment by kbighorse** [comment]
Awesome, thanks!
