### ISSUE TITLE
Backend management?

### ISSUE THREAD

**Issue by kbighorse** [NUARIG/surveyor#318]
Is there any concept of viewing and managing results on the receiving end? Or is it designed to export to a spreadsheet?

**Comment by jefflunt** [comment]
The issue tracker isn't really intended to ask support/discussion/how-to questions. It's for reporting bugs, and the like. We do have a google mailing list where people help each other and discuss thing. You can email it at: surveyor-dev@googlegroups.com

We do welcome, and encourage people to ask for help on the mailing list. If you send your usage question there, it's more likely to get addressed.
