### ISSUE TITLE
Add encoding headers for generated files, including migrations

### ISSUE THREAD

**Issue by rsutphin** [NUARIG/surveyor#329]
Surveyor's generators add several files to a rails project. For maximum Ruby 1.9 compatibility, these files should declare their encodings.

**Comment by gaurish** [comment]
Since Surveyor is rails gem, isn't rails supposed to handle encoding on its own by specifying `config.encoding="utf-8"`?

**Comment by rsutphin** [comment]
> Since Surveyor is rails gem, isn't rails supposed to handle encoding on its own by specifying `config.encoding="utf-8"`?

AFAIK, `config.encoding` controls the default encoding for responses/requests in a Rails app. The encoding this issue is talking about is the [source file encoding](http://blog.grayproductions.net/articles/ruby_19s_three_default_encodings/) which is a separate thing and which is independent of Rails.

**Comment by yoon** [comment]
would you prefer ASCII or UTF-8? I don't believe there's any non-ascii characters in any of the generated files except for in config/locales

**Comment by rsutphin** [comment]
It doesn't matter. I'd be inclined to do UTF-8 because it's a sensible default, but since it is set per-file it can easily be changed if the needs of the file change.
