### ISSUE TITLE
Failing Scenario - Creating a date failed

### ISSUE THREAD

**Issue by gaurish** [NUARIG/surveyor#331]
**Failing Scenarios**:
cucumber features/surveyor.feature:456 #

``` ruby
  @javascript
  Scenario: Creating a date
    Given the survey
    """
      survey "When" do
        section "One" do
          q "Tell us when you want to meet"
          a "Give me a date", :date
        end
      end
    """
```

Any idea what broke this & what can we do to fix this? 

And on related note, would it be a good idea to use a [CI](http://travis-ci.org/) so changes that break the build are caught & reverted?

**Comment by yoon** [comment]
I've had random, intermittent failures locally with this scenario as well. They went away for a short time when I added the 1 second pause, but come back occasionally. I haven't looked into what causes it yet, but it seems to be to be an issue with the test, not surveyor itself.

**Comment by rsutphin** [comment]
I've also seen this feature fail rarely, intermittently. @gaurish, does it fail consistently for you? If so, can you give us some details about your environment (ruby, OS, etc.) so we can try to get it failing consistently here?

> And on related note, would it be a good idea to use a CI so changes that break the build are caught & reverted?

We do have a [multiaxis CI build for Surveyor](https://public-ci.nubic.northwestern.edu/job/Surveyor). It does not run the Selenium-based features yet, though (#333).

**Comment by gaurish** [comment]
I tested again & this time strangely ALL tests passed:

``` ruby
48 scenarios (48 passed)
398 steps (398 passed)
1m57.851s
```

So, I don't know what made it fail in first place & why does it pass now? Wierd! it seems the problem is random as you have noted

**Comment by rsutphin** [comment]
I'm hoping that d45d50e will prevent these intermittent failures. Time will tell.
