### ISSUE TITLE
Sliders failing - JS error

### ISSUE THREAD

**Issue by rbastian** [NUARIG/surveyor#334]
I'm getting a JS error when the sliders in the kitchen_sink survey are rendered - 

Uncaught TypeError: Object #<Object> has no method 'selectToUISlider'

I'm using rails 3.2.5
I'm using the edge of surveyor commit # 5dd6d1218e70
I've only installed surveyor, nothing else.

I'm not JS savvy so I may not have installed a dependency...

Thanks for any help.

rb

**Comment by rbastian** [comment]
btw - the above error occurs at line 95 in jquery.surveyor.js

**Comment by yoon** [comment]
you may need to include jquery.selectToUISlider in your js manifest file. this hasn't been added to the generator, so we will address that soon.

**Comment by rbastian** [comment]
Yoon - Thanks, that got the sliders to render.  However, the horizontal scale is being rendered vertically for each slider in the kitchen-sink example.  I'll keep poking at it.

rb

**Comment by rbastian** [comment]
OK, I added "*= require surveyor/ui.slider.extras" to the surveyor_all.css file and everything works.  

Thanks for your help!

rb
