### ISSUE TITLE
'gem install surveyor' not fetching Rails 3.2 attr_accessible fix

### ISSUE THREAD

**Issue by pdkn** [NUARIG/surveyor#335]
hi guys,

Awesome gem! I've got a Rails 3.2.3 app that requires the 'attr_accessible' fix https://github.com/NUBIC/surveyor/commit/1583c35f9f9401bb2c98ff474ada89943f6448bd#diff-0

At the mo 'gem install surveyor' doesn't seem to include this?  Although I can fix this for local development, I'm struggling on my Heroku cloud app. Any chance you can bump the version number up? 

Many Thanks

**Comment by rsutphin** [comment]
The fix for #302 is not in a released version yet, as you note. If you need the fix immediately, you should be able point your [Gemfile](http://gembundler.com/man/gemfile.5.html) at surveyor master.

**Comment by pdkn** [comment]
Aha, thanks rsutphin I'll give that a bash ;)
