### ISSUE TITLE
answer != condition returns false if question was never activated

### ISSUE THREAD

**Issue by stgallagher** [NUARIG/surveyor#337]
Some questions depend on previous questions not being answered in a particular way.  This dependency is noted as a condition like the following:

`condition_B :q_main_heat, "!=", :a_neg_5`

If the previous question that this dependency refers to was never asked, then the above statement will evalute as "false" even though the English translation of that statement, "Check and make sure Main Heat wasn't answered "neg 5" " would seem to be true in the case that it was never asked.

**Comment by pfriedman** [comment]
This change has unintended consequences. It looks like some dependencies are evaluating to true when the dependent question is never displayed.

This convoluted example survey shows the problem. I'm suggesting for now to revert this change because the scenario in which the "answer != condition returns false" is less likely than scenario below

``` ruby
survey "Test Dependency Groups survey" do

  section "Basic questions" do
    # A label is a question that accepts no answers
    label "These questions are examples of the basic supported input types"

    # A basic question with radio buttons
    question_1 "What is your favorite color?", :pick => :one
    answer "red"
    answer "blue"

    # A basic question with dependencies
    q_2 "Choose the colors you don't like", :pick => :any
    a_1 "red"
    a_2 "blue"
    dependency :rule => "A or B"
    condition_A :q_1, "==", :a_1
    condition_B :q_1, "==", :b_1

    # A dependent group, with conditions based on the previous 
    # question which also has a dependency.
    # These groups show even though the dependent question was never
    # asked or answered.
    group "Red" do
      dependency :rule => "A"
      condition_A :q_2, "!=", :a_1

      q_2a "Please explain why you don't like red?"
      a_1 "explanation", :text
    end

    group "Blue" do
      dependency :rule => "A"
      condition_A :q_2, "!=", :a_2

      q_2a "Please explain why you don't like blue?"
      a_1 "explanation", :text
    end

  end
end
```

**Comment by rsutphin** [comment]
Perhaps I don't understand something about dependencies, but I'm not clear what `:b_1` in condition B of question 2 is referring to. 

There are also two questions here with reference ID `2a`. I don't think that reference IDs are scoped to group, so that might explain the problem.

**Comment by pfriedman** [comment]
I've corrected the example survey and placed it here: https://gist.github.com/3054793. The problem where the group sections should not show but do anyway still exists with this survey.

**Comment by yoon** [comment]
@pfriedman, @rsutphin, I was going to add an example to the kitchen sink survey, but basically this change requires that any time you have a dependency condition with "!=" that you would like to remain hidden until there is an answer, you have to also have a "count>0" condition as well.

**Comment by rsutphin** [comment]
This change broke the build, so it's been reverted from master for now. There is a branch that reflects the changes that @yoon has done so far: `337-condition_not_equal`.
