### ISSUE TITLE
Custom Classes and Values

### ISSUE THREAD

**Issue by mjthompsgb** [NUARIG/surveyor#338]
Is it possible to designate custom classes for form fields such as "required"? I want to be able to use jQuery to only allow submission of a form if it is so much percent complete.

I am also wondering if it is possible to add a custom value or something to a specific answer to be able to figure out a price on the fly based on the values of certain answers?

Thanks in advance.

Matt

**Comment by jefflunt** [comment]
Yes. I'm using an older version of surveyor on a project, so I'm not sure
if this sample code will 100% work on the latest build.

For example:

```
q "Backup contact person (name and phone number)", :is_mandatory => true
```

...would make the question mandatory (survey can't be finished until this
question is answered).

We also use things like:

```
a :date, :custom_class => "date"
```

...which appears to add custom classes to the output html), which you could use to hook on your jQuery. The class name chosen in this example is arbitrary - it can be whatever you want it to be.

I'm not sure if you need to modify the way the form is rendered in order for the class to
be added, or if it does this out of the box.

Whatever the solution is for your project, play around with these options
and look at how surveyor renders the output form. You can essentially add
any options you like, modify the renderer to do something special for those
options, and thereby control the html that is output for your project in
any way you wish.

**Comment by mjthompsgb** [comment]
Thanks for getting back to me so quickly.

I tried what you suggested and neither seems to work for me. For the is_mandatory thing I know in the question table there is an is_mandatory column and for all questions its set to true with or without the is_mandatory option in the DSL. And even with that it will still let me submit the form.

As for the custom_class it doesn't seem to work either. I have tried a bunch of things to get custom attributes on answers with no luck. I will keep messing around and hopefully get it figured out.

One more thing. Do you know of any way to speed up Surveyor? When I click on a survey it seems to take forever to load. I added some indexes to the tables but I don't notice any speed difference. Any ideas?

Thanks again.

Matt

**Comment by jefflunt** [comment]
I'm sorry, the option for `is_mandatory` is only used for the false case =>
":is_mandatory => false"

That was just a complete mistake on my part. You're right that the default
is "true" already.

On Wed, Jun 20, 2012 at 4:09 PM, Matt <
reply@reply.github.com

**Comment by jefflunt** [comment]
These usability questions are best for the mailing list: surveyor-dev@googlegroups.com

Speed is a complex topic, and it depends heavily on the structure of your survey, for one thing. Speed is a better topic for the mailing list as well (as with any discussion topics, unless you're reporting a bug or requesting a feature).

The short version of the answer is that dependencies between questions are calculated on the fly, and the more dependencies (and the more complex those dependencies) the longer it takes to render a page. Reduce the number and complexity of dependencies and you might see speed increases.

However, that's just a stab in the dark. If you want to tell the mailing list more about your specific case, and what about it is slow (as well as what you think should be faster) you're likely to get a more specific answer.

**Comment by mjthompsgb** [comment]
Thats okay. 

Even when they are all set to true it still lets me submit the form so something must be messed up. I did get the custom_class to work so I will probably just end up using jQuery and some custom_class hooks because I want to display a percent meter for completion of required fields.

Now I just need to figure out how to speed Surveyor up. I know it makes a lot of calls to the database for everything it does and that is why it is slow but the indexes I added didn't seem to make any difference.

Any ideas on that?

Thanks
Matt

**Comment by mjthompsgb** [comment]
Sorry didn't see you answered before I sent my post. I will move over to the mailing list and see if I can get some help there. Thanks for the help already though.

Thanks
Matt

**Comment by jefflunt** [comment]
I don't believe the mandatory flag is intended to prevent form submission - it's intended to be a signal to know whether or not the minimum information in a survey has been provided in order for it to be considered "done".

The form still submits, yes, and it will should, so the responses that have been provided are written to the database. This enables things like allowing surveys to be saved "as-is" and finished at a later time.

**Comment by yoon** [comment]
Since I don't see this on the google group yet, I'll comment here - the mandatory fields don't prevent submission in the UI by default. But there are methods such as ResponseSet#mandatory_questions_complete? that allow you to do some checking in a custom surveyor controller. A percent meter is difficult because of dependencies.

Surveyor can be slow for a host of reasons, but the best place to start is the log, checking if the issue is db time, rendering time, or something else. Next I'd check the client side with something like Firebug's network panel.
