### ISSUE TITLE
Add :pick => :one + time/date/datetime examples to kitchen sink & integrated tests

### ISSUE THREAD

**Issue by rsutphin** [NUARIG/surveyor#340]
The next release of surveyor will support having a `:pick => :one` question with `:date`, `:time`, or `:datetime` answers. (Previous versions only allowed `:string` or `:answer` answers.) We should add examples of these to the kitchen sink survey and the integrated test suite.

**Comment by yoon** [comment]
Already in integrated tests at: https://github.com/NUBIC/surveyor/blob/master/features/surveyor.feature#L591
