### ISSUE TITLE
Verify internal references after parsing survey

### ISSUE THREAD

**Issue by rsutphin** [NUARIG/surveyor#341]
After a survey is loaded, Surveyor should verify all author-provided internal references to make sure they point to valid structures and are not duplicated. This would include internal pointers such as:
- The reference from a dependency condition to a question
- The reference from a dependency condition to an answer

And potential duplications such as:
- Question reference IDs (across the survey)
- Answer reference IDs (within a question)

(There may be others also.)

**Comment by rsutphin** [comment]
This problem was noticed in a [specific survey](https://code.bioinformatics.northwestern.edu/issues/issues/show/2254) for NCS Navigator and while developing the example code @pfriedman posted on #337.

**Comment by yoon** [comment]
Reference lookups happen in the parser already (https://github.com/NUBIC/surveyor/blob/master/lib/surveyor/parser.rb#L218), but it could certainly be more robust.

We don't look for uniqueness of reference identifiers, but we could add that constraint. It may break old surveys that don't use them in a way that demands uniqueness.

**Comment by rsutphin** [comment]
> Reference lookups happen in the parser already (https://github.com/NUBIC/surveyor/blob/master/lib/surveyor/parser.rb#L218), but it could certainly be more robust.

So it does check, but it doesn't fail the parse if the reference is bad. Since there's other code that assumes that all references are good, and I can't think of a reason to keep bad references around, I'd suggest that the parser ought to accumulate the bad references it encounters and throw an exception at the end of the process, listing all the bad references.

> We don't look for uniqueness of reference identifiers, but we could add that constraint. It may break old surveys that don't use them in a way that demands uniqueness.

Good point. Perhaps what we should do instead is verify referential uniqueness. I.e., if a dependency condition refers to a question by reference identifier, we should verify that there is only one question with that reference identifier at the end of the parse.

**Comment by jdzak** [comment]
Another reason to add this is that Survey#to_json throws an exception when a dependency with a bad question reference exists.
