### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by sweded** [NUARIG/surveyor#346]
I'm receiving the error `<module:Formtastic>': uninitialized constant Formtastic::SemanticFormBuilder (NameError)` when I attempt to run `rails g surveyor:install` and have specified the gem as `gem 'surveyor'`. However, when I specify the repo in my Gemfile, `gem 'surveyor', :git => 'git://github.com/NUBIC/surveyor.git'` the installer runs without issue. I've also attempted specifying version `0.22.0` and `0.20.0` with either failing as above.

I'm running ruby 1.9.3p194 and rails 3.2.6.

**Comment by rsutphin** [comment]
I'm sorry to hear you're having an issue. However, I can't reproduce this using the same versions of ruby and rails. I put the steps I'm attempting [in a gist](https://gist.github.com/3138789). Can you take a look to see how they differ from what you're doing?

Also: when you use `gem 'surveyor'`, what version of surveyor is installed? You could determine this by running `bundle show surveyor`.

**Comment by sweded** [comment]
Thanks for getting back quickly. Following the gist produced no errors for me. However, it's using Formtastic 1.2.4 where in my previous attempts I'm using version 2.1.1 per gleaning `s.add_dependency('formtastic', '~> 2.1.0')` from line 24 of the gemspec.

In my current working installation, the version is at surveyor-d45d50eadc0b.

**Comment by rsutphin** [comment]
The latest released version of Surveyor does not support Formtastic 2. `Formtastic::SemanticFormBuilder` is part of Formtastic 2 and is only referenced in the pre-release version of surveyor on master. I'm not sure how there could be references to it when you were just using `gem 'surveyor'` in your Gemfile. Perhaps leftovers from a previous time when you were sourcing the gem from git?

If you can reproduce this problem, can you give us the full stack trace of the error and the results of `bundle show surveyor` when you reproduce it? Otherwise, I'm not sure what else to try.

**Comment by sweded** [comment]
Previously I had `'formtastic', '~> 2.1.0'` in my Gemfile. I was confused because I saw that in the gemspec and thought I was good to go. Since my project uses Formtastic 2, I'll continue with edge for the time being but I will need to use a stable release in the future. Not to be pushy but how far out do you think the release that supports Formtastic 2 might be? Thanks again!

**Comment by rsutphin** [comment]
Ah, so if you had `'formtastic', '~> 2.1.0'`, in your Gemfile, bundler would have pushed you back to an older version of surveyor with a looser formtastic constraint. That might have caused the error you saw.

> Not to be pushy but how far out do you think the release that supports Formtastic 2 might be?

I believe we're planning to do a release once #328 is done. Probably in the next two weeks or so.

**Comment by daniambrosio** [comment]
Guys I know this is an old thread, but I am having this same problem. I am using rvm in a mac machine.

#gemfile 
gem "formtastic"
gem "surveyor"

bundle show surveyor
/Users/danielambrosio/.rvm/gems/ruby-1.9.3-p392@dadelet/gems/surveyor-0.20.0

bundle show formtastic
/Users/danielambrosio/.rvm/gems/ruby-1.9.3-p392@dadelet/gems/formtastic-2.2.1

The stacktrace is this:
rails g surveyor:install
/Users/danielambrosio/.rvm/gems/ruby-1.9.3-p392@dadelet/gems/surveyor-0.20.0/lib/formtastic/surveyor_builder.rb:3:in `<module:Formtastic>': uninitialized constant Formtastic::SemanticFormBuilder (NameError)
    from /Users/danielambrosio/.rvm/gems/ruby-1.9.3-p392@dadelet/gems/surveyor-0.20.0/lib/formtastic/surveyor_builder.rb:2:in`<top (required)>'
    from /Users/danielambrosio/.rvm/gems/ruby-1.9.3-p392@dadelet/gems/surveyor-0.20.0/lib/surveyor.rb:3:in `<top (required)>'
    from /Users/danielambrosio/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.3.4/lib/bundler/runtime.rb:72:in`require'
    from /Users/danielambrosio/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.3.4/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
    from /Users/danielambrosio/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.3.4/lib/bundler/runtime.rb:70:in`each'
    from /Users/danielambrosio/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.3.4/lib/bundler/runtime.rb:70:in `block in require'
    from /Users/danielambrosio/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.3.4/lib/bundler/runtime.rb:59:in`each'
    from /Users/danielambrosio/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.3.4/lib/bundler/runtime.rb:59:in `require'
    from /Users/danielambrosio/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.3.4/lib/bundler.rb:132:in`require'
    from /Users/danielambrosio/dev/projects/dadelet/config/application.rb:7:in `<top (required)>'
    from /Users/danielambrosio/.rvm/gems/ruby-1.9.3-p392@dadelet/gems/railties-3.1.0/lib/rails/commands.rb:21:in`require'
    from /Users/danielambrosio/.rvm/gems/ruby-1.9.3-p392@dadelet/gems/railties-3.1.0/lib/rails/commands.rb:21:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

The line 7 in application.rb is the bundler require below, however I see no relation with the problem
if defined?(Bundler)
  Bundler.require *Rails.groups(:assets => %w(development test))
end

**Comment by yoon** [comment]
You might want to try `bundle update surveyor`. The current version is 1.3.0 https://rubygems.org/gems/surveyor

**Comment by rsutphin** [comment]
Surveyor depends on 

``` ruby
s.add_dependency('formtastic', '~> 2.1.0')
```

If your Gemfile is this:

``` ruby
gem "formtastic"
gem "surveyor"
```

There are at least two very different things that bundler could pick:
- formtastic 2.1.x and a recent version of Surveyor
- formtastic 2.2.x and an old version of Surveyor which didn't have a version restriction on the formtastic dependency. (E.g., surveyor 0.20.0)

I think that bundler's choice is undefined in this case. For @daniambrosio, it's picking the latter. If you want it to pick a more recent version of Surveyor, you'll need to tell it that explicitly in the Gemfile:

``` ruby
gem 'formtastic'
gem 'surveyor', '~> 1.3'
```

**Comment by daniambrosio** [comment]
@rsutphin thanks a lot! This worked... Forcing the minimum version actually brought surveyor 1.3 into my environment.

@yoon - thanks for your reply, however updating was not working because of some gem dependency, bundle would not update it!

**Comment by nsantiago2719** [comment]
ok im facing the same problem @daniambrosio  but when i add the git source and bundle install it worked .. and i tried to run rake db:migrate but it fails ...  help pls.. 

== 20140709235544 AddDisplayTypeToAnswers: migrating ==========================
-- add_column(:answers, :display_type, :string)
   -> 0.0013s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `hide_label' for #<Answer:0xbe45cf4>/home/laziendo/.rvm/gems/ruby-2.1.1/gems/activemodel-4.1.0/lib/active_model/attribute_methods.rb:435:in`method_missing'

that one
