### ISSUE TITLE
How can I find next question? 

### ISSUE THREAD

**Issue by ZuevEvgenii** [NUARIG/surveyor#348]
Can I find a question which I need to show next based on previous answers (taking in consideration all dependencies)? I tried to find a method (e.g next question) in the source code but not found it.

**Comment by rsutphin** [comment]
Generally, Surveyor's model is not one of "what question is next" but rather "which questions are eligible to be answered". 

This sort of question is better directed at the [mailing list](https://groups.google.com/group/surveyor-dev). This issue tracker is for concrete bug reports and feature requests. If you'd like to discuss it further, please go to the [list](https://groups.google.com/group/surveyor-dev).
