### ISSUE TITLE
Unify surveyor web and iOS' serialized datetime/date/time response value

### ISSUE THREAD

**Issue by jdzak** [NUARIG/surveyor#355]
Currently both surveyor web and surveyor iOS have different representation for datetime/date/time when serializing a response value. Below is an example of the representations.

| type | Surveyor (web) | surveyor (iOS) |
| --- | --- | --- |
| datetime | 2012-08-06T05:18-00:00 | 08/06/2012 05:18 |
| date | 2012-08-06T00:00-00:00 | 08/06/2012 |
| time | 2012-08-06T05:18-00:00 | 05:18 |

I would like to propose unifying the format so it would look more like below.

| type | Unified representation |
| --- | --- |
| datetime | 2012-08-06T05:18-00:00 |
| date | 2012-08-06 |
| time | 05:18 |

**Comment by rsutphin** [comment]
Another plus for this unified representation is that these will be the native storage serializations if/when we convert everything everything to strings.

**Comment by jdzak** [comment]
Corrected the surveyor (web) serialized date/time representation.

**Comment by 1samhicks** [comment]
According to ISO 8901, "-00:00" is disallowed. This _is_ allowed in RFC3339, however. Therefore, are we using the RFC3339 format for time zone offsets? For whatever reason, RFC3339 time zone offsets is not explicitly allowed in the Foundation class library. Please see http://stackoverflow.com/questions/3094730/iphone-nsdateformatter-timezone-conversion which links to unicode.org as the reference for what the NSFoundation wants. Do we care what NSFoundation wants? More importantly, why doesn't NSFoundation like this format (I can easily do some string parsing to get around the constraints.)

**Comment by jdzak** [comment]
> Therefore, are we using the RFC3339 format for time zone offsets?

Yep. It took me a little while to verify this, but yes we are using RFC3339

> For whatever reason, RFC3339 time zone offsets is not explicitly allowed in the Foundation class library.

Yes, with iOS 5.0-5.1 we weren't able to parse the date '2012-08-06T05:18-00:00' because the timezone format omits colons (e.g. -0000 is supported, but -00:00 is not). With iOS 6.0 the [apple docs say]((https://developer.apple.com/library/mac/#documentation/Cocoa/Conceptual/DataFormatting/Articles/dfDateFormatting10_4.html#//apple_ref/doc/uid/TP40002369-SW13) it supports the unicode technical standard version tr35-25 which includes [support for timezones with colons](http://www.unicode.org/reports/tr35/tr35-25.html#Date_Format_Patterns). It looks like to parse the timezone format with colons, we just need to change the date parser in surveyor (iOS) to have ZZZZZ as the timezone format.

I'm surprised we didn't stumble across this parsing issue sooner. I opened a [bug](https://github.com/NUBIC/nu_surveyor/issues/101) in surveyor (iOS) for this.
