### ISSUE TITLE
Export CSV issue

### ISSUE THREAD

**Issue by leckylao** [NUARIG/surveyor#356]
According to article https://github.com/NUBIC/surveyor/wiki/Surveyor-Exports, it says "Surveyor currently support CSV export (YAML, JSON, XML are future possibilities)."

But by deep into the code, the export support only JSON and it only export the survey not the response. 

On the other hand, the show is exporting csv, but it's exporting the particular response_set and format is totally different from the article. The article is really misleading.

**Comment by yoon** [comment]
Surveyor does support exporting a response set to CSV:

https://github.com/NUBIC/surveyor/blob/master/lib/surveyor/surveyor_controller_methods.rb#L28

and it is now the future in which we also support JSON export if both the survey definition and response sets. We'll update the wiki to reflect that.

mark

[_][_][_]
tiny keyboard, please excuse typos and brevity

**Comment by leckylao** [comment]
@yoon , I think you want to refer to L52, which is what I mentioned above. It has two issues, firstly the to_csv is not output the correct format as the export article saying, currently it's output a lot of un-relavent stuff from the table. Secondly, it's only exporting the particular response_set, but from the export article, it's outing all the response_set.

**Comment by yoon** [comment]
@lecky could you create a new issue with a more specific request? if you believe that output isn't in the correct format, for example, you might create an issue "change output format of csv export". if you believe that it should export all response sets, then you might create an issue "export all response sets". if you'd like to start a discussion, then groups.google.com/group/surveyor-dev is the right place.

**Comment by leckylao** [comment]
@yoon, Why u close it? Don't u realise the export article is exporting all the response_set and the code doesn't, which is definitely a issue?

**Comment by leckylao** [comment]
question.text   question.short_text question.help_text  question.pick   question.reference_identifier   question.data_export_identifier question.common_namespace   question.common_identifier  question.display_order  question.display_type   question.is_mandatory   question.display_width  question.custom_class   question.custom_renderer    answer.text answer.short_text   answer.help_text    answer.weight   answer.response_class   answer.reference_identifier answer.data_export_identifier   answer.common_namespace answer.common_identifier    answer.display_order    answer.is_exclusive answer.display_length   answer.custom_class answer.custom_renderer  answer.default_value    answer.display_type response.datetime_value response.integer_value  response.float_value    response.unit   response.text_value response.string_value   response.response_other response.response_group response.created_at response.updated_at
Please nominate your old provider   Please nominate your old provider       one 7   please_nominate_your_old_provider           9   dropdown    TRUE                XXX XXX         answer  28  XXX         7   FALSE                   default                                 2012-08-17 10:20:11 +1000   2012-08-17 10:20:11 +1000

**Comment by leckylao** [comment]
@yoon , Above is what I got from the export CSV, It's directly output the DB values, But the export article didn't. It's totally different format and misleading.

**Comment by yoon** [comment]
this issue was closed because it was not a specific request. we'll update the wiki.

**Comment by leckylao** [comment]
Hey @yoon , issue is to report a issue like bug or feature. So it's not just for request. And this is the right place to report bug.

**Comment by leckylao** [comment]
@yoon , FYI, I have to implement a generate_csv feature for my current project as per request from my manager, which can basically match ur wiki. And should be a fix for this issue.
