### ISSUE TITLE
Getting "undefined method 'survey_version'" when I run rake survey

### ISSUE THREAD

**Issue by jasnow** [NUARIG/surveyor#358]
When I run the following command, I get **"undefined method 'survey_version'.**
I forked your app, cloned, created testbed, and ran same command and it worked then.

**rake surveyor FILE=surveys/kitchen_sink_survey.rb**
--- Parsing /Users/whitemac/source/SoftwareQualityCraft/surveys/kitchen_sink_survey.rb ---
rake aborted!
undefined method `survey_version' for #Survey:0x007ff4d9ca62c0

Tasks: TOP => surveyor => surveyor:parse
(See full trace by running task with --trace)

**Comment by rsutphin** [comment]
`survey_version` is a new attribute in the [next version of surveyor](https://github.com/NUBIC/surveyor/blob/master/CHANGELOG.md). You would get this error if you updated the code from master without applying the new migrations with `script/rails generate surveyor` followed by `rake db:migrate`. Does that describe your situation?

**Comment by jasnow** [comment]
Fixed, did "rails destory surveyor:install; rails g surveyor:install" then "rake db:drop db:migrate db:test:prepare'.
Now I works for **rake surveyor FILE=surveys/kitchen_sink_survey.rb**
--- Parsing /Users/whitemac/source/SoftwareQualityCraft/surveys/kitchen_sink_survey.rb ---
--- Done /Users/whitemac/source/SoftwareQualityCraft/surveys/kitchen_sink_survey.rb ---

**Comment by jasnow** [comment]
Fixed, did "rails destory surveyor:install; rails g surveyor:install" then "rake db:drop db:migrate db:test:prepare'.
Now I works for **rake surveyor FILE=surveys/kitchen_sink_survey.rb**
--- Parsing /Users/whitemac/source/SoftwareQualityCraft/surveys/kitchen_sink_survey.rb ---
--- Done /Users/whitemac/source/SoftwareQualityCraft/surveys/kitchen_sink_survey.rb ---

**Comment by rsutphin** [comment]
I'm glad that worked for you. In general, you should not need to drop your database to upgrade surveyor, though. Just running the installer again followed by running `db:migrate` should be sufficient.
