### ISSUE TITLE
 ArgumentError in SurveyorController#create 

### ISSUE THREAD

**Issue by tmeasday** [NUARIG/surveyor#36]
Hey. I'm getting this issue using surveyor in development mode with phusion. Can't say I properly understand what's going on but see these two:
http://dev.rubyonrails.org/ticket/6001
http://strd6.com/?p=250

I don't properly understand what the right fix is, but a simple one is to add 'unloadable' to the definition of SurveyorController. Apparently (according to the comments of the second link) that is deprecated, but I can't find any Rails documentation about this.

**Comment by brian-lc** [comment]
Hi, we have seen this error with the internal usage of the plugin and are working on a fix for it. Thanks for reporting.

**Comment by yoon** [comment]
Could you help us replicate the problem? We are seeing this internally with some special before_filters when customizing surveyor controller. Are you using the plugin or gem, and are you extending it at all?

**Comment by yoon** [comment]
remove surveyor controller from load_once_paths. fixes issue with dependencies and unloading in development. closed by 5267bf9165988def8139193b250abc6036c4b1df

**Comment by tmeasday** [comment]
Not sure if you still need this info, but there wasn't anything special about my setup. Pretty much a clean install of surveyor as a gem, using the kitchen sink survey.
