### ISSUE TITLE
Exception on jquery.blockUI

### ISSUE THREAD

**Issue by sweded** [NUARIG/surveyor#364]
I updated to `surveyor (0.23.0.pre f61adbb)` which raised in exception in `Surveyor#new`.

```
couldn't find file 'surveyor/jquery.blockUI'
  (in /Volumes/Pig/Users/arrow/Code/assessory/app/assets/javascripts/surveyor_all.js:5)
```

Removing `//= require surveyor/jquery.blockUI` resolves this.

**Comment by rsutphin** [comment]
When you update to a new version of surveyor, you will often need to re-run surveyor's generator to get new/updated assets and migrations. I believe that would have taken care of this issue. Did you try that?

**Comment by sweded** [comment]
I like going at things the hard way ^_^ 

I didn't run the generator initially. I added the line back and ran it and can confirm the generator is working.
