### ISSUE TITLE
Bug in surveyor_controller.rb

### ISSUE THREAD

**Issue by tmeasday** [NUARIG/surveyor#37]
Line #29 says
    if (@survey = Survey.find_by_access_code(params[:survey_code])) && (@response_set = ResponseSet.create(:survey => @survey, :user_id => @current_user))

Shouldn't is say:
    if (@survey = Survey.find_by_access_code(params[:survey_code])) && (@response_set = ResponseSet.create(:survey => @survey, :user => @current_user))

(the results it was creating didn't properly have users attached).

**Comment by brian-lc** [comment]
Yes, I believe that you are correct. We will fix this in the next release.

**Comment by yoon** [comment]
it depends, @current_user can be nil. i'll fix with a check for respond_to?(:id)

**Comment by yoon** [comment]
@current_user.id if @current_user isn't nil. Closed by 95fd53008d854c74d51672af2236c0d0e578330c
