### ISSUE TITLE
Survey - model and controller name conflicted.

### ISSUE THREAD

**Issue by ajahongir** [NUARIG/surveyor#372]
i have a project wich already have wrore, and i wanted to add some survey module.
and i run into problem. promlem is i have already survey_controller and survey model.
i vanted to override by cotomizing the Surveyor(Survey) model BUT i couldnt do that because when gem loads it already initiate Survey model.

what can i do in this case?

**Comment by rsutphin** [comment]
Questions like this are best sent to [surveyor-dev](https://groups.google.com/group/surveyor-dev). In fact, a similar one [was asked recently](https://groups.google.com/group/surveyor-dev/browse_frm/thread/8f594baf37a2a4d9/6dd74832259232da?lnk=gst&q=rename#6dd74832259232da). 

The short answer is that you'll either need to rename your Survey model and controller, or you'll need to fork surveyor, rename its Survey model and controller, and change all the references.
