### ISSUE TITLE
The answer partial is missing answer help text

### ISSUE THREAD

**Issue by jefflunt** [NUARIG/surveyor#373]
https://github.com/NUBIC/surveyor/blob/master/app/views/partials/_answer.html.haml

Answers do not display help text - not to be confused with **questions** which **do** have their help text shown.

**Comment by jefflunt** [comment]
One possible fix for this is to add something like `%span.answer-help=a.help_text` as the last line to the partial, such that the line is inside the `= f.semantic_fields_for i, r do |ff|` block.

**Comment by markedmondson** [comment]
It doesn't look like the answer.help_text gets rendered anywhere. It would be useful in _question_group.html.haml to have it rendering in line 18 alongside:
<code>%th= a_text(a)</code>

That way it could partly resolve some of #380 too and allow for the help text to display underneath the answer after a line break?
