### ISSUE TITLE
Grid Answers leaking to other grids

### ISSUE THREAD

**Issue by jsurrett** [NUARIG/surveyor#375]
If you have multiple grids in the same survey, they answers from the first grid will be added to the answers of the second grid, and so on. Example:

first grid with answer choices A, B will show choices A and B
second grid with answer choices C, D will show choices A, B, C and D
third grid with answer choices E, F will show choices A, B, C, D, E and F
etc

You can reproduce this:
   using either ruby 1.8.7 or 1.9.3
   a new rails app
   surveyor 1.0.0
   the kitchen_sink_survey (under the complicated questions section)

It seems like a parser issue when importing the survey but I can't find it yet.

**Comment by rsutphin** [comment]
Thanks for the report. Can you please provide an example Surveyor DSL file that shows this problem in a clean rails app? You can either create it as a [gist](https://gist.github.com/) and add a comment with the link (preferred) or paste it right into a code block in a comment.

**Comment by jsurrett** [comment]
The kitchen_sink_survey.rb provided by surveyor exhibits this problem. Clean rails app (3.2.8) Surveyor (1.0.0)

**Comment by rsutphin** [comment]
Curious. I don't see this with the kitchen sink on Surveyor 1.0.0 or current master using the kitchen sink that's present in each version. I'm testing on OS X, Ruby 1.9.3-p194, Rails 3.2.8. What's your environment?

**Comment by rsutphin** [comment]
Scratch that; reading comprehension failure on my part. It's the _answers_ that are being duplicated — I was looking at the questions. I do see answer duplication with 1.0.0.

**Comment by rsutphin** [comment]
> with 1.0.0.

... and current master.

**Comment by jsurrett** [comment]
Found the solution.

In the lib/surveyor/parser.rb file
    the :grid_answers context was not being cleared in the module SurveyorParserQuestionGroupMethods
    insert :grid_answers, into line 175

That method should be:

# QuestionGroup model

module SurveyorParserQuestionGroupMethods
  def parse_and_build(context, args, original_method, reference_identifier)
    # clear context
    clear(context)

```
# build and set context
self.attributes = ({
  :text => args[0] || "Question Group",
  :display_type => (original_method =~ /grid|repeater/ ? original_method : "default")}.merge(args[1] || {}))
context[:question_group] = self
```

  end
  def clear(context)
    [ :question_group,
      :grid_answers,
      :question,
      :dependency,
      :dependency_condition,
      :answer,
      :validation,
      :validation_condition ].each{|k| context.delete k}
  end
end
