### ISSUE TITLE
Table alignment in grids goes wonky when answer labels are multi-line

### ISSUE THREAD

**Issue by jefflunt** [NUARIG/surveyor#380]
When you have a grid that has answer labels that are multi-line, and especially if the answers have a different number of lines between answers, the table alignment goes askew.

Reproduced this against the latest version of surveyor, using the kitchen sink survey and default CSS.

Ignoring the obvious `html_safe` issue present in this screenshot (which is an unrelated issue in my app), you can clearly see both the vertical and horizontal layout issues where radio buttons don't line up with one another, and the bottoms of answer labels aren't on a consistent baseline, etc.

http://imgur.com/XUCjj

I would propose (and will probably submit a patch for) aligning the answer labels along a bottom baseline (vertically), and the radio buttons as close to centered (vertically and horizontally) in relation to their answers and questions (table rows).

The other issue here is that the columns in the table aren't consistent widths. I'm not sure what to do about that just yet, but the vertical alignment of things is the more major issue, if both cannot be achieved right away.

**Comment by yoon** [comment]
I'm unable to re-created this in the latest surveyor with a simpler survey:

```
survey "vertical" do
  section "spider" do
    grid "the itsy" do
      a "one"
      a "two<br/>two"
      a "three<br/>three</br>three"
      q "one", :pick => :one
      q "two", :pick => :one
      q "three", :pick => :one
    end
  end
end
```

using `.html_safe` temporarily

As for consistent horizontal widths in grids, this may not always be desirable - say if you have a really wide answer next to a bunch of short ones - making them all wide may push the grid beyond the right edge. You can selectively make it consistent, though, via custom_class and css rules.

**Comment by jefflunt** [comment]
This is fine for now - the latest version of master, indeed, does not seem to exhibit this behavior anymore. I'll reopen if it comes back up.
