### ISSUE TITLE
Surveyor is not a class error in Rails 3.2.9

### ISSUE THREAD

**Issue by braidn** [NUARIG/surveyor#382]
After running `bundle install` this is the result of rake db:migrate. The rest of the error:

``` bash
db/migrate/20121127190871_update_blank_api_ids_on_question_group.rb:2:in `<top (required)>'
```

**Comment by rsutphin** [comment]
That is curious. Can you give us:
- The remainder of the stacktrace, including the type of the exception
- What version of Surveyor you're using?

**Comment by braidn** [comment]
This gist: [gist](https://gist.github.com/4157152) and gem version 1.1.0

**Comment by rsutphin** [comment]
Thanks. From the gist, it looks like your Rails application' name is `survey`. That means that Rails will have generated a module named `Survey` to contain your application's `Application` class. (Check out config/application.rb.)

Surveyor's key model is also called `Survey`, so this is a problem. Can you name your application something else?

**Comment by braidn** [comment]
And I feel foolish, thank you very much for all the help. Problem solved.

**Comment by rsutphin** [comment]
Happy to help.
