### ISSUE TITLE
Method of extending the Survey model does not work in development

### ISSUE THREAD

**Issue by mgurley** [NUARIG/surveyor#39]
The method of extending a model suggested by running
 <pre><code>script/generate extend_surveyor</code></pre>

does not work within a Rails development environment because

<pre><code>config.cache_classes = false</code></pre>

Consequently, the Survey model gets reloaded each time you reference it but the initializer code does not.  So methods start disappearing.

Maybe a different way would be to use inheritance instead of method injection.  For example:

<pre><code>class ExtendedSurvey < Survey
end
</code></pre>

**Comment by jakewendt** [comment]
Possible self extension similar to the controller?

**Comment by yoon** [comment]
surveyor config['extend'] is now an array. custom modules (e.g. SurveyExtensions are now included from within surveyor models, allowing the customizations to work on every request in development. closed by bd27650f8b92ac2622c283d6141a9cf4d0d47b3e. thanks to mgurley and jakewendt for the suggestions.
