### ISSUE TITLE
monitoring answers

### ISSUE THREAD

**Issue by osde** [NUARIG/surveyor#392]
is it possible to see the results in percented view? i mean if there are 100 people how many percent of them poll   for 1 answer or another, thanks

another question how to setup surveyor on windows 8, it really killing me, video on vimeo can't help me, 
 to see ''kitchen_sink_survey'' i run 

"bundle exec rake surveyor FILE=surveys/kitchen_sink_survey.rb"

 result is 

"rake aborted! File dies not exist: C:\blabla\surveys\kitchen_sink_survey.rb"

my gem list:

abstract (1.0.0)
actionmailer (3.2.9, 3.0.7, 2.3.4)
actionpack (3.2.9, 3.0.7, 2.3.4)
activemodel (3.2.9, 3.0.7)
activerecord (3.2.9, 3.0.7, 2.3.4)
activerecord-mysql-adapter (0.0.1)
activeresource (3.2.9, 3.0.7, 2.3.4)
activesupport (3.2.9, 3.0.7, 2.3.4)
arel (3.0.2, 2.0.10)
bigdecimal (1.1.0)
builder (3.0.4, 2.1.2)
bundler (1.2.3)
cgi_multipart_eof_fix (2.5.0)
coffee-rails (3.2.2)
coffee-script (2.2.0)
coffee-script-source (1.4.0)
erubis (2.7.0, 2.6.6)
eventmachine (1.0.0 x86-mingw32)
execjs (1.4.0)
fastercsv (1.5.5)
fastthread (1.0.1 i386-mswin32)
formtastic (2.1.1)
gem_plugin (0.2.3)
haml (3.1.7)
hike (1.2.1)
i18n (0.6.1, 0.5.0)
io-console (0.3)
journey (1.0.4)
jquery-rails (2.1.4)
json (1.7.5, 1.5.4)
linecache (0.43 mswin32)
mail (2.4.4, 2.2.19)
mime-types (1.19)
minitest (2.5.1)
mongrel (1.1.5 x86-mswin32-60)
multi_json (1.5.0)
mustache (0.99.4)
mysql (2.9.0 ruby x86-mingw32, 2.7.3 mswin32)
mysql2 (0.3.11 x86-mingw32)
node (0.0.2)
polyglot (0.3.3)
rabl (0.6.14)
rack (1.4.1, 1.2.5, 1.0.0)
rack-cache (1.2)
rack-mount (0.6.14)
rack-ssl (1.3.2)
rack-test (0.6.2, 0.5.7)
rails (3.2.9, 3.0.7, 2.3.4)
railties (3.2.9, 3.0.7)
rake (10.0.3, 0.9.2.2)
rdoc (3.12, 3.9.4)
ref (1.0.2)
ruby-debug-base (0.10.3 mswin32)
ruby-debug-ide (0.4.5)
sass (3.2.4, 3.2.3)
sass-rails (3.2.5)
sprockets (2.2.2)
sqlite3 (1.3.6 x86-mingw32)
sqlite3-ruby (1.2.1 mswin32)
surveyor (1.1.0)
thor (0.16.0, 0.14.6)
tilt (1.3.3)
treetop (1.4.12)
tzinfo (0.3.35)
uglifier (1.3.0)
uuidtools (2.1.3)

rails: 3.2.9
ruby: 1.9.3p327
mysql2
windows 8

**Comment by jefflunt** [comment]
Surveyor is a data capture and retention system, but you'll need to write reports on your own. So, if you want to see a % answers that match a given answer, for example, you need to write a report using SQL to lookup how many answers among how many response sets have a certain value or reference a certain `answer_id`, etc.

As for the `File does not exists error`, well, you're specifying a path to the survey that doesn't match where the survey is on your file system. You'll need to be in the `surveyor` folder for your command above to work. Also, please make sure you've followed [the installation instructions in the README](https://github.com/NUBIC/surveyor#installation), including running all database migrations, etc.

If you have further problems or questions, feel free to post them on our [surveyor-dev mailing list](https://groups.google.com/forum/?fromgroups#!forum/surveyor-dev). The github issues are meant for code/enhancement/bug reports and the like, as opposed to support questions.

**Comment by osde** [comment]
thanks for answer. what if i download current project(i mean all file) from github, to install on windows which versions of ruby, rail & gems i will need? if possible can you explane basic installation of it.

**Comment by jefflunt** [comment]
This is a support question, so please [post it on the mailing list](https://groups.google.com/forum/?fromgroups#!forum/surveyor-dev) rather than continuing the discussion here.
