### ISSUE TITLE
rails generate surveyor:install results in error

### ISSUE THREAD

**Issue by FreeMako** [NUARIG/surveyor#393]
rails generate surveyor:install
[...]/ruby-1.9.3-p286@rails328/bundler/gems/surveyor-a95169e36afc/lib/formtastic/surveyor_builder.rb:3:in `module:Formtastic': uninitialized constant Formtastic::SemanticFormBuilder (NameError)

tried to downgrade formtastic in Gemfile:

gem 'surveyor', :git => 'git://github.com/breakpointer/surveyor.git', :branch => 'rails3'
gem 'formtastic', '<= 2.1'

not able to do it:

$ bundle install
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/..
You have requested:
  formtastic <= 2.1
The bundle currently has formtastic locked at 2.2.1.
Try running `bundle update formtastic`

after running the update:

$ bundle show formtastic
/Users/FreeMako/.rvm/gems/ruby-1.9.3-p286@rails328/gems/formtastic-2.1.0

Get the same error:

$ rails generate surveyor:install
[...]/.rvm/gems/ruby-1.9.3-p286@rails328/bundler/gems/surveyor-a95169e36afc/lib/formtastic/surveyor_builder.rb:3:in `module:Formtastic': uninitialized constant Formtastic::SemanticFormBuilder (NameError)

Is there any way I can use surveyor with Rails3 and the current version of the required Gems?

**Comment by jefflunt** [comment]
That breakpointer repo hasn't been used for two years. You're pointing at
the wrong gem.

Use:
https://github.com/NUBIC/surveyor

-Jeff

**Comment by FreeMako** [comment]
Awesome thank you Jeff
