### ISSUE TITLE
Multiselect Field Dependency Behaviour

### ISSUE THREAD

**Issue by ingopaulsen** [NUARIG/surveyor#396]
In Kitchen Sink survey question 2 the dependent color explanation text field does not disappear after deselecting a check list field. The same is true for the second multicolor text field.

**Comment by yoon** [comment]
In the lastest surveyor, I can confirm that this happens, but only when you've selected an answer for question 1) What is your favorite color? In isolation, both dependencies on that question appear to be working correctly.
