### ISSUE TITLE
Need a way to configure questions with :display_type => :hidden, so they show up when needed

### ISSUE THREAD

**Issue by Nataliya** [NUARIG/surveyor#397]
Need a way to configure questions with :display_type => :hidden. There are cases, when those questions have to be visible - for example for testing the instruments separately of the project. If the questions are hidden and used in the dependencies, those questions won't show up, which is right when answers gets added, but if the instrument is used to test dependencies, those should be visible and selectable.

**Comment by yoon** [comment]
I think if you need to see these questions sometimes, and not others, then :display_type => :hidden isn't the right way to hide them. I would use a custom class and a separate stylesheet that hides the questions at times when needed. See #197

**Comment by rsutphin** [comment]
I agree with @yoon. I believe in the system that @Nataliya is talking about, the questions that should be hidden when deployed in the live system but visible when separately deployed for testing already have their own custom class. The live system should be modified to hide those questions.
