### ISSUE TITLE
jquery stopped working properly

### ISSUE THREAD

**Issue by FreeMako** [NUARIG/surveyor#399]
Not sure if and how this issue is related to surveyor but after installing it I got a lot of jquery exceptions as the following one:

Uncaught TypeError: Object [object Object] has no method 'live' 

In the branch of my project without Surveyor I do not get these errors.
I read on http://stackoverflow.com/ that it can be due to a double declaration of jquery.

I tried to change the order surveyor 'require calls' are made in the pipeline and even temporarily deleted surveyor_all.js but the problem persists. 

Any ideas?

Thank you very much

**Comment by rsutphin** [comment]
Surveyor doesn't actually load JQuery itself — it assumes your application has done that. Has it? (This would usually be in your `app/assets/javascripts/application.js`.)

If that's not it, can you post your `application.js`, `surveyor_all.js`, and anything else you have in `app/assets/javascripts`? You can add them in comments or in a [gist](https://gist.github.com/).

**Comment by FreeMako** [comment]
Thank you for your answer. Yes I load it in application.js:
//= require jquery
//= require jquery_ujs
//= require foundation
//= require_tree .

surveyor_all.js
// = require surveyor/jquery-ui
// = require surveyor/jquery-ui-timepicker-addon
// = require surveyor/jquery.surveyor
// = require surveyor/jquery.selectToUISlider

the file first file that started raising the error is nextTip.js (even though the function is actually empty the error is for calling the .live method)

$(".NextTipForm").live('click', function(evt, data) {

});

I get the following exception 

Uncaught TypeError: Object [object Object] has no method 'live' 

in all the files where I call

.live('click', function(evt, data) {
or
.live('ajax:success', function(evt, data) {

I get this error just in this branch which I created to install Surveyor.

I use the following gems related to Surveyor:

gem 'rails', '3.2.11'
gem 'jquery-rails'
gem 'surveyor', :git => 'https://github.com/NUBIC/surveyor.git'
gem 'formtastic'

**Comment by rsutphin** [comment]
I don't have an answer for you, but I do have two things to consider:
- What is `foundation` (in `application.js`)? Perhaps it and surveyor do not get along?
- Your `surveyor_all.js` does not include JQuery Tools. The default `surveyor_all.js` does include it. Perhaps that is causing an issue?

I don't have a concrete reason why either of these would cause the problem you are having, but they are all I'm noticing.

**Comment by yoon** [comment]
depending on your version of jQuery, the .live function may have been deprecated or removed

http://api.jquery.com/live/

the .live function is used to watch for changes. surveyor may need to be tied to a specific version of jquery, or changed to be compatible with newer as well as existing versions.

**Comment by FreeMako** [comment]
Thank you both, I guess Yoon is right: I changed the .live calls for .on as explained in the doc you linked and everything works fine.

Thank you very much!!
