### ISSUE TITLE
Why are repeaters initiallized with 3 rows?  And always append 3 rows?

### ISSUE THREAD

**Issue by mgurley** [NUARIG/surveyor#40]
app/views/partials/_question_group.html.haml  has logic that causes a repeater question to always be initialized to 3 rows?  And to always append 3 rows?  Is this configurable via the DSL?

**Comment by yoon** [comment]
This is currently not configurable. It came up as an issue on Jeff's survey, and we decided to go with convention over configuration.

**Comment by brian-lc** [comment]
I am for changing this back to one row at a time. This change will be in the next version.
