### ISSUE TITLE
answer text should recognize HTML tags

### ISSUE THREAD

**Issue by jefflunt** [NUARIG/surveyor#404]
Similar to #284 

Example, showing `<strong>` and `<br />` tags:

![Screen Shot 2013-01-29 at 3 43 36 PM](https://f.cloud.github.com/assets/618081/108810/2bbc97ca-6a5d-11e2-8db6-8b2aac3744ac.png)

**Comment by yoon** [comment]
I don't think that HTML is the best choice for formatting in Surveyor, since we expect the same survey definition to work for surveyor and nu_surveyor. #285

**Comment by yoon** [comment]
Consolidated into #413
