### ISSUE TITLE
surveyor/jquery.tools.min.js breaks jquery

### ISSUE THREAD

**Issue by FreeMako** [NUARIG/surveyor#407]
If I take away from surveyor_all.js this line

//= require surveyor/jquery.tools.min.js

all the javascripts in my app work fine. (but surveyor datepicker and other controls do not work)

If I leave it all my other .js functions do not work:

Uncaught TypeError: Object # has no method 'on' updateVotes.js:4
Uncaught TypeError: Object # has no method 'on' welcome.js:1
Uncaught TypeError: Object # has no method 'orbit' sxs.js:49
Uncaught TypeError: Object # has no method 'popover' application.js:11
Uncaught TypeError: Object # has no method 'prop'

My application.js:
//= require jquery
//= require jquery_ujs
//= require foundation
//= require_tree .

my surveyor_all.js
//= require surveyor/jquery-ui
//= require surveyor/jquery-ui-timepicker-addon
//= require surveyor/jquery.surveyor
//= require surveyor/jquery.selectToUISlider

Also when answering a question with a slider (after removed "//= require surveyor/jquery.tools.min.js" from surveyor.js)  I receive the following errors:

Uncaught TypeError: Cannot read property 'msie' of undefined jquery-ui.js:680

GET http://myapp.com:3000/images/ui-bg_highlight-soft_100_eeeeee_1x100.png 404 (Not Found) jquery.js:7125
GET http://myapp.com:3000/images/ui-bg_glass_100_f6f6f6_1x400.png 404 (Not Found)

And the answer does not get saved.

The radio button answers work.

**Comment by rsutphin** [comment]
What version of JQuery are you using?

**Comment by FreeMako** [comment]
I am using 

gem 'jquery-rails'

This gem provides:

jQuery 1.7.2
jQuery UI 1.8.18 (javascript only)
the jQuery UJS adapter
assert_select_jquery to test jQuery responses in Ruby tests

**Comment by yoon** [comment]
surveyor (currently) [comes with](https://github.com/NUBIC/surveyor/tree/master/lib/assets/javascripts) jQuery Tools 1.2.5 (which includes jQuery 1.4.2), jQuery UI 1.8.14 and some timepicker add ons. Although it might be possible to drop in replacements for these, there's no guarantee on functionality. If you do want us to upgrade jQuery, please close this ticket and create another one. There will likely be some refactoring needed.

**Comment by FreeMako** [comment]
Thank you!
