### ISSUE TITLE
Images As Part of a Question?

### ISSUE THREAD

**Issue by ghost** [NUARIG/surveyor#408]
I want to embed an image as part of the question, e.g.

![image](https://f.cloud.github.com/assets/555/117071/49a84b50-6c1d-11e2-98e1-5a04ce24c5f6.png)

I see issue #282 mentions embedding an image in an answer. Can it also be part of a question? If so, how?

Thanks?

**Comment by rsutphin** [comment]
> Can it also be part of a question? If so, how?

By examination of the code (`Surveyor::Helpers::SurveyorHelpers#q_text`), it appears that you can use an image _as_ a question in the same way as you can use an image _as_ an answer in the same way that @nicolamadio describes for an answer in #282 — i.e., with `:display_type => 'image'`. However, if you want a combination of text and image (as in your example), there is no special built in support.

Please send open-ended questions of this type to the mailing list as described in the README. This issue tracker is for concrete, reproducible bugs and planning of specifically-scoped features. If you wish to discuss this further, please send a message to the mailing list.

**Comment by ipvideomarketinfo** [comment]
My apologies. I forgot about the mailing list!
