### ISSUE TITLE
Upgrade JQuery

### ISSUE THREAD

**Issue by FreeMako** [NUARIG/surveyor#409]
From previous conversation:

surveyor (currently) comes with jQuery Tools 1.2.5 (which includes jQuery 1.4.2), jQuery UI 1.8.14 and some timepicker add ons. Although it might be possible to drop in replacements for these, there's no guarantee on functionality. If you do want us to upgrade jQuery, please close this ticket and create another one. There will likely be some refactoring needed.

**Comment by rsutphin** [comment]
Is it possible for us to use JQuery Tools without bundling a specific version of JQuery? We could then make JQuery a mandatory external dependency, but folks could pick the version they wanted to use.

**Comment by yoon** [comment]
@FreeMako all of surveyor's assets are now in the gem's lib/assets folder, so you can feel free to remove the generated surveyor assets from your app's public folder.
