### ISSUE TITLE
Duplicate responses

### ISSUE THREAD

**Issue by mgurley** [NUARIG/surveyor#41]
Surveyor sporadically saves duplicate responses.  Currently, the gem binds an ajaxSubmit  to the change event of the #survey_form.  If you have a text box as the last question in a  section and enter a response and then click the 'Previous Section', 'Next Section' or 'Finish' buttons, two put requests are submitted to the SurveyorController's update action.  One ajax request and one standard HTTP request.  These submissions are right next to each other.

Currently the update action deletes and inserts the responses every time.

<pre>
      @response_set.clear_responses
      saved = @response_set.update_attributes(:response_attributes => (params[:responses] || {}).dup , :response_group_attributes => (params[:response_groups] || {}).dup) #copy (dup) to preserve params because we manipulate params in the response_set methods
</pre>

But if the the first request has not been committed to the database by the time the second request is processed, then duplicate response occur because the first response set is not deleted.

Forcing a reload in the clear_responses method did not solve the problem:

<pre>
  def clear_responses
    question_ids = Question.find_all_by_survey_section_id(current_section_id).map(&:id)
    responses(true).select{|r| question_ids.include? r.question_id}.map(&:destroy)
    responses.reload
  end
</pre>

The workaround that I came up with was to delay the submission of the request submitted by a button with some JavaScript.

<pre>
  var pause = true;

  $('.next_section input[type=submit], .previous_section input[type=submit]').click(function () {
    var button = $(this);
    if ( pause ) {
      $(this).delay(1000, function () {
        pause = false;
        button.click();
      });
      return false;
    }
    else {
      return true;
    }
  });
</pre> 

Simply changing the implementation to  "update if exists" will probably not solve the problem because you would still need to check if the response exists.  Most likely, some kind of client-side coordination between the submission of ajax and non-ajax requests will be necessary.  Nevertheless, updating instead of deleting and inserting would be much better for auditing purposes.

**Comment by brian-lc** [comment]
Thanks Mike for letting us know about this issue and how you created a workaround to resolve it. After investigation it was found that this happens with multi-threaded hosting environments on surveys that have a text field as the last element on the form. There is a fix in for this issue that is in the latest version (0.9.10). We will look into changing how the save works and move from a delete and resave model to doing updates when possible.
