### ISSUE TITLE
index timestamp columns

### ISSUE THREAD

**Issue by yoon** [NUARIG/surveyor#418]
@yipdw  reported in #290:

Surveyor's current migrations do not index the timestamp columns. Under PostgreSQL, this requires a separate sorting stage, which isn't a cost that applications should have to pay if they don't care about order:

https://gist.github.com/f3037a93013336b6fd17

Sorting on an indexed column permits the query analyzer to use a faster index scan, but then you pay a cost on record insert.

**Comment by hannahwhy** [comment]
The point of #290 was to _remove_ the default order, not keep it around and pile more stuff on top of it.

There are many algorithms that deal with sets of responses.  Some deal with the response creation timestamp, some require an order that has nothing to do with the response creation timestamp, and some have no ordering requirement.  In none of those cases does it make sense to impose a default order on the response collection.

As it is the implementor's responsibility to select the ordering that they require, Surveyor should not add additional assumptions which may have to be worked around.  (To use a different ordering, you'd have to throw in an `with_exclusive_scope` -- this infects _all_ Surveyor client code.  Why is that necessary?)

**Comment by hannahwhy** [comment]
Additionally, the "cost" I pointed out is based on non-production data, and so the PostgreSQL query analyzer has very little to work with (read: the numbers and query plan are useless).  Indeed, indexing may add unwanted costs in applications with high writes and relatively low reads.

Like default ordering, it imposes assumptions on Surveyor clients that aren't necessarily true.

**Comment by yoon** [comment]
@yipdw we haven't kept the default order around, it's been removed[1](0e3e67f). If you change your mind and would like indexed timestamp columns, please reopen this ticket.

**Comment by hannahwhy** [comment]
No, removal is exactly what I was looking for; indexing isn't required.  Thanks.
