### ISSUE TITLE
validates_uniqueness_of :access_code

### ISSUE THREAD

**Issue by lancejpollard** [NUARIG/surveyor#42]
Should surveys have a unique access_code?

**Comment by brian-lc** [comment]
Yes, they probably should. I'll address this (and some of the other uniqueness issues that have come up recently).

**Comment by yoon** [comment]
contrain surveys to have unique access_codes. closed by 88f3f8e1475d48967b7de4959ea4220e7cabe7d5. closed by 88f3f8e1475d48967b7de4959ea4220e7cabe7d5
