### ISSUE TITLE
Spork + Surveyor may result in Formtastic::InvalidInputError

### ISSUE THREAD

**Issue by rrschmidt** [NUARIG/surveyor#425]
In case anybody runs into the same problem (took me a day to figure out). 

It's known for Formtastic and a workaround is listed here too: https://github.com/justinfrench/formtastic/issues/851

Rolling back the required formtastic version to 2.0.x (if possible) may fix this problem, too.

**Comment by yoon** [comment]
Thanks for bringing this up. Rolling back to formtastic 2.0.x would break surveyor's supports for rails 3.2[1](https://github.com/justinfrench/formtastic/blob/master/CHANGELOG#L55). i think the best we could do at this point is add the workaround to the README.

**Comment by yoon** [comment]
justinfrench/formtastic#851 has been closed since there is a workaround, same here.
