### ISSUE TITLE
require locale of survey when translations are present

### ISSUE THREAD

**Issue by flockom** [NUARIG/surveyor#426]
When a survey has translations present there is no reliable way to access the language used in the survey because it is not specified and the default locale is the server locale.

This also makes it difficult to list the languages available for a survey.

The proposed solution is to add a locale attribute to surveys which is required if any translations are present. 

If the survey locale is not required then the default locale should be changed to the survey locale so as to prevent a situation where the language specified in the survey is not accessible.

The correct default locale is also debatable

**Comment by rsutphin** [comment]
I can see value in this as a feature — allowing the survey author to specify the locale for the default text would make display of a locale selector cleaner.

However, I don't think it needs to be mandatory. The default locale can just be called "default". AFAIK, there's no need to assume anything about which locale the default text is in.

**Comment by flockom** [comment]
The issue with not requiring a locale when translations are present is that surveyor will default the locale to the servers locale. If translations exist for the servers locale then they would be displayed and there would be no*\* way to view the surveys locale. 
*\* you could pass empty or non-existent locale but that seems incorrect.

So if the survey locale is not required then this default behavior should be changed

**Comment by yoon** [comment]
our consensus: if you specify `translations`, one of the must be the "default", e.g. `translations {:es => "...", :en => :default}`
this will be validated by the parser before the survey is saved.
