### ISSUE TITLE
section complete?

### ISSUE THREAD

**Issue by kumbafu** [NUARIG/surveyor#43]
Need a way to tell if a section is complete

**Comment by brian-lc** [comment]
Yes, this is definitely something the plugin will/should support soon. In the mean time feel free to investigate how this could be done and submit a patch. :)

**Comment by yoon** [comment]
Does the ResponseSet method: mandatory_questions_complete? work for you?

**Comment by brian-lc** [comment]
I don't think I've ever used it. David uses it in Registar I think... you
might ask him

On Thu, Jun 16, 2011 at 11:08 AM, yoon <
reply@reply.github.com>wrote:

> Does the ResponseSet method: mandatory_questions_complete? work for you?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/NUBIC/surveyor/issues/43#issuecomment-1382205

## 

-Brian

blchamberlain@gmail.com
@breakpointer
