### ISSUE TITLE
Manually Setting reference_identifier has no effect

### ISSUE THREAD

**Issue by geniass** [NUARIG/surveyor#439]
surveyor (1.3.0) installed using bundler
1.3.1pre using git in bundler has the same problem

Adding an answer to a question using the syntax:

```
a "Answer 1", {:answer_reference => "1"}
```

does not actually give the answer an answer_reference. Trying to refer to the answer using `:a_1` or `condition_A :q_1, "==", {:answer_reference => "1"}` gives a `bad references` error.

See http://stackoverflow.com/questions/15788334/auto-generated-dropdown-with-dependency-in-surveyor-rails-gem

**Comment by rsutphin** [comment]
The correct syntax is:

```
a "Answer 1", :reference_identifier => "1"
```

But (as noted in the SO post) that has the same problem. If you use this syntax without a dependency condition referencing it, the reference identifier is correctly saved. So it seems like the problem is in the post-parse dependency condition verification.

**Comment by geniass** [comment]
I'm just speculating, but looking at [dependency_condition_methods.rb](https://github.com/NUBIC/surveyor/blob/master/lib/surveyor/models/dependency_condition_methods.rb) and [question_methods.rb](https://github.com/NUBIC/surveyor/blob/master/lib/surveyor/models/question_methods.rb), the method to_hash in dependency_methods accesses question.answer_ids, which doesn't appear anywhere in the question_methods.rb file.

**Comment by geniass** [comment]
Awesome it's working perfectly now. Thanks
