### ISSUE TITLE
[Syntax error] undefined method `transation' for ActiveRecord::Base:Class

### ISSUE THREAD

**Issue by harley** [NUARIG/surveyor#44]
Hello,

When I try the kitchen sink example, then click "Next section" (bottom of page), I get this:

<pre>
NoMethodError (undefined method `transation' for ActiveRecord::Base:Class):
  vendor/plugins/surveyor/app/controllers/surveyor_controller.rb:64:in `update'
  haml (2.2.20) lib/sass/plugin/rails.rb:20:in `process'
  /usr/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
  /usr/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
  /usr/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
  /usr/lib/ruby/1.8/webrick/server.rb:162:in `start'
  /usr/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
  /usr/lib/ruby/1.8/webrick/server.rb:95:in `start'
  /usr/lib/ruby/1.8/webrick/server.rb:92:in `each'
  /usr/lib/ruby/1.8/webrick/server.rb:92:in `start'
  /usr/lib/ruby/1.8/webrick/server.rb:23:in `start'
  /usr/lib/ruby/1.8/webrick/server.rb:82:in `start'
</pre>

Fixing the typo "transation" to "transaction" on line 64 of app/controllers/surveyor_controller.rb seems to get it working again.  Thought you may want to include this fix.

Thanks for the great gem.

**Comment by brian-lc** [comment]
ugh. I need to learn how to type and/or spell. Thanks for pointing this out. Fixed!
