### ISSUE TITLE
Surveys tied to a particular user??

### ISSUE THREAD

**Issue by udaykadaboina** [NUARIG/surveyor#449]
Do we have the feature of saving the survey by a user so that they can come up to the survey when they have time.

requirements:
1) Linking up the surveys to User model/Devise.
2) Saving of the survey and resuming it back at later time by a user.

**Comment by jefflunt** [comment]
There is a dev list for support issues - please direct support questions there (we're very friendly). Just email surveyor-dev@googlegroups.com

To answer your question, yes this is possible. When someone responds to a survey a `ResponseSet` is created. You can add something like a `user_id` attribute to `ResponseSet` (if it doesn't have one already), thereby tying it to a given user.

Also, the ability to resume a survey can definitely be done. When/if to lock a survey, or when/if to allow infinite revision/updates, and everything in between is an application-specific choice, and is up to the application to implement.
