### ISSUE TITLE
Issue with latest version of formtastic (2.2.1) ?

### ISSUE THREAD

**Issue by bwalsh** [NUARIG/surveyor#452]
Ran into an issue 

```
>jruby -S rails generate surveyor:install
NameError: uninitialized constant Formtastic::SemanticFormBuilder
```

> # I needed to add this in my gem file
> 
> gem 'formtastic', '~> 2.1.0'
> 
> gem 'activeadmin'
> gem 'meta_search',    '>= 1.1.0.pre'
> gem 'surveyor'

**Comment by rsutphin** [comment]
It sounds like you may be encountering the same issue as discussed in the post-closure comments on #346. Essentially, if you...
- Have a direct dependency on Formtastic (or possibly a dependency via a different library), and
- Don't provide explicit versions for either Formtastic or Surveyor

... bundler may select Formtastic 2.2.x. If this happens, bundler will also select a very old version of Surveyor.

If this is not the problem you are encountering, please create a [gist](https://gist.github.com) with a minimal application that reproduces your issue and leave a comment here.
