### ISSUE TITLE
Incompatibility with activeadmin dependencies?

### ISSUE THREAD

**Issue by FlopTheNuts** [NUARIG/surveyor#464]
Is there a version of surveyor that works with formtastic 2.2.1 as required by activeadmin?  Is there another way to get this working?  Thanks in advance!

Bundler could not find compatible versions for gem "formtastic":
  In Gemfile:
    surveyor (~> 1.3) ruby depends on
      formtastic (~> 2.1.0) ruby

```
activeadmin (>= 0) ruby depends on
  formtastic (2.2.1)
```

**Comment by yoon** [comment]
Check out the rails4 branch.
