### ISSUE TITLE
When We can have Support of Surveyor  for Mongo Db 

### ISSUE THREAD

**Issue by ghost** [NUARIG/surveyor#467]
Actually Surveyor is basically used with active record. When We can have Support for Mongo Db

**Comment by jdzak** [comment]
@bgosavi Unfortunately, I don't know of anyone working on mongoDB support for surveyor. If you're interested in forking surveyor to add mongoDB support, it looks like mongomapper or mongoid are good ORM [replacements for activerecord](http://docs.mongodb.org/ecosystem/tutorial/getting-started-with-ruby-on-rails-3/). Also, the surveyor model methods are included in modules, so they could easily be mixed into any models you have to recreate for mongomapper or mongoid.

Also, in the future please post all surveyor questions to the [surveyor google group](https://groups.google.com/forum/?fromgroups#!forum/surveyor-dev).

Thanks!
