### ISSUE TITLE
Loaded foxy fixture ids not guaranteed to be unique

### ISSUE THREAD

**Issue by jakewendt** [NUARIG/surveyor#47]
This is more of an FYI for those who may be interested and don't already know.  When using foxy fixtures, the id is generated based on the fixture label.  As the id is a finite, albeit large, number, it is not guaranteed to be unique.  A collision, intended in this case, can be demonstrated by ...

<pre>
rake surveyor FILE=surveys/kitchen_sink_survey.rb APPEND=true
rake surveyor:load_fixtures APPEND=true
</pre>

and should show something like

<pre>
Loading ............../surveys/fixtures/answers.yml...
Appending, skipping delete...
rake aborted!
Mysql::Error: Duplicate entry '943057946' for key 'PRIMARY': INSERT INTO `answers` (`question_id`, `is_exclusive`, `created_at`, `updated_at`, `hide_label`, `text`, `response_class`, `id`, `short_text`, `display_order`, `reference_identifier`, `data_export_identifier`) VALUES (304607657, 0, '2010-03-24 23:21:39', '2010-03-24 23:21:39', 0, '2', 'answer', 943057946, '2', 5, NULL, '2')
</pre>

In the random chance that this collision occurs on 2 labels that are not identical in the middle of a fixture load, you will be left with a mess.  The only foreseeable solution would be to regenerate the fixtures and try again.

**Comment by brian-lc** [comment]
Thanks for the FYI. I am not entirely thrilled with the fact that we generate fixtures to begin with. You could also tweak the offending id but that could be just as hairy depending on where in the object dependency graph it is. Regenerating would be the best thing to do (as you said). If you have any ideas for how to improve the survey loading process please feel free to fork and fix. PDI as they say :)

**Comment by yoon** [comment]
The same could happen in ActiveRecord Fixtures:

  def self.identify(label)
    Zlib.crc32(label.to_s) % MAX_ID
  end

We do our best to make the labels unique by adding both the date-time stamp, a unique counter, and the underscored short version of the text.
