### ISSUE TITLE
bug when installing surveyor (rails 4)

### ISSUE THREAD

**Issue by jellevanveenen** [NUARIG/surveyor#470]
i'm stuck setting up a simple rails survey using the surveyor gem. I am following the basic instructions given here, on a new rails project: http://nubic.github.io/surveyor/

additionally, my gemfile includes the following in order to deal with rails 4 issues:

gem 'surveyor', :git => 'git://github.com/NUBIC/surveyor.git', :branch => 'rails4'
gem 'formtastic'
when i try to run the demo survey (kitchen sink), i end up with the following error:

NoMethodError in SurveyorController#edit
undefined method `with_sections_and_questions' for #Class:0x007fe84d519450

more info can be found here: http://stackoverflow.com/questions/21722076/surveyor-gem-nomethoderror

**Comment by caboteria** [comment]
You'll probably want to look at the changes I made for Rails4 support:
https://github.com/NUBIC/surveyor/pull/468

**Comment by jellevanveenen** [comment]
Thanks for your comment. I've tried to include your changes with 
`gem 'surveyor', :git => 'git://github.com/ferrisoxide/surveyor.git', :branch => 'rails4'`
(is that the correct branch?)

But i get an error with bundle install:

```
Git error: command `git rev-parse rails4` in directory
/usr/local/rvm/gems/cache/bundler/git/surveyor-4fc4f24b780930914db12da43748f28e197b2c6c has failed.
    If this error persists you could try removing the cache directory
'/usr/local/rvm/gems/ruby-2.0.0-p247/cache/bundler/git/surveyor-4fc4f24b780930914db12da43748f28e197b2c6c'
```

the error persists after removing the cache. Maybe i am missing something? (not very experienced with rails).

ps: please let me know if this is the wrong place for asking these questions!

**Comment by ferrisoxide** [comment]
Oooh.. don't trust my fork! That was a quick hack to get things working.
All I manage to get right were the tests (and I got a lot wrong). OK.. I
will.. any day now... get back to it.

**Comment by caboteria** [comment]
@jellevanveenen try this:

```
gem 'surveyor', github: 'caboteria/surveyor', branch: 'rails4'
```

@ferrisoxide if you could take a look at my rails 4 branch I'd appreciate any feedback.  Works great for me!

**Comment by jellevanveenen** [comment]
Hi, thanks for the suggestion; however  i still get an error:

```
RuntimeError in SurveyorController#new
`attr_accessible` is extracted out of Rails into a gem. Please use new recommended protection model for params(strong_parameters) or add `protected_attributes` to your Gemfile to use old one.
```

I think i'll give surveyor another go once it's properly updated.

**Comment by caboteria** [comment]
@jellevanveenen - try adding the protected_attributes gem to your Gemfile

**Comment by jellevanveenen** [comment]
@caboteria That seems to work! thanks!
