### ISSUE TITLE
formtastic 2.3.0 integration?

### ISSUE THREAD

**Issue by JavkhlanShirendev** [NUARIG/surveyor#474]
I am currently having a problem in my project which has active_admin gem that depends on formastic 2.3.0 while surveyor asks for 2.2.1.

How do i resolve this?

bundler error message:

```
Bundler could not find compatible versions for gem "formtastic":
In Gemfile:
surveyor (>= 0) ruby depends on
  formtastic (~> 2.2.1) ruby

activeadmin (>= 0) ruby depends on
  formtastic (2.3.0.rc3)
```

**Comment by yoon** [comment]
@QueenOfPain you can either fork our gem and change the gemspec, or wait for us to upgrade surveyor to a later version of formtastic. It may not happen until formtastic 2.3.0 is out of rc. Also, it is possible that we'll be moving to simple_form, which would also solve this dependency issue.
