### ISSUE TITLE
adding surveyor to Gemfile keeps pulling 0.20.0 version

### ISSUE THREAD

**Issue by stanlx** [NUARIG/surveyor#476]
I looked at the other similar issue - https://github.com/NUBIC/surveyor/issues/346 but I can't resolve it. 

I just installed rails 4.0.4 and ruby 2.0.0, so really really fresh install. When I add 
_gem "surveyor"_
and do 'bundle update' it keeps pulling surveyor 0.20.0. I don't have formtastic gem at all, so not sure where/what I need to change.

I tried adding formtastic explicitly 
_gem 'formtastic'_
_gem 'surveyor', '~> 1.3'_

but when I do bundle install it complains that  

> Bundler could not find compatible versions for gem "rails":
>   In Gemfile:
>     surveyor (~> 1.3.0) ruby depends on
>       rails (~> 3.0) ruby
>     rails (4.0.4)

**Comment by yoon** [comment]
Until we release a version of surveyor that has Rails 4 in its gemspec (likely in the next week), you'll need to tie it to master.

gem 'surveyor', :github => "NUBIC/surveyor", :branch => "master"
