### ISSUE TITLE
Having a counter_cache column defined in the extension causes double incrementations

### ISSUE THREAD

**Issue by jakewendt** [NUARIG/surveyor#49]
I attached my ResponseSets to a Subject and added 
<code>belongs_to :subject, :counter_cache => true</code>
to the base.class_eval section of the ResponseSetExtensions.  Now when I add a new response set, the counter cache column in the subject is double incremented.  I doubt that this is a Surveyor issue, but I fixed it by wrapping the association in a condition like

<pre><code>unless base.instance_methods.include?('subject')
   belongs_to :subject, :counter_cache => true
end
</code></pre>

This sounds more like a rails problem, but it shows its head here.  Has anyone else seen this?

**Comment by brian-lc** [comment]
We have not seen this but I'll leave this issue open for others to read and comment on.

**Comment by jakewendt** [comment]
With the addition of self extending models, this behavior seems to have gone away for me.

Thanks.
