### ISSUE TITLE
`<module:Formtastic>': uninitialized constant Formtastic::SemanticFormBuilder (NameError)

### ISSUE THREAD

**Issue by Jngai** [NUARIG/surveyor#491]
Judys-MacBook-Air:hopesurveyorwork judyngai$ rails g surveyor:install
/Users/judyngai/.rvm/gems/ruby-2.1.1@rails4.1/gems/surveyor-0.20.0/lib/formtastic/surveyor_builder.rb:3:in `module:Formtastic': uninitialized constant Formtastic::SemanticFormBuilder (NameError)

tried with rails 4.1 and rails new app to test out surveyor
ran the generator and got the error above.

**Comment by Joe-Gjelaj** [comment]
@Jngai How did you solve this problem, I am getting the same error.

**Comment by Jngai** [comment]
@Joe-Gjelaj  I did not solve the problem. Are you using rails 4? if you look at /surveyor.gemspec, you will see the formtastic dependency to be locked at 2.2.1 so this gem needs an upgrade.

**Comment by rsutphin** [comment]
Note this part of the stack trace:

```
.../gems/surveyor-0.20.0/...
```

Bundler is pulling in a very old version of Surveyor for you (0.20.0), similar to the problem [discussed in the comments](https://github.com/NUBIC/surveyor/issues/346#issuecomment-15550207) on #346. Give an explicit version of Surveyor in your Gemfile and you'll either get a working combination of gems or a more informative error message (this time from bundler).

(This is just a pointer — I'm no longer working with Surveyor so I don't have any more detailed advice to give.)

**Comment by jjangmes** [comment]
I had the same issue. Here's what I did to solve the issue 

In your gem, update your surveyor gem to be like below

```
gem 'surveyor', :github => "NUBIC/surveyor", :branch => "master"
```

This updated the surveyor gem to the latest one. Mine was also stuck at 0.20.0.  For the formtastic gem, I didn't specify a specific version, instead I just had

```
gem 'formtastic'
```
