### ISSUE TITLE
:one_integer missing from renderer

### ISSUE THREAD

**Issue by jakewendt** [NUARIG/surveyor#51]
I currently have a situation where the question is a ":pick => :one" and one of the answers is an ":integer".  When displayed, the word "Integer" appears without a radio button or text box.  I noticed in that this answer is a ":one_integer" which does not appear in <code>app/views/partials/_answer.html.haml</code>.

I created a custom renderer to remedy this for myself, but perhaps the section ...

<pre><code>  - when :one_answer, :one_string
    - fields_for_radio(response_obj) do |radio_form|
      = radio_form.radio_button(:answer_id, answer.id, :checked => response_obj.selected?, :title => answer.text)
      = radio_form.label("answer_id_#{answer.id}", answer.text, :class => (hide_label ? "hidden" : ""))
    - if renderer == :one_string
      = response_form.text_field(:string_value, :size => 25, :maxlength => 250, :autocomplete => "off")
</code></pre>

... could be modified to be ...

<pre><code>  - when :one_answer, :one_string, :one_integer
    - fields_for_radio(response_obj) do |radio_form|
      = radio_form.radio_button(:answer_id, answer.id, :checked => response_obj.selected?, :title => answer.text)
      = radio_form.label("answer_id_#{answer.id}", answer.text, :class => (hide_label ? "hidden" : ""))
    - if renderer == :one_string
      = response_form.text_field(:string_value, :size => 25, :maxlength => 250, :autocomplete => "off")
    - if renderer == :one_integer
      = response_form.text_field(:integer_value, :size => 5, :maxlength => 10, :autocomplete => "off")
</code></pre>

... or something similar.

**Comment by yoon** [comment]
added one_integer renderer. closed by f3db5b8a3d800c4127edc3148e99a5bd94e04a21
