### ISSUE TITLE
Surveyor installed as a gem not loaded correctly under Rails 2.3.5 and bundler 0.9.14

### ISSUE THREAD

**Issue by mgurley** [NUARIG/surveyor#52]
Using surveyor as a gem under Rails 2.3.5 and bundler 0.9.14 does not work.  I receive the following error upon trying to load my application:

`load_missing_constant':NameError: uninitialized constant Surveyor::Config

The rails guide on plugins suggest that any plugin packaged as a gem should have a rails/init.rb file:  http://guides.rubyonrails.org/plugins.html. This blog post suggest the same: http://patshaughnessy.net/2009/12/12/how-to-convert-a-rails-plugin-into-a-gem

I added a rails folder to my local gem installation and copied the init.rb file from the root to the new rails folder.   Event though the init.rb file is empty, this was enough to get the Surveyor module loaded under a Rails 2.3.5 app using bundler 0.9.14.  My app is now working locally with the modified local gem.

**Comment by yoon** [comment]
adding rails init.rb to make gem loading work. thanks mike gurley. closed by ea156a14ce25f1fa2456b020e9451a8fa0294647.
