### ISSUE TITLE
extend response_set?

### ISSUE THREAD

**Issue by jibblett** [NUARIG/surveyor#53]
i need a scheme where a user creates many response_sets over time to the same 'survey', distinguisned by an attribute i would add to response_set.  the scenario is a periodic performance evaluation by a trainer of a trainee.  doable?

**Comment by yoon** [comment]
Absolutely. A user is not restricted to one response set per survey. 

Unless you specifically need add an attribute the response sets, you can just use an existing attribute, such as date (created_at), to distinguish between the response sets.

If you needed to add an attribute, you would just create a migration in your app adding it to response_sets.

Your app should have its own controller and actions for a user to see their previous response sets, or start a new one.

**Comment by jibblett** [comment]
cool - just wanted to make sure i didn't miss a gotcha while reading the code.  nice job, guys.

**Comment by yoon** [comment]
thanks. :) we have a lot more to do!
