### ISSUE TITLE
rake surveyor FILE=surveys/kitchen_sink_survey.rb

### ISSUE THREAD

**Issue by rtacconi** [NUARIG/surveyor#56]
Hi, that rake command does not work. You should put rake surveyor FILE=surveys/kitchen_sink_survey.rb FIXTURES=surveys/fixtures

**Comment by yoon** [comment]
Could you let us know what version of rails you are working with? This command works without the FIXTURES argument in Rails 2.3.5 and 2.3.8 on my machine.

**Comment by rtacconi** [comment]
I use 2.3.5

**Comment by rtacconi** [comment]
I am using the plug-in

**Comment by brian-lc** [comment]
So, we added this feature to loading but did not document it (until now, sorry about the mixup). You can specify where the fixtures are loading from for the rake task, this was mandatory in master but I just pushed a commit to make it optional.
