### ISSUE TITLE
views/surveyor/edit.html.haml

### ISSUE THREAD

**Issue by rtacconi** [NUARIG/surveyor#57]
errors in line 6 root_url

and

ActionView::TemplateError (undefined method `section_status' for #ResponseSet:0x101fc7ea0) on line #18 of vendor/plugins/surveyor/app/views/surveyor/edit.html.haml:

**Comment by brian-lc** [comment]
Thanks for catching this, it was a mistake for me to commit these changes to master. You should no longer see these errors, however... the date/time picker UI element is now broken. But this is less of a showstopper

Thanks for reporting the issue.
-Brian
