### ISSUE TITLE
database error while installation and running

### ISSUE THREAD

**Issue by satishkn** [NUARIG/surveyor#61]
Hi,

I have installed the surveyor (0.11.0). 
Even the db migration step indicates that the migration was successful.
When I try to execute the following command:
 rake surveyor FILE=surveys/kitchen_sink_survey.rb,

I get the following d/b error:

D:\satish\ror\projects\surveys> rake surveyor FILE=surveys/kitchen_sink_survey.r
b
(in D:/satish/ror/projects/surveys)

--- Parsing 'D:/satish/ror/projects/surveys/surveys/kitchen_sink_survey.rb' ---
S1 S1 Q1 Q2 A1 A2 A3 A4 A5 Q3 A6 A7 A8 A9 A10 Q4 A11 D1 C1 C2 C3 C4 Q5 A12 Q6 A1
3 D2 C5 Q7 A14 D3 C6 Q8 D4 C7 Q9 A15 A16 A17 Q10 A18 V1 C1 Q11 A19 V2 C2 Q12 A20
 Q13 A21 Q14 A22 Q15 A23 A24 A25 A26 A27 A28 A29 A30 A31 A32 Q16 A33 A34 A35 A36
 A37 Q17 A38 G1 Q18 A39 Q19 A40 A41 A42 Q20 A43 A44 A45 A46 A47 A48 A49 A50 A51
A52 A53 A54 A55 A56 A57 A58 A59 A60 A61 A62 A63 A64 A65 A66 A67 A68 A69 A70 A71
A72 A73 A74 A75 A76 A77 A78 A79 A80 A81 A82 A83 A84 A85 A86 A87 A88 A89 A90 A91
A92 A93 A94 A95 A96 A97 A98 A99 A100 A101 A102 A103 A104 A105 A106 A107 A108 A10
9 A110 A111 A112 A113 A114 A115 A116 A117 A118 A119 A120 A121 A122 A123 A124 A12
5 A126 A127 A128 A129 A130 A131 A132 A133 A134 A135 A136 A137 A138 A139 A140 A14
1 A142 A143 A144 Q21 A145 A146 A147 A148 A149 A150 Q22 A151 A152 A153 A154 S2 G2
 A A A Q23 Q24 Q25 G3 A A A A A Q26 Q27 Q28 Q29 A179 A180 A181 A182 A183 Q30 A18
4 A185 A186 A187 G4 Q31 A188 A189 A190 A191 A192 A193 A194 Q32 A195 Q33 A196 G5
Q34 A197 A198 Lookup Q ref 2: found Q3 Lookup A ref 1 found A6 Lookup Q ref 2: f
ound Q3 Lookup A ref 2 found A7 Lookup Q ref 2: found Q3 Lookup A ref 3 found A8
 Lookup Q ref 2: found Q3 Lookup A ref 4 found A9 Lookup Q ref montypython3: fou
nd Q5 Lookup A ref 1 found A12 Lookup Q ref montypython4: found Q6 Lookup A ref
1 found A13 Lookup Q ref montypython5: found Q7 Lookup A ref 1 found A14 --- End
 of parsing ---

Loading D:/satish/ror/projects/surveys/surveys/fixtures/answers.yml...
rake aborted!
SQLite3::SQLException: table answers has no column named parser: INSERT INTO "an
swers" ("data_export_identifier", "display_order", "hide_label", "id", "is_exclu
sive", "parser", "reference_identifier", "response_class", "short_text", "text",
 "created_at", "updated_at", "question_id") VALUES ('red', 1, 'f', 1, 'f', NULL,
 NULL, 'answer', 'red', 'red', '2010-07-09 17:30:43', '2010-07-09 17:30:43', 826
103073)

(See full trace by running task with --trace)

I have installed sqlite3-ruby, I have not provided you the complete log of earlier steps.

Would appreciate if you can suggest what I can do. Thanks,
-Satish

**Comment by yoon** [comment]
I'm not yet able to replicate this issue. What version of ruby and rails are you using? Are you installing surveyor as a gem (if so, bundler or gem dependencies), or in vendor/plugins?

**Comment by satishkn** [comment]
Hi,

ruby:  ruby 1.9.1p429 (2010-07-02 revision 28523) [i386-mingw32](on windows).
sqlite: sqlite3-ruby (1.3.0 x86-mingw32)

I have installed surveyor as gem (not as a bundler though)

Regards,
-satish

**Comment by satishkn** [comment]
trying to reopen it....

**Comment by satishkn** [comment]
Hi,

I am getting the error on column named 'parser' while inserting into 'answers'.

Hope it is helpful.
-Satish

**Comment by yoon** [comment]
We're having the same problem with Ruby 1.9.1

**Comment by satishkn** [comment]
Thanks for your response.

Does it mean we need to switch to 1.8.6 ? What would you suggest?
Any plans as to when you are planning a release to support 1.9.1? 

 -Satish

**Comment by yoon** [comment]
We'd like to fix this issue and offer support for both 1.8.7 and 1.9.1. We'd suggest using 1.8.7 for now, but we'll take a look at fixing this soon.

**Comment by yoon** [comment]
From #69 "Would appreciate if you can make a note in installation notes (of wiki) with the complete stack (ruby version, rails, d/b, etc.,) that the surveyor works well."

**Comment by yoon** [comment]
fix parser error in ruby 1.9, where instance_variables are symbols. closed by 2ceac71ac91ac14a27ac23638b7b00a6c5177c3a

**Comment by satishkn** [comment]
Thank you for the fix.
Does it mean that it will work in Ruby 1.9.1?

**Comment by yoon** [comment]
Yes, it should work in Ruby 1.9.1
