### ISSUE TITLE
Require a question to be answered

### ISSUE THREAD

**Issue by rossum** [NUARIG/surveyor#66]
Unless this is already possible with the validation rules:

Given any question (particularly pull-down or radio button types), it would be convenient to simply tag a question as "required" to complete the survey.

**Comment by yoon** [comment]
the question.is_mandatory boolean should be set to true.
then use the response_set.progress_hash method to find out if mandatory questions (and dependent questions that have been triggered and are mandatory) have been answered.

**Comment by rossum** [comment]
Is there an example of this in the kitchen_sink that I'm overlooking?
