### ISSUE TITLE
view my survey specs aren't running

### ISSUE THREAD

**Issue by yoon** [NUARIG/surveyor#67]
Anyway there seems to be some problem in the show action in surveyor_controller:
When rendering html - the view template uses the @survey variable which is not being set by the action.

The specs pass because they run in isolation mode, so the templates are not being parsed at all. If you add in line 83 of surveyor_controller_spec.rb a call to integrate_views

You'll see four failures stemming from the ' describe "view my survey: GET /surveys/xyz/pdq" ' block.

(reported by Nadav via e-mail)

**Comment by bnadav** [comment]
Sent a pull request that solves the issue.

**Comment by yoon** [comment]
view my survey specs fixed, fragment caching for surveyor#edit, localization. thanks bnadav. closed by ae5d9a45f6ca039c1c3b7985e38fe59b1a9b5125. closed by ae5d9a45f6ca039c1c3b7985e38fe59b1a9b5125.
