### ISSUE TITLE
ArgumentError

### ISSUE THREAD

**Issue by satishkn** [NUARIG/surveyor#69]
Hi,

I went through the installation process (on windows). However, I am getting an error in the last step () when executing the follwoign command:
$>  rake surveyor FILE=surveys/kitchen_sink_survey.rb FIXTURES=surveys/fixtures

Error I am getting: 
I am getting an Argument error (while loading dependencies.yml) as indicated below. Sorry for the long error message..

Loading D:/satish/ror/projects/surveys/surveys/fixtures/answers.yml...
Loading D:/satish/ror/projects/surveys/surveys/fixtures/dependencies.yml...
rake aborted!
a YAML error occurred parsing D:/satish/ror/projects/surveys/surveys/fixtures/de
pendencies.yml. Please note that YAML must be consistently indented using spaces
. Tabs are not allowed. Please have a look at http://www.yaml.org/faq.html
The exact error was:
  ArgumentError: syntax error on line 6, col -2: `  parser: #<SurveyParser::Pars
er:0x29d7d40>

  question: 20100729095338_question_4

  rule: "A or B or C or D"

20100729095338_dependency_2:

  dependency_conditions: [#<SurveyParser::DependencyCondition:0x278b440 @parser=
# <SurveyParser::Parser:0x29d7d40 @salt="20100729095338", @surveys=[#<SurveyParse

r::Survey:0x2975060 @parser=#<SurveyParser::Parser:0x29d7d40 ...>, @id=1, @surve
y_sections=[#<SurveyParser::SurveySection:0x2944760 @parser=#<SurveyParser::Pars
er:0x29d7d40 ...>, @id=1, @survey_id=1, @question_groups=[#<SurveyParser::Questi
onGroup:0x2491f40 @parser=#<SurveyParser::Parser:0x29d7d40 ...>, @id=1, @display
_type=:inline, @reference_identifier=nil, @text="How much oil do you use per day
?">], @questions=[#<SurveyParser::Question:0x28e01a0 @parser=#<SurveyParser::Par
ser:0x29d7d40 ...>, @id=1, @survey_section_id=1, @answers=[], @pick=:none, @disp
lay_type="label", @is_mandatory=true, @display_order=1, @reference_identifier=ni
l, @question_group_id=nil, @text="These questions are examples of the basic supp
orted input types", @short_text="These questions are examples of the basic suppo
rted input types", @data_export_identifier="examples_basic_supported_input_types
">, #<SurveyParser::Question:0x28bf600 @parser=#<SurveyParser::Parser:0x29d7d40
...>, @id=2, @survey_section_id'

(See full trace by running task with --trace)

.......................

Any help or pointers from anybody is appreciated in advance.
Thanks & regards,
-Satish

**Comment by yoon** [comment]
We're having the same problem with Ruby 1.9.1

**Comment by satishkn** [comment]
Thanks for your response.

Does it mean we need to switch to 1.8.6 ? What would you suggest?
Any plans as to when you are planning a release to support 1.9.1?

Would appreciate if you can make a note in installation notes (of wiki) with the complete stack (ruby version, rails, d/b, etc.,) that the surveyor works well.

Thanks & regards,
-satish
-Satish

**Comment by yoon** [comment]
Duplicates #61.

**Comment by satishkn** [comment]
Thanks for your inputs. I used 1.8.7 and the kitchen survey worked well.

-Satish
