### ISSUE TITLE
PostgreSql 8.3 Compatibility

### ISSUE THREAD

**Issue by mgurley** [NUARIG/surveyor#7]
In order to get the Surveyor plugin/gem and PostgreSql to work with my application I had to modify the following files:
app/views/question_display_types/_repeater_dropdown.html.haml
app/views/question_display_types/_repeater_default.html.haml

The call in both of these files to ResponseSet#response_for model needs to convert the argument for the response_group to a string like so:

response_set.response_for(question.id, a.id, response_group.to_s)

**Comment by yoon** [comment]
fixing response_group conversion to string, for postgresql 8.3 compatibility. closed by 8b348e331a584ac0e1dea3e9dc6b961d80e48727
