### ISSUE TITLE
'surveyor' task not found

### ISSUE THREAD

**Issue by pfriedman** [NUARIG/surveyor#74]
When using surveyor as a gem by declaring it in the Gemfile for bundler, I get the following response when calling rake surveyor FILE=surveys/___.rb

rake aborted!
Don't know how to build task 'surveyor'

Apparently the surveyor_tasks.rake file is not being loaded. However, the 3 lines in the surveyor.rb file can be run verbatim in the script/console, so the gem can be found as well as the rake file.

**Comment by yoon** [comment]
I've generated a fresh rails 2.3.8 project on ruby 1.8.7, bundled the surveyor gem, run script/generate surveyor, and am able to run the rake task. I'm also able to see the surveyor tasks when I run rake -T. What is your dev stack?

**Comment by pfriedman** [comment]
Interestingly, when I use the system ruby (1.8.7 - /usr/bin/ruby) I see the rake task. But when I use rvm (tested two versions ree-1.8.7 or ruby-1.8.7) I do not see the rake task.

**Comment by yoon** [comment]
Fixed by upgrading rvm to play well with bundler
