### ISSUE TITLE
PG: ERROR:  integer out of range 

### ISSUE THREAD

**Issue by pfriedman** [NUARIG/surveyor#75]
When creating a new response_set I get the following error:

PG: ERROR:  integer out of range

I was able to fix this by editing the migration script from: t.integer :user_id
to: t.column :user_id, :bigint

however this is not db agnostic (I believe) so this might be an issue only with particular databases (and versions)

Also note that I am using bcsec where get_current_user returns the current_user (e.g. Bcsec::User) which is not an active_record object so returning current_user.id returns the object id and not an database identifier with which to associate the response_set.

**Comment by yoon** [comment]
You should be able to customize this by overwriting get_current_user in a custom surveyor controller.
