### ISSUE TITLE
Customizing surveyor documentation

### ISSUE THREAD

**Issue by pfriedman** [NUARIG/surveyor#76]
The documentation describing how to customize surveyor says to run this:
script/rails generate surveyor:custom

both that and script/generate surveyor:custom respond similarly (depending on rails version) 
Couldn't find 'surveyor:custom' generator

Also this file does not exist:
check out surveys/README_FOR_CUSTOM_SURVEYOR.md

is generators/extend_surveyor/templates/EXTENDING_SURVEYOR meant instead?

**Comment by yoon** [comment]
fixing instructions for extending surveyor. closed by 025b4b7fd18b816fe0b1a452d761f68aca1c1913
