### ISSUE TITLE
Extending models does not work as described

### ISSUE THREAD

**Issue by oneiros** [NUARIG/surveyor#77]
When I try to extend a surveyor model as described in EXTENDING_SURVEYOR, only the class in app/models that I created gets loaded by Rails (2.3). The class that the surveyor gem provides is being ignored if a corresponding file exists in app/models.

I know there are several ways to work around this, but I am struggling with deciding what is the easiest and the most elegant way.

**Comment by yoon** [comment]
We just discovered this too - it seems to be ok as a plugin, but not a gem. Looking into it.

**Comment by yoon** [comment]
explicity require surveyor models and helper. update sweeper syntx. closed by 74aab78a65ffe05e5fd1a098fec2a05b10c13ac5

**Comment by oneiros** [comment]
Thank you so much! And keep up the good work.

**Comment by oneiros** [comment]
Thanks again, especially for pushing out a new gem so quickly. sadly, now the problem is still there, just the other way around. the original model gets loaded but my modifications in app/model/ are being ignored.

Working around it with an explicit require is possible, but does not play nice with class reloading in development mode.

**Comment by yoon** [comment]
I am using Rails 2.3.8, on rvm with ree-1.8.7-2010.01, fresh install using Bundler version 0.9.26. My gemfile includes rails, sqlite3-ruby, and surveyor. My custom survey model looks like this:

class Survey < ActiveRecord::Base
  def title
    "Custom #{super} has #{response_sets.count} response sets"
  end
end

And the modifications are being loaded. Let us know your setup and try a fresh install.

**Comment by oneiros** [comment]
the only real difference in my setup is, that i am not using bundler, but config.gem inside environment.rb.

**Comment by oneiros** [comment]
sorry for all the hassle. but it is still not working for me. i tried bundler, but it did not change anything.

so i went ahead and created a minimal rails 2.3.8 app that uses surveyor: http://github.com/oneiros/surveyor_example

I added a custom survey model with one method: test_extension_of_surveyor_model.

I tested the following steps on a different machine, just to make sure:
git clone (grab sample project)
rake gems:install (to install surveyor and dependencies)
rake db:migrate (to populate sqlite database)
script/console (fire up an irb)
Survey.new.test_extension_of_surveyor_model

And it still results in a NoMethodError :(

**Comment by yoon** [comment]
Looks like this was my mistake - I had cache_classes set to true. Taking another shot at this.

**Comment by yoon** [comment]
use modules to include model methods. reclosed by 6fe85d73b2786d18a349f59c8f93e188d27db466

**Comment by oneiros** [comment]
Once again: Thanks a lot! Everything works like a charm now.
