### ISSUE TITLE
Dependency Logic in Controller should not check if a dependent question has been answered

### ISSUE THREAD

**Issue by mgurley** [NUARIG/surveyor#8]
The  dependents method of app/controllers/surveying_controller.rb checks to see if a question has met its dependency condition _and_ been answered.  This check for the second condition causes a dependent question to disappear after you answer it:

<pre>
if dep.met?(response_set) and response_set.has_not_answered_question?(dep.question)
</pre>

I removed the check for the second condition in my application.

**Comment by yoon** [comment]
This behavior should be put in the ResponseSet model and split - for pure html (js off) we want just the unanswered dependents for the top of each page. With js, we want to show all dependencies, even those that have been answered. Working on this now...

**Comment by yoon** [comment]
moving dependency logic to repsonse set, factories and specs to match. closed by 679c54ca9090ad48528e0f006048d0a0e0f89c6d
