### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by denniscastro** [NUARIG/surveyor#84]
Hi Breakpointer
Your gem is great but I have some questions that I need to answer to client
1. I need request user data for fill the survey, like name,address,etc, I see in your table the user_id column but how implement it. 
2. I need that some questions are required, or mandatory, I see it in your table with 1 value, but I got to finish the survey without answer and it say survey completed.
3. I tried to see the result but I get this error:
   undefined local variable or method `surveyor_includes' for #ActionView::Base:0xa034738
   in file
   gems/surveyor-0.16.0/app/views/layouts/results.html.erb where line #7 raised

**Comment by brian-lc** [comment]
Hello denniscastro
Thanks for your questions.
1) We added the user_id column to help you tie a user in your app to a ResponseSet and that's about as far as we go. We leave a lot up to you to decide how you want to create a user in your app. From Surveyors perspective all it cares is make sure that the variable @current_user is set and it will put whatever id this object has into that user_id field (you can set this variable in a before_filter in the application controller if you like). 
2) This is up to you. We provide a way of identifying the mandatory/required questions but if you want to stop users from moving forward in the survey pages, or from finishing the survey we provide hooks for you to do this, either in javascript or in a redirect after the survey's finished to another controller where you check survey completeness and decide how you want to handle it.
3)  I'm seeing this error too. Please, if you would not mind, create a separate issue just for this problem in the github issue tracker. 

Thanks,
Brian

**Comment by denniscastro** [comment]
Thanks Breakpointer
I understand and will implement it next days.
Any question, i'll ask you.

Dennis
