### ISSUE TITLE
Routes problem

### ISSUE THREAD

**Issue by denniscastro** [NUARIG/surveyor#85]
Hi
Some days ago I noted this problem
If i want to see the results of one survey /surveys/results is ok but when i select  a survey for results, it go to surveyor controller
view_my_survey GET /surveys/:survey_code/:response_set_code(.:format) {:controller=>"surveyor", :action=>"show"}
Parameters: {"survey_code"=>"1", "response_set_code"=>"result"}
and It must go to
show_one_survey_results GET /surveys/:id/result  {:controller=>"results", :action=>"show"}

the order on your routes.rb is surveyor  and results

Please fix it,

**Comment by brian-lc** [comment]
If you fix it we'll accept your patch.

**Comment by denniscastro** [comment]
Ok
I'll do it tomorrow

Dennis
