### ISSUE TITLE
result problem

### ISSUE THREAD

**Issue by denniscastro** [NUARIG/surveyor#89]
hi, 
I have a question..
why do you use this line in results_helper, display_response def
sets = r_set.responses.select{|r| r.question.display_order == question.display_order}

I fill the questions and answers without display_order, so all the question.display_order column is 0 value.. and so this line gets many records, no 0, no 1, so  go to lines
  sets.each do |set|
          txt << show_answer(set) + "<br/>"
        end

is mandatory fill the column with incremental order? , try to fill all the question with display_order colunm = 0

sorry for  my english, I hope you understand

PLease explain to me the idea?

**Comment by yoon** [comment]
The display order allows you to reorder questions within a section. It doesn't have to be sequential, but it is important that the numbers be integers and unique within a survey_section.
