### ISSUE TITLE
problem with operator '!='

### ISSUE THREAD

**Issue by flonath** [NUARIG/surveyor#91]
I encounter problem with the '!=' operator in conditions. it's not functional in my application.
I use also '!' in rule, but the parser didn't create de dependancy when i use this operator.

Best regards

**Comment by yoon** [comment]
Thanks for writing in. You're right, != is an operator, and belongs in a dependency condition, not the rule.

I'm unable to replicate your issue - could you perhaps write a cucumber feature or rspec spec to illustrate? If I change the kitchen sink survey:

```
q_montypython4 "What... is your quest? (e.g. To seek the Holy Grail)"
a_1 :string
dependency :rule => "A"
condition_A :q_montypython3, "!=", {:string_value => "", :answer_reference => "1"}
```

Then "what is your quest" comes up any time I type anything in the name field.
