### ISSUE TITLE
It not work in rails3 ?

### ISSUE THREAD

**Issue by ouyangzhiping** [NUARIG/surveyor#94]
rails3 view default use not raw html.

so , the view output the err code.

the html code :

  <div id='header'> 
    <div class='title'>&amp;#8220;Kitchen Sink&amp;#8221; survey 1</div> 
  </div> 
  <div class='previous_section'></div> 
  <div class="survey_section" id="survey_section_3"><span class='title'>Basic questions</span> 
  <div class='questions'> 
    <div class="question label" id="question_35"><span class='text'>These questions are examples of the basic supported input types</span> 
    <span class='help'></span> 
    </div> 
    <div class="question" id="question_36"><div class='number'>1&lt;span style='padding-left:0.1em;'&gt;)&lt;/span&gt;</div> 
    <fieldset> 

ye, please look the [img](http://yangzhiping.com/images/github/survey.png)

**Comment by yoon** [comment]
There are a lot more issues than html_safe in the rails3 branch, which is still under development.

**Comment by ouyangzhiping** [comment]
thanks! 

I waiting the good news...

**Comment by BorjaH2E** [comment]
Yoon, do you know when we could use surveyor on Rails3?

thanks!

**Comment by yoon** [comment]
surveyor's DSL parser is currently working on rails 3, but the controllers and views are not. we're working hard, and would appreciate any help. :) feel free to fork and take on some of the issues.
